### PR TITLE
docs(rust): improve docs for `ockam enroll` and `ockam identity show`

### LINKED ISSUE #6053: Improve `ockam enroll —-help` text by changing the first paragraph of help text
## Context
When a user types `ockam enroll —-help` in their terminal, they are presented with long help text. You can improve this text content by specifying that `enroll` command will do something with the Ockam Orchestrator, the SaaS service.

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

## Current behavior
1. When you run `ockam enroll --help` in your terminal you will see the following help text.

Image

## Suggested fix
The first paragraph should say: “When you run this command for the first time, it creates a space for you in Ockam Orchestrator, the SaaS service. This is where you host your projects, as well as a default project for you within this space.” 

File that needs to be changed: [/src/enroll/static/long_about.txt](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/static/long_about.txt#L1).

Once the fix is applied, it should look like the following.

Image

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### LINKED ISSUE #6129: Add docs for `--full` to improve `ockam identity show --help`
# Current behavior 

Currently when you run `ockam identity show` you can pass a flag `--full`. This flag is currently does not have any help docs as you can see below.

Image

# Desired behavior

Add the doc comment `/// Show the full identity history, and not just the identifier or the name`. Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/show.rs#L27) to make changes.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### PR DESCRIPTION
**Pull request by Salonikansal2**
## Proposed changes

- Fixes https://github.com/build-trust/ockam/issues/6053
- Fixes https://github.com/build-trust/ockam/issues/6129

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Review by adrianbenavides — COMMENTED** [review]
Hello @Salonikansal2, thanks for putting your time in this PR 🙏 

I've noticed you opened three different PR's with the same changes. Should we close them in favor of this one?
- https://github.com/build-trust/ockam/pull/6208
- https://github.com/build-trust/ockam/pull/6212

Also, could you include in the description the issue this PR is solving? If you write something like `Fixes #{number-of-issue}` it will track it automatically and will get closed when this PR gets merged.

Let me know if you have any question!

**Review by Salonikansal2 — COMMENTED** [review]
Fixes #6053

**Review by Salonikansal2 — COMMENTED** [review]
Fixes #6054

**Comment by Salonikansal2** [comment]
@adrianbenavides , I solved two issues but they kept merging into one pr that's why i tried so many times still i am not able to resolve this 
Will this still be acceptable.
and yes please close the other two
(i tried changing branch like 10 times atleast).
Thanks for your time .

**Review by adrianbenavides — APPROVED** [review]
Thanks @Salonikansal2 for your contribution 🙏 
It will get merged ASAP 🚀

**Comment by Salonikansal2** [comment]
Thanku so much @adrianbenavides for your time and efforts in this pr. Really appreciate it. People like you and @mrinalwadhwa make open source so fun. Thanku 😇

**Review by SanjoDeundiak — APPROVED** [review]

**Pull request merged**
