### PR TITLE
docs(rust): improve documentation for `ockam relay` command

### LINKED ISSUE #6292: Improve `ockam relay --help` text to be in active voice
# Current behavior

When a user runs `ockam relay --help`, they get the following output. The first part of this output is in passive voice.

Image

# Desired behavior

Instead of passive voice, change that first paragraph of help text to be active voice using the following copy:

```
Communication topologies often encounter situations where the machine providing a service cannot or will not open a listening port or expose a bridge node to other networks. This is a common security best practice in enterprise environments, home networks, OT networks, and VPCs across clouds. Application developers may not have control over these choices from the infrastructure/operations layer. In such cases, relays are useful.
```

# Implementation details

In order to make this change, please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/static/long_about.txt#L1).

---
<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. In the PR description, include the issue that's being solved 
1. Run `cargo fmt`. You can configure the editor to run it automatically every time a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `git merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

### PR DESCRIPTION
**Pull request by Night-Amber3301**
Fixes #6292

Replaced the description for ockam relay --help command from passive voice to active voice.

### CODE REVIEW

**Comment by Night-Amber3301** [comment]
Accepted the contributor license. PR #6313

**Comment by Night-Amber3301** [comment]
any progress regarding the review process?

**Comment by nazmulidris** [comment]
@Night-Amber3301 Thank you for spending your time on this PR. 

You have two PRs open against the same issue #6292 , so I am going to close this PR and we will accept the other PR https://github.com/build-trust/ockam/pull/6309 ✅

**Comment by Night-Amber3301** [comment]
I had only one PR regarding this issue sir, and #6309 was not raised by me

**Comment by nazmulidris** [comment]
@Night-Amber3301 Sorry about the confusion 🙏🏽 . Thank you for taking the time to work on this PR 👍🏽 . I've added the `HACKTOBERFEST-ACCEPTED` label to this PR.

**Pull request closed without merging**
