### PR TITLE
chore: move `cargo release` config file to `tools/scripts/release`

### PR DESCRIPTION
**Pull request by constantinosgeorgiou**
## Current Behavior

The configuration file [release.toml](https://github.com/build-trust/ockam/blob/develop/release.toml) is located at the root of the repository, cluttering it up.

## Proposed Changes

Move  [release.toml](https://github.com/build-trust/ockam/blob/develop/release.toml) configuration file to [`tools/scripts/release`](https://github.com/build-trust/ockam/tree/develop/tools/scripts/release) and change the following scripts:

- [tools/scripts/release/crate-bump.sh](https://github.com/build-trust/ockam/blob/develop/tools/scripts/release/crate-bump.sh#L88)
- [tools/scripts/release/crate-publish.sh](https://github.com/build-trust/ockam/blob/develop/tools/scripts/release/crate-publish.sh#L72)

by adding the [`--config`](https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#configuration) parameter.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
Thank you for spending time on this, before we can merge please

- [x] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

**Comment by constantinosgeorgiou** [comment]
Done! https://github.com/build-trust/ockam-contributors/pull/125

Can you please add the `hacktoberfest-accepted` label?

**Review by mrinalwadhwa — DISMISSED** [review]
That looks great. Thank you for an awesome first contribution 🥳 

I made a small change to hardcode the path of the config file since we know that when running the script and detection with BASH_SOURCE can break sometimes.

We'll merge after @metaclips has a chance to check the change as well.

**Comment by mrinalwadhwa** [comment]
> Can you please add the hacktoberfest-accepted label?

Added 👍

**Review by mrinalwadhwa — APPROVED** [review]

**Review by metaclips — APPROVED** [review]
Approved 🚀. Thanks @constantinosgeorgiou

**Pull request merged**
