### PR TITLE
fixes#6056 added troubleshoot

### PR DESCRIPTION
**Pull request by Salonikansal2**
## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by adrianbenavides** [comment]
Hi @Salonikansal2 ! The PR looks good but I think you are creating new branches from an outdated version of the repo ( that's why the PR has 5 commits). Try running:
1. `git pull --rebase` from your `develop` branch, and then
2. `git rebase develop` from your `tres` branch
3. Then run `git push --force` from your `tres` branch

Let me know if you run into any issue with the previous instructions

**Comment by Salonikansal2** [comment]
Still it isn't working, I also tried other methods before as well

**Comment by adrianbenavides** [comment]
@Salonikansal2 you could also try to automatically sync your fork. If you go to the fork's page, you will see the following button at the top.

image

**Comment by Salonikansal2** [comment]
@adrianbenavides done.
thanku for your help ,it worked .
i have tried syncing fork before as well but this time instead of adding all the changes of repo in the branch i just added the changed file in the branch and then pushed it and also i sync the fork of repo before this .
again  thanku for taking out time to correct my silly mistakes

**Pull request closed without merging**
