### PR TITLE
feat(rust): `relay delete` return a "not found" error before prompting the user

### LINKED ISSUE #6300: Improve `ockam relay delete <ARGS>` when the relay does not exist
# Current behavior

If you run the command `ockam relay delete FOO` and the relay `FOO` does not exist, it proceeds as if it will be possible to delete that node and the user is asked for a confirmation.

Image

However, since `FOO` does not exist, pressing "Y" results in the following error message.

Image

# Desired behavior

Instead of displaying a confirmation prompt, it would be better to check whether that relay (eg: `FOO`) even exists. If it does not exist, then the command should exit and let the user know that `FOO` could not be found (so it can't be deleted). 

If `FOO` is found, then the current behavior is fine.

# Implementation details

To get started, please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/delete.rs#L19).

---
<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. In the PR description, include the issue that's being solved 
1. Run `cargo fmt`. You can configure the editor to run it automatically every time a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `git merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

### PR DESCRIPTION
**Pull request by vishal-sharma-369**
solves: #6300 

Added the handlers for condition when the relay does not exist in ockam relay delete <ARGS> command

## Proposed changes

Added the handlers for condition when the relay does not exist in ockam relay delete <ARGS> command

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@vishal-sharma-369 Thank you for spending time on this, before we can merge please

- [x] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by vishal-sharma-369** [comment]
Created the PR
#6308

**Comment by adrianbenavides** [comment]
Hey @vishal-sharma-369 , thanks for submitting the PR! 

It looks like the PR is not ready yet right? To check if a relay exists, you can send an additional request to the background node [before prompting](https://github.com/build-trust/ockam/blob/1bbe28f78d43cd96e7d8b3da3722309056852280/implementations/rust/ockam/ockam_command/src/relay/delete.rs#L54) the user as [done here](https://github.com/build-trust/ockam/blob/1a49eba84f17ea3b368aa22a1ffc6e53a474b474/implementations/rust/ockam/ockam_command/src/relay/show.rs#L48), but using `ask_and_get_reply` instead of `tell`. Then you can match the [status from the reply](https://github.com/build-trust/ockam/blob/be1067367d8680f78752af1a89af060f02dd445c/implementations/rust/ockam/ockam_core/src/api.rs#L111) to check if it's a `NotFound` error.

Here are some tips you can use while you work on this:
1. Run `cargo fmt`. You can configure the editor to run it automatically every time a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `git merge develop`

**Comment by vishal-sharma-369** [comment]
Submitted the PR with necessary modifications.

**Review by adrianbenavides — COMMENTED** [review]
Thanks @vishal-sharma-369! There is a simpler way to detect if a relay exists. Here is the code:

```rust
let relay_name = cmd.relay_name.clone();
let at = get_node_name(&opts.state, &cmd.at);
let node_name = parse_node_name(&at)?;
let node = BackgroundNode::create(&ctx, &opts.state, &node_name).await?;

// Check if relay exists
node.ask_and_get_reply::<_, ()>(&ctx, Request::get(format!("/node/forwarder/{relay_name}")))
    .await?
    .found()
    .into_diagnostic()?
    .ok_or(miette!("Relay with name '{}' does not exist", relay_name))?;
```

This snippet should be located at the beginning of the `run_impl` function, before the `if opts.terminal.confirmed_with_flag_or_prompt` block. The rest of the command should not be modified, as it will handle the deletion as expected.

Let me know if you have any questions!

**Comment by vishal-sharma-369** [comment]
@adrianbenavides Made the modifications. Is it correct now?

**Comment by vishal-sharma-369** [comment]
Are there any further modifications to do ?

**Comment by adrianbenavides** [comment]
It looks almost ready to go. I wanted to push some minor changes for you, but looks like your fork doesn't accept external users. Could you change that so I can push to your branch?

**Comment by vishal-sharma-369** [comment]
> It looks almost ready to go. I wanted to push some minor changes for you, but looks like your fork doesn't accept external users. Could you change that so I can push to your branch?

@adrianbenavides sir I am new to open source. Please guide me how to do this.

**Comment by adrianbenavides** [comment]
> > It looks almost ready to go. I wanted to push some minor changes for you, but looks like your fork doesn't accept external users. Could you change that so I can push to your branch?
> 
> @adrianbenavides sir I am new to open source. Please guide me how to do this.

Check out these two guides and double check that you don't have any restriction on your branches or fork:
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by vishal-sharma-369** [comment]
@adrianbenavides Sir, I allowed edit my maintainers from my side.

**Comment by adrianbenavides** [comment]
I've created a separate PR at https://github.com/build-trust/ockam/pull/6370 with your commit in it (giving you the full credit of the PR). It will get merged as soon as possible. Thank you so much for your contribution @vishal-sharma-369 🙏

**Comment by vishal-sharma-369** [comment]
@adrianbenavides Thank you sir

**Comment by adrianbenavides** [comment]
Closed via https://github.com/build-trust/ockam/pull/6370

Full credit to @vishal-sharma-369! 🥳

**Pull request closed without merging**
