### PR TITLE
adding default value for project_route argument

### LINKED ISSUE #4615: update `ockam service start kafka-consumer/producer` clap commands so that `--project-route` uses the default project
### Current behavior

Currently kafka consumer and producers require a project-route such as

```sh
ockam service start kafka-consumer --node consumer --project-route /project/default \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 4000 \
  --brokers-port-range 4001-4100
 ```
 
 ```sh
 ockam service start kafka-producer --node producer1 --project-route /project/default \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 5000 \
  --brokers-port-range 5001-5100
  ```

### Desired behavior

Add a default value, so that if the argument `--project-route`  is not passed, it should use `/project/default`

[Kafka Consumer Argument](https://github.com/build-trust/ockam/blob/af78ca3f6a971aa24ea8e5ff544bc17388f0dfab/implementations/rust/ockam/ockam_command/src/service/start.rs#L77-L78)

[Kafka Producer Argument](https://github.com/build-trust/ockam/blob/af78ca3f6a971aa24ea8e5ff544bc17388f0dfab/implementations/rust/ockam/ockam_command/src/service/start.rs#L95-L96)

Clap arguments have a macro to set the default value, example of this [here](https://github.com/build-trust/ockam/blob/af78ca3f6a971aa24ea8e5ff544bc17388f0dfab/implementations/rust/ockam/ockam_command/src/service/start.rs#L85).

```sh
ockam service start kafka-consumer --node consumer \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 4000 \
  --brokers-port-range 4001-4100
 ```
 
  ```sh
 ockam service start kafka-producer --node producer1  \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 5000 \
  --brokers-port-range 5001-5100
  ```
  
  ---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by 0xkelvin**
## Proposed changes
Resolves https://github.com/build-trust/ockam/issues/4615

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Comment by 0xkelvin** [comment]
issue https://github.com/build-trust/ockam/issues/4615

**Comment by adrianbenavides** [comment]
hey @0xkelvin, thanks for submitting this PR! Is this ready to review?

**Comment by 0xkelvin** [comment]
> hey @0xkelvin, thanks for submitting this PR! Is this ready to review?

hi @adrianbenavides , it haven't ready to review, i am figuring out how to test
setting up Kafka for testing according to this blog : https://docs.ockam.io/guides/examples/end-to-end-encrypted-kafka
but it is a bit hard and involving many many steps

**Comment by caoakleyii** [comment]
> > hey @0xkelvin, thanks for submitting this PR! Is this ready to review?
> 
> hi @adrianbenavides , it haven't ready to review, i am figuring out how to test setting up Kafka for testing according to this blog : https://docs.ockam.io/guides/examples/end-to-end-encrypted-kafka but it is a bit hard and involving many many steps

Hey, I was able to test this for you! This PR looks good to go.

When you have a chance if you can edit the commits within this branch to fit with the commit linter, we can get this merged in!

Thank you again!

**Comment by etorreborre** [comment]
Hi @0xkelvin it looks like those changes have eventually be rolled-in another PR: https://github.com/build-trust/ockam/pull/4788 so I propose to close this one. Thanks for giving it go though!

**Pull request closed without merging**
