### PR TITLE
fix(rust): improve ockam space list when there are no spaces

### LINKED ISSUE #6145: Improve `ockam space list` when there are no spaces in Ockam Orchestrator
# Current behavior

When there is no local state (e.g. after you run `ockam reset -y`) and you run `ockam space list` the following error is shown.

Image

# Desired behavior

It should display a message saying that local state is empty and there are no spaces in Ockam Orchestrator. The output can also provide text instructing the user to use `ockam enroll` to create a default project.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### PR DESCRIPTION
**Pull request by k1nho**
## Current behavior

Fixes #6145 

```$ ockam space list``` returns an immediate error when the local state is empty, after running a command like ```$ ockam reset -y```.

## Proposed changes

This PR improves the user experience by handling the error. Now after running ```$ ockam space list``` on an empty local state, it will show that there are no local spaces and suggest the use of ```ockam enroll``` to get the default space.

Screenshot 2023-10-03 at 1 28 46 PM

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Review by adrianbenavides — APPROVED** [review]
LGTM! Thanks @k1nho for another great contribution 🙏

**Review by etorreborre — APPROVED** [review]

**Comment by k1nho** [comment]
@adrianbenavides, I noticed I still get the error after running ```$ ockam space list```

**Comment by adrianbenavides** [comment]
Oh, I see why is this happening. Let me reopen the issue and add more details there. Thanks for the heads up!

**Comment by adrianbenavides** [comment]
> @adrianbenavides, I noticed I still get the error after running `$ ockam space list`

I've left some context answering this question in the issue comments: https://github.com/build-trust/ockam/issues/6145#issuecomment-1749052935

**Pull request merged**
