### PR TITLE
comments for AbortNode behaviour

### LINKED ISSUE #6615: Investigate why `AbortNode` message doesn't stop the node
### Observed behavior

In [this discussion](https://github.com/build-trust/ockam/pull/6445#issuecomment-1760647825) we noticed that sending an `AbortNode` message to the router doesn't cause the node to stop. We should investigate why this happens

### PR DESCRIPTION
**Pull request by adiSuper94**
fixes #6615. (Doesn't actually fix any thing)

Note: CI Tests do not need be run on this.

### CODE REVIEW

**Comment by adiSuper94** [comment]
@SanjoDeundiak

**Review by SanjoDeundiak — DISMISSED** [review]

**Comment by adiSuper94** [comment]
@SanjoDeundiak do you want this to be merged ??

**Comment by SanjoDeundiak** [comment]
@adiSuper94 yes, any objections?

**Comment by adiSuper94** [comment]
I can clean up the comments a bit if you'd like. 

Especially the numbers, I added the numbers just so that you get the order to read those comments. I am not sure they make sense in the larger code base though.

**Comment by SanjoDeundiak** [comment]
@adiSuper94 whatever you think is better. It was unclear that you want to change anything in the PR before the merge

**Comment by adiSuper94** [comment]
@SanjoDeundiak Made some edits, which might more value to future reader.

**Comment by SanjoDeundiak** [comment]
@adiSuper94 would you mind squashing the commits into one?

**Comment by adiSuper94** [comment]
done.

**Review by SanjoDeundiak — APPROVED** [review]

**Comment by SanjoDeundiak** [comment]
@adiSuper94 could you please check why your commit is unsigned?

**Comment by adiSuper94** [comment]
> @adiSuper94 could you please check why your commit is unsigned?

oops. fixed it.

**Pull request merged**
