### PR TITLE
Fix names of executables in End-to-Encryption through Kafka guide

### PR DESCRIPTION
**Pull request by sanjayatpilcrow**
## Current Behavior

Please refer to Run section in the guide [End to End Encryption through Kafka](https://github.com/build-trust/ockam/tree/develop/documentation/use-cases/end-to-end-encryption-through-kafka). The docker commands threw following errors 

`error: exec: "ockam_kafka_bob": executable file not found in $PATH`
`error: exec: "ockam_kafka_alice": executable file not found in $PATH`

## Proposed Changes
Following changes to the docker commands worked for me:
`docker run --rm --interactive --tty ghcr.io/build-trust/examples/kafka bob`
`docker run --rm --interactive --tty ghcr.io/build-trust/examples/kafka alice`

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@sanjayatpilcrow thank you for sending this 🎉

**Comment by sanjayatpilcrow** [comment]
@mrinalwadhwa Most welcome!

**Comment by sanjayatpilcrow** [comment]
@mrinalwadhwa, seems I messed up the commit message and Commit-check is failing. Would you suggest me to update commit-message with new PR? 
image

**Comment by mrinalwadhwa** [comment]
@sanjayatpilcrow no need, I'll fix the commit message for you as part of the merge.

But we need this part:

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

**Comment by sanjayatpilcrow** [comment]
@mrinalwadhwa CONTRIBUTORS.csv updated

**Review by mrinalwadhwa — DISMISSED** [review]

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
@sanjayatpilcrow thank you for an awesome first contribution 🥳

**Comment by sanjayatpilcrow** [comment]
@mrinalwadhwa :relieved: Thank you for the nice words!

**Pull request merged**
