### PR TITLE
Doriancodes/add docs to full flag

### PR DESCRIPTION
**Pull request by doriancodes**
## Current behavior

Currently when you run `ockam identity show` you can pass a flag `--full`. This flag is currently does not have any help 

## Proposed changes

Now when you run `ockam identity show` you can you can see the documentation for the  flag `--full`.

## Checks

- [x ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x ] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by adrianbenavides** [comment]
Hi @doriancodes, I'm sorry but someone else fixed [this issue](https://github.com/build-trust/ockam/issues/6129) at https://github.com/build-trust/ockam/pull/6213. We try to avoid collisions but it's really hard with so many people creating PR's!

Good news are that we have plenty of issues to choose from. I'd recommend you the following issues, which are very similar to this one: 

- https://github.com/build-trust/ockam/issues/6137
- https://github.com/build-trust/ockam/issues/6134

Thanks for spending your time on this PR and sorry again 🙏

**Comment by mrinalwadhwa** [comment]
@doriancodes Thank you got spending time on this. In case you're participating in Hacktoberfest ... Even though we decided not to land this change because of the overlap, I've added the HACKTOBERFEST-ACCEPTED label so it gets counted toward that. Thank you!

**Comment by mrinalwadhwa** [comment]
When you get a chance please add yourself to the Ockam Contributors list by accepting our [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md)

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by doriancodes** [comment]
@mrinalwadhwa thank you :)

**Pull request closed without merging**
