### PR TITLE
chore(rust)::> used `--locked` argument with `cargo run` argument

### LINKED ISSUE #3005: Improve tests on examples/rust/*
Here are some opportunities...

1. The tests in `examples/rust/get_started` do not cover significant portions of code. 
2. Some tests in `examples/rust/*` could still clash on TCP ports when run in parallel. Maybe they should ask the OS for free ports, rather then using hardcoded values (could use [portpicker](https://crates.io/crates/portpicker)?). 
3. `example_test_helper` could allow child processes to inherit environment variables from their parent. This _might_ allow child `cargo` processes to use the mold linker in CI.
4. Maybe tests in `examples/rust/*` should use the the `cargo` `--locked` argument as is done in other parts of the Ockam code base (e.g. [here](https://github.com/build-trust/ockam/blob/f6eb4126cd4ac5f7c265118ac580b70f6eea05fb/implementations/rust/build.gradle#L88)).

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### PR DESCRIPTION
**Pull request by PsychoPunkSage**
## Current behavior
Currently, things are less reproducible due to potential dependency changes (because of `cargo run`) and potentially less stable if dependency updates introduce breaking changes.

## Proposed changes
After using `--locked` flag, things become highly reproducible as dependency versions are fixed and more stable as dependency versions are locked.

Addressed #3005 **pointer 4**

### CODE REVIEW

**Comment by metaclips** [comment]
@PsychoPunkSage can you change the commit message to `chore(rust): used cargo --locked argument` also, we should use a more descriptive commit message

**Comment by PsychoPunkSage** [comment]
> @PsychoPunkSage can you change the commit message to `chore(rust): used cargo --locked argument` also, we should use a more descriptive commit message

Sure @metaclips I will keep this in mind from next time

**Comment by metaclips** [comment]
@PsychoPunkSage here's how I'll fix my commit message
```bash
git pull --rebase https://github.com/build-trust/ockam.git develop
git commit --amend -m "commit_message_here"
git push -f
```

**Review by metaclips — APPROVED** [review]

**Comment by metaclips** [comment]
Thanks for an amazing PR @PsychoPunkSage

**Pull request merged**
