### PR TITLE
feat(rust): add launch configuration to start services

### PR DESCRIPTION
**Pull request by twittner**
Example:

```json
{
  "startup_services": {
    "vault": {},
    "identity": {
      "address": "identity_service"
    },
    "verifier": {
      "address": "verify"
      "disabled": true
    },
    "authenticator": {
      "enrollers": "/tmp/enrollers.json",
      "project": "p42"
    }
  }
}
```
Opening as a draft PR as it currently abuses the existing `launch_config` parameter and needs better integration with the rest of the system.

### CODE REVIEW

**Comment by twittner** [comment]
CC: @polvorin, @hairyhum, @spacekookie

**Comment by hairyhum** [comment]
> "disabled": true

What does that mean? Why is it in the config if it's disabled?

Also can you please do two configs, one for the sidecar and one for the CA node?

**Comment by twittner** [comment]
> > "disabled": true
> 
> What does that mean? Why is it in the config if it's disabled?

It means that the service is not started and allows for some flexibility. Since JSON does not support comments and it may sometimes be useful to temporarily disable the configuration for a service without having to delete the part from the file, "disabled" can be set to true. The setting is entirely optional.

> Also can you please do two configs, one for the sidecar and one for the CA node?

What do you mean? As implemented one provides a config file with the services to start. The configuration can be different per node.

**Comment by hairyhum** [comment]
> What do you mean? As implemented one provides a config file with the services to start. The configuration can be different per node.

Can you give examples of a node, which requires secure channel to connect to and a node which doesn't? Or it's not controlled by this configuration?

**Comment by mrinalwadhwa** [comment]
@twittner this looks great! I didn't get a chance to try it today but I will tomorrow. Nice!!

**Comment by twittner** [comment]
> Can you give examples of a node, which requires secure channel to connect to and a node which doesn't? Or it's not controlled by this configuration?

It was not. I now added a config section with the same parameters as the command-line interface to start a secure-channel listener, except that it is always started at the local node.

Example 1 (using defaults): 

```
"secure_channel_listener": {}
```

Example 2:

```
"secure_channel_listener": {
  "address": "api",
  "authenticated_identifiers": ["P18face426da251fbee0c0d3a564547c2c5b38c9b1359574eb4aa7e4dd526c00a"]
}
```

**Review by hairyhum — DISMISSED** [review]

**Review by mrinalwadhwa — APPROVED** [review]

**Pull request merged**
