### PR TITLE
feat(rust): support hostname and/or port on `tcp-outlet create` `--to` argument

### LINKED ISSUE #5563: `ockam tcp-outlet create` should support `HOSTNAME:PORT` format
Currently, `ockam tcp-outlet create` command located [here](https://github.com/build-trust/ockam/blob/c0ebe05dd644c271ba394b61d8b58edf8e0a31ee/implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs) only supports `--to` argument in the form of `SocketAddr` (`IP:PORT`). However, supporting the `HOSTNAME:PORT` format is sometimes required (e.g., in containerized environments).  Therefore, `ockam tcp-outlet create` should support `HOSTNAME:PORT` arguments as well.

As an example, `ockam tcp-connection create` command [here](https://github.com/build-trust/ockam/blob/c0ebe05dd644c271ba394b61d8b58edf8e0a31ee/implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs) supports such format.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by alcolmenar**
## Current behavior

Some inputs accept ip addresses and ports but should be able to support hostname and ports. This PR enables hostname and ports for the tcp outlet command. Note: some command access inputs that don't support hostnames and ports, i.e. when specifying a bind address and port.

## Proposed changes

- Change tcp outlet to parameter to be String type
- Update usage of those parameters to enable String type
- Created the HostPort struct that uses the `Host` struct within the url crate
- Created a host_parser util function that validates input for port, ip:port, and hostname:port generating a HostPort struct
- Implemented some conversions to reuse the `host_parser` function with the `socket_addr_parser`

Fixes #5563 

## Checks

Tests pass

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Review by adrianbenavides — DISMISSED** [review]
Looks awesome, thanks @alcolmenar for another great PR! Will get merged soon 🚀

**Comment by adrianbenavides** [comment]
@alcolmenar looks like there is a clippy warning that we must fix to pass the CI checks. We can merge the PR after that is fixed!

**Comment by alcolmenar** [comment]
Looks like there's an error that popped up during these bats tests also. I'm working through it atm

**Review by adrianbenavides — DISMISSED** [review]
All green now! Thanks again @alcolmenar for working on this 💪

**Comment by adrianbenavides** [comment]
@alcolmenar There was a minor conflict with develop that wasn't properly notified until I hit the merge button. I've fixed for you already 👍

**Review by adrianbenavides — APPROVED** [review]

**Review by SanjoDeundiak — APPROVED** [review]

**Pull request merged**
