### PR TITLE
feat(elixir): update the `ockam.address` protocol to be more descriptive

### PR DESCRIPTION
**Pull request by Maartz**
### Proposed Changes

I've updated the code to use `Ockam.RoutableAddress` instead of previous `Ockam.Address`
Related to issue #1222

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
Awesome, quick tip: the commit message linter expect commit message subject to be all lower case.

**Comment by Maartz** [comment]
> Awesome, quick tip: the commit message linter expect commit message subject to be all lower case.

oops didn't check for that...

**Comment by mrinalwadhwa** [comment]
@Maartz thank you for sending the PR ❤️ 🎉 

I reviewed the changed and they look good.

Before we merge, could you do a few small things:
1. fix this [Credo error](https://github.com/ockam-network/ockam/pull/1224/checks?check_run_id=2317729768#step:4:579)
2. make the commit message subject lower case and [sign the commit.](https://docs.github.com/en/github/authenticating-to-github/signing-commits)
3. read and accept our CLA.

Read the CLA at
https://www.ockam.io/learn/how-to-guides/contributing/cla/

To accept the CLA please send a different PR to our contributors repo indicating that you accept the CLA by adding your Git/Github details in a row at the end of the CONTRIBUTORS.csv file:
https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv

Looking forward to merging your first contribution!!

**Comment by Maartz** [comment]
Hi @mrinalwadhwa !
Thanks for you message.
Can you handle this commitlint issue on your side ?
I've update the commit message on my side but it seems it's still KO.

**Comment by mrinalwadhwa** [comment]
Hey @Maartz ... yes, after you sign the CLA commit in https://github.com/ockam-network/contributors/pull/10
I can easily fix the commit here and merge.

**Comment by mrinalwadhwa** [comment]
@Maartz since this has been open for a long time. It would hard to apply this change now.
Sorry that you weren't able to get the CLA pr in to get this change merged.
If you want to work on another issue please let me know and I would be happy point you to something you may find interesting.

**Pull request closed without merging**
