### PR TITLE
feat(rust): add clean up option for command node delete

### PR DESCRIPTION
**Pull request by leonzchang**
add an option `--force` for command `ockam node delete `  to clean up config directory and state directory. (#3131, #3132)

### CODE REVIEW

**Review by mrinalwadhwa — APPROVED** [review]
That looks great. Thank you!

**Comment by leonzchang** [comment]
@mrinalwadhwa  Thanks. If there is any issue in other crates, I would love to dive into it. 🙂

**Comment by mrinalwadhwa** [comment]
@leonzchang Thank you for another awesome contribution :clap: :clap:

**Comment by mrinalwadhwa** [comment]
@leonzchang how about this one? https://github.com/build-trust/ockam/issues/3076 or are you looking for something outside the ockam_command crate?

**Comment by mrinalwadhwa** [comment]
This one will require learning about and digging into the `ockam_api` crate https://github.com/build-trust/ockam/issues/3056

**Comment by leonzchang** [comment]
@mrinalwadhwa cool, I will dive into #3056, thank you.  😁

**Comment by lameferret** [comment]
Hey @leonzchang I was already working on it, and I should have commented rather than using an emoji.

**Comment by mrinalwadhwa** [comment]
@anuvratsingh 👋 so I'm clear, which issue are you referring to?

**Comment by lameferret** [comment]
@mrinalwadhwa Sorry I should have been specific its Issue #3076, and read properly as it looks like leonz is working on #3056.

**Comment by mrinalwadhwa** [comment]
Perfect, looking forward to pull requests from both you 👍 
Let me know in case either of you has any questions.

**Pull request merged**
