### PR TITLE
Rename  elixir_cache composite action to cache_elixir

### LINKED ISSUE #6520: CI - rename the elixir_cache composite action to cache_elixir
Rename the [elixir_cache composite action](https://github.com/build-trust/ockam/tree/develop/.github/actions/elixir_cache) to `cache_elixir`

### PR DESCRIPTION
**Pull request by Ritish134**
Renamed the elixir_cache composite action to cache_elixir closes #6520

## Proposed changes
Renamed the folder elixir_cache to cache_elixir.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@Ritish134 thank you, could also rename all the place the action is used in this folder
https://github.com/build-trust/ockam/tree/develop/.github/workflows

**Comment by mrinalwadhwa** [comment]
@Ritish134 Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by Ritish134** [comment]
Created a pr #6526

**Review by metaclips — APPROVED** [review]
Approved 🚀

**Comment by metaclips** [comment]
I left behind the elixir_cache action for now as we use it in our workflows, I'll create separate issues to allow these workflows point to the renamed action

**Review by etorreborre — APPROVED** [review]

**Pull request merged**
