### PR TITLE
fixes#2286 changes in ockam node

### LINKED ISSUE #2286: Consider replacing channel(1) with oneshot channel in ockam_node

### PR DESCRIPTION
**Pull request by Salonikansal2**
Fixes #2286
replacing channel(1) with oneshot channel in ockam_node
@SanjoDeundiak

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@Salonikansal2 while we still have to review this change. I'm adding the `HACKTOBERFEST-ACCEPTED` label so the contribution is counted by hacktoberfest bots before the end of October. Thank you for taking time to contribute 🎉

**Comment by Salonikansal2** [comment]
Thanks for your efforts @mrinalwadhwa

**Comment by Salonikansal2** [comment]
gentle reminder to review changes 
@adrianbenavides 
@SanjoDeundiak

**Comment by Salonikansal2** [comment]
Gentle reminder @mrinalwadhwa , @nazmulidris , @adrianbenavides , @SanjoDeundiak . Sorry for such hurry in behavior but actually I participated in hacksquad competition due to which I need them merged as soon as possible

**Comment by Salonikansal2** [comment]
@metaclips

**Comment by mrinalwadhwa** [comment]
@Salonikansal2 Please note it is Sunday for everyone who may be able to give feedback on your pull requests. We don't work on Sundays.

We all also have work responsibilities that are usually the most important things on everyone's agenda on a Monday. So its unlikely we will be able to get to your PRs for at least a couple of days. Please be patient.

**Comment by SanjoDeundiak** [comment]
@Salonikansal2 I believe it requires additional work to fix the issue. Oneshot channels have different type and API. Please try to build the project with your change

**Comment by SanjoDeundiak** [comment]
Hey @Salonikansal2 , do you plan to get back to this issue?

**Comment by Salonikansal2** [comment]
I don't think I am able to solve this. So, NO
@SanjoDeundiak

**Pull request closed without merging**
