### PR TITLE
refactor(elixir): replaces deprecated Logger.warn

### PR DESCRIPTION
**Pull request by paulozulato**
The Logger.warn macro is deprecated in favour of the Logger.warning one.

(https://hexdocs.pm/logger/1.15.6/Logger.html#warn/2)

## Current behavior

When running some Elixir example, the following warning is printed:
```bash
$ elixir 01-worker.exs
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  (ockam 0.1.0) lib/ockam/worker.ex:278: Ockam.Worker.schedule_idle_timeout/1

...
```

## Proposed changes

Update Elixir code to replace `Logger.warn` by `Logger.warning`.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@paulozulato Thank you for spending time on this and sending this pull request. While we review please:

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by paulozulato** [comment]
Hi, @mrinalwadhwa, how are you?

I had already accepted the Ockam Contributor License Agreement before (https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv#L261). Should I do anything else on that?

**Comment by mrinalwadhwa** [comment]
Oh that's great thank you. Sorry I missed that. I'm doing well 😀

**Comment by mrinalwadhwa** [comment]
No need to do anything else, we'll review the PR shortly

**Comment by paulozulato** [comment]
> I'm doing well 😀

Good to hear! :smile:


> No need to do anything else, we'll review the PR shortly

OK. Thank you very much :blush:

**Review by polvorin — APPROVED** [review]

**Comment by polvorin** [comment]
thanks for your contribution @paulozulato ! 👍 ,  accepted and going to be merged soon.

**Pull request merged**
