### PR TITLE
Shellcheck fixes

### PR DESCRIPTION
**Pull request by spazm**
## Current Behavior

Partial fix for https://github.com/build-trust/ockam/issues/3754 -- shellcheck workflow errors need fixing.
example: https://github.com/build-trust/ockam/actions/runs/3334646032/jobs/5517818354

## Proposed Changes

Applies automated changes and manual application of simple changes.
fixes two actual bugs 

Does not fix all the errors.  I skipped the ones that required more context than I have for this project.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.
( https://github.com/build-trust/ockam-contributors/pull/150 )

### CODE REVIEW

**Comment by spazm** [comment]
I was just passing through and made some fixes.  I hope they work out for you.  Feel free to modify or edit this PR as you see fit.

I've signed my commits here and in ockam-contributor with the publickey associated with my github account.

**Comment by adrianbenavides** [comment]
@metaclips @mrinalwadhwa should we merge this?

**Comment by metaclips** [comment]
Please merge @adrianbenavides. Thanks.

**Comment by adrianbenavides** [comment]
@mergiyfio rebase

**Comment by adrianbenavides** [comment]
@mergifyio rebase

**Review by adrianbenavides — DISMISSED** [review]
@spazm Sorry for the delay, we'll merge your PR shortly! Thanks for an awesome first contribution :muscle:

**Review by adrianbenavides — APPROVED** [review]

**Pull request merged**
