### PR TITLE
docs: fix typo on Pull Request template

### PR DESCRIPTION
**Pull request by paulozulato**
## Current behavior

The Pull Request template contains a typo:
```
<!--
To help us review and merge this pull request quickly, please confirm the following
by replaceing the [ ] in front of each bullet point below with [x]
   ----------
-->
```

## Proposed changes

Fix the typo.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Review by metaclips — DISMISSED** [review]
Way to go @paulozulato. Thanks

**Comment by paulozulato** [comment]
@metaclips, the merge failed, so I rebased the PR.

**Comment by paulozulato** [comment]
Sorry. I did it on GitHub UI and it was not verified. I've just fixed that.

**Review by metaclips — APPROVED** [review]

**Comment by metaclips** [comment]
> Sorry. I did it on GitHub UI and it was not verified. I've just fixed that.

Thanks @paulozulato the PR didn't follow our commit message naming conventontion, https://github.com/build-trust/ockam/actions/runs/6398911535/job/17370099728, I updated the commit message.

**Review by polvorin — APPROVED** [review]

**Pull request merged**
