### PR TITLE
Update scorecards.yml

### PR DESCRIPTION
**Pull request by VectorStrike**
## Proposed Changes

Fixes [https://github.com/build-trust/ockam/issues/3452](url) by complying with https://github.com/ossf/scorecard-action#breaking-changes-in-v2

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X ] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X ] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@VectorStrike Thank you for fixing this!

If you do one quick thing, we're ready to merge it:

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

**Comment by mrinalwadhwa** [comment]
@VectorStrike sorry about accidentally closing the PR. I'm preparing the merge in a new PR here using you commit. https://github.com/build-trust/ockam/pull/3459.

**Comment by mrinalwadhwa** [comment]
#3459 is ready to merge, as soon as you accept the CLA! 

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

Looking forward to merging your first contribution 🥳

**Comment by mrinalwadhwa** [comment]
> sorry about accidentally closing the PR.

Github automatically closed PRs (with no way to reverse) since I accidentally pushed the current develop branch to the PR branch, while amending the commit message.

**Comment by VectorStrike** [comment]
Pull request made.

**Comment by mrinalwadhwa** [comment]
@VectorStrike Thank you and congratulations on your first contribution 🎉 🎊 
Merged in https://github.com/build-trust/ockam/pull/3459

**Pull request closed without merging**
