### PR TITLE
refactor(rust): encapsulate string parsing behavior in the struct

### PR DESCRIPTION
**Pull request by leonzchang**
[encapsulate string parsing behavior in a struct so that we can reuse it](https://github.com/build-trust/ockam/issues/3068#issuecomment-1206206957)

### CODE REVIEW

**Review by adrianbenavides — DISMISSED** [review]
Awesome, thanks @leonzchang !

**Comment by leonzchang** [comment]
force push for signed commit.

**Comment by leonzchang** [comment]
[mrinalwadhwa](https://github.com/mrinalwadhwa) should I close this PR since [pro465](https://github.com/pro465) sovled in #3124 ?

**Comment by mrinalwadhwa** [comment]
@leonzchang yes I think since the two changes conflict with each other. Makes most sense to close this one. Sorry about that!

**Pull request closed without merging**
