### PR TITLE
test(cmd_authenticated): Add property-based testing for argument parsing

### PR DESCRIPTION
**Pull request by younes-io**
- Implemented property-based tests using proptest for 'authenticated get' and 'list' commands

- Tests generate a range of IP addresses, ports, and IDs to verify argument parsing robustness

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [X] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by younes-io** [comment]
Can someone help me fix the commit msg ?

**Review by SanjoDeundiak — CHANGES_REQUESTED** [review]
Could you please take a look at why CI fails?

**Comment by SanjoDeundiak** [comment]
@younes-io sure, do you need guidance on how to change a commit message, or what a commit message should be to meet our rules?

**Comment by younes-io** [comment]
@SanjoDeundiak, I'd appreciate your help on how to change the commit. Should I do a `git rebase`?

**Comment by SanjoDeundiak** [comment]
@younes-io yes, I usually do `git rebase` or use the UI (Sublime Merge). However, if only the last commit message should be changed, you can do `git commit --amend`. After you've changed the commit message, you'll need to `git push --force-with-lease`. More detailed explanation can be found [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message). Let me know if you need further help!

**Comment by younes-io** [comment]
@SanjoDeundiak I tried to, but since the commit isn't the last, I don't have the Amend option...

**Comment by SanjoDeundiak** [comment]
@younes-io you would also need to remove the merge commit. You can do it with `git rebase develop`

**Comment by younes-io** [comment]
Closing because this keeps failing and I get a million emails a day... even with the commits.. it's not solved..

**Pull request closed without merging**
