### PR TITLE
docs(rust): improve documentation for `ockam relay` command

### LINKED ISSUE #6292: Improve `ockam relay --help` text to be in active voice
# Current behavior

When a user runs `ockam relay --help`, they get the following output. The first part of this output is in passive voice.

Image

# Desired behavior

Instead of passive voice, change that first paragraph of help text to be active voice using the following copy:

```
Communication topologies often encounter situations where the machine providing a service cannot or will not open a listening port or expose a bridge node to other networks. This is a common security best practice in enterprise environments, home networks, OT networks, and VPCs across clouds. Application developers may not have control over these choices from the infrastructure/operations layer. In such cases, relays are useful.
```

# Implementation details

In order to make this change, please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/static/long_about.txt#L1).

---
<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. In the PR description, include the issue that's being solved 
1. Run `cargo fmt`. You can configure the editor to run it automatically every time a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `git merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

### PR DESCRIPTION
**Pull request by Chandram-Dutta**
## Proposed changes
fixes: #6292

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by adrianbenavides** [comment]
Thanks @Chandram-Dutta for submitting the PR 🙏  It looks good, but we need you to accept our CLA before we can merge your PR. These are the instructions:

> I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

**Comment by Chandram-Dutta** [comment]
done @adrianbenavides

**Comment by adrianbenavides** [comment]
> done @adrianbenavides

Hey @Chandram-Dutta! You need to create a separate PR for the CLA so that the CI check can work as expected.

**Comment by nazmulidris** [comment]
@adrianbenavides 
- The long help text changes in this PR look good. 
- I have closed the other [PR](https://github.com/build-trust/ockam/pull/6312) that was also open against the [same issue](https://github.com/build-trust/ockam/issues/6292) (as this PR).

**Review by adrianbenavides — APPROVED** [review]
LGTM! Thank you so much @Chandram-Dutta for your contribution 🙏

**Review by metaclips — APPROVED** [review]

**Pull request merged**
