### PR TITLE
ci(yaml): references to new builder image

### PR DESCRIPTION
**Pull request by Dark-Knight11**
changed the old hash with new hash of latest ockam-builder image 

ref: #3702

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Review by metaclips — APPROVED** [review]
Thanks for an amazing PR @Dark-Knight11

**Comment by mrinalwadhwa** [comment]
@Dark-Knight11 sorry this close is accidental. Github has a bug where they close the PR if you push to the fork PR branch and it the same name as the PR target branch - `develop`

I thought they had fixed this https://github.blog/changelog/2022-10-12-reverted-recent-change-that-caused-some-pull-requests-to-be-incorrectly-marked-as-merged/

I'm trying a fix.

**Comment by mrinalwadhwa** [comment]
@Dark-Knight11 need a little help from you:

Your commit is saved in this branch https://github.com/build-trust/ockam/tree/3705

I can just merge it. However if you're participating in hacktoberfest, I want to make sure you get credit for merging a PR. So:

If you're NOT participating in hacktoberfest:
- this is simple I can merge the contribution.

If you're participating in hacktoberfest
- we either need to reopen this PR, which I can't but I thin you might be able to - try it.
- or you will have to create a new PR with your changes from this branch https://github.com/build-trust/ockam/tree/3705

Sorry about the confusion, let me know if you have questions.

**Comment by mrinalwadhwa** [comment]
I realized I can ensure Hacktoberfest credit but adding the accepted label to @Dark-Knight11's [contributors PR.](https://github.com/build-trust/ockam-contributors/pull/138)

Preparing to land @Dark-Knight11's changes in https://github.com/build-trust/ockam/pull/3719

**Comment by Dark-Knight11** [comment]
Thanks a lot ❤

**Pull request closed without merging**
