### PR TITLE
chore(rust): rename `project enroll` to `project ticket`

### LINKED ISSUE #4939: Rename `ockam project enroll` clap command to `ockam project ticket`
### Current behavior

```sh
ockam project enroll >  user.ticket
```

### Desired behavior

```sh
ockam project ticket >  user.ticket
```

Update the `enroll` clap command found [here](https://github.com/build-trust/ockam/blob/a42a4c06d19409c18a3303d1df56f8d105d78dff/implementations/rust/ockam/ockam_command/src/project/enroll.rs)

Update examples found [within here](https://github.com/build-trust/ockam/tree/develop/examples/rust/get_started/examples)

Update bats testings found [within here](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/tests/bats)

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by fsmiamoto**
## Proposed changes

Rename subcommand `project enroll` to `project ticket`.

Closes https://github.com/build-trust/ockam/issues/4939 

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@fsmiamoto Thank you for spending time on this. While we review, please:

- [x] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

**Comment by fsmiamoto** [comment]
Oops, looks like I was too sleepy and didn't read the checklist item properly :laughing: 
Here's the PR for adding me as a contributor: https://github.com/build-trust/ockam-contributors/pull/215
Thanks!

**Comment by adrianbenavides** [comment]
> Oops, looks like I was too sleepy and didn't read the checklist item properly 😆 Here's the PR for adding me as a contributor: [build-trust/ockam-contributors#215](https://github.com/build-trust/ockam-contributors/pull/215) Thanks!

Great! I'll review it shortly 👍

**Review by adrianbenavides — COMMENTED** [review]
It all looks good! There is a small formatting issue that you can fix running `cargo fmt`. We can merge it after that

**Comment by fsmiamoto** [comment]
Applied `cargo fmt` and rebased changes

**Review by adrianbenavides — APPROVED** [review]
LGTM, thanks @fsmiamoto for your first contribution to Ockam! 🥳

**Comment by mrinalwadhwa** [comment]
@fsmiamoto thank you and congratulations on an awesome first contribution 🎉🥳

**Pull request merged**
