### PR TITLE
chore(rust): improve cowstr display

### PR DESCRIPTION
**Pull request by akki1306**
## Current Behavior

as described in #3531 

## Proposed Changes

Use Display instead of Debug and N/A in absence of a value

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by akki1306** [comment]
previous pull request failed with commit message check. Creating a new one.

**Review by twittner — APPROVED** [review]
Looks good to me. Thank you!

**Comment by mrinalwadhwa** [comment]
@akki1306 thank you for an awesome first contribution 🎉 🎊

**Comment by akki1306** [comment]
Thanks, @mrinalwadhwa :) looking forward to more contributions.

**Pull request merged**
