### PR TITLE
[Fix]: Run lint_docs_ockam_io_rust_examples job test only on the merge queue

### LINKED ISSUE #6523: Run the `lint_docs_ockam_io_rust_examples` job test only on the merge queue
We have a job called the [lint_docs_ockam_io_rust_examples](https://github.com/build-trust/ockam/blob/b4ece1b9a60e90bab6853cacc54ca95b042d7bf7/.github/workflows/rust.yml#L374) that checks our Rust [example](https://github.com/build-trust/ockam/tree/develop/examples/rust) against our docs.ockam.io website examples to see if the code diverges and fails if it doesn't, when a PR makes changes to the examples code other PR's that have not rebased with the changes fails the lint check, we should only run the `lint_docs_ockam_io_rust_examples` job only when it's started on the merge queue `if: github.event_name == 'merge_group'` . Example of a job that only runs on the merge queue https://github.com/build-trust/ockam/blob/b4ece1b9a60e90bab6853cacc54ca95b042d7bf7/.github/workflows/rust.yml#L324

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

### PR DESCRIPTION
**Pull request by A-5ingh**
Fixes #6523 

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@A-5ingh Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by A-5ingh** [comment]
Accepted CLA in #6530

**Comment by A-5ingh** [comment]
> @A-5ingh Thank you for spending time on this, before we can merge please
> 
> * [ ]  Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.
> 
> The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

Is there anything else required here @mrinalwadhwa ?

**Comment by mrinalwadhwa** [comment]
@A-5ingh nothing yet, we'll review it when the new week starts.

**Review by metaclips — DISMISSED** [review]
Thanks for an amazing PR @A-5ingh

**Review by metaclips — APPROVED** [review]

**Review by etorreborre — APPROVED** [review]

**Pull request merged**
