### PR TITLE
chore: upgrade cortex-m-rt

### PR DESCRIPTION
**Pull request by etorreborre**
in order to fix this advisory issue: https://github.com/build-trust/ockam-artifacts/issues/110.

### CODE REVIEW

**Comment by davide-baldo** [comment]
I think it's OK to update the library, but we are *not* affected since the version is <= 0.7.0

**Comment by etorreborre** [comment]
Actually it is in our dependency tree as `0.7.2` via other dependencies

**Comment by davide-baldo** [comment]
~~Please update the commit message to reflect that~~

**Review by davide-baldo — APPROVED** [review]

**Comment by etorreborre** [comment]
Thanks @davide-baldo!

**Pull request merged**
