### PR TITLE
feat(rust): added service format parsing

### PR DESCRIPTION
**Pull request by michealkeines**
# Added

added custom parser for clap argument

# Output:

updated outputs with different formats

### /service

image

### normal hash or value

image

### local#value formatt

image

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@michealkeines Thank you for spending time on this. The changes here work great but I think changing this in core right now might break some things in unexpected ways. I would be better to keep the conversion in either the ockam_command or the ockam_api crates even if that causes some extra repetition. Would you mind exploring that possibility?

**Review by mrinalwadhwa — CHANGES_REQUESTED** [review]
https://github.com/build-trust/ockam/pull/3407#issuecomment-1236043650

**Comment by michealkeines** [comment]
@mrinalwadhwa I have added the parser within the delete command itself, please review it, thank you!

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
@michealkeines thank you for another awesome contribution 🎉

**Pull request merged**
