### PR TITLE
Changed Ockam Crate Desc.

### PR DESCRIPTION
**Pull request by manavsiddharthgupta**
## Current Behaviour
Ockam crate Description is not yet changed

## Proposed Changes
Change to: End-to-end encryption and mutual authentication for distributed applications.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

### CODE REVIEW

**Comment by thomcc** [comment]
Hey, thanks for the contribution, unfortunately I'm not sure we want this change. The old description has more information, and this change will make [our docs](https://docs.rs/ockam/latest/ockam/) somewhat less informative.

@mrinalwadhwa thoughts?

**Comment by mrinalwadhwa** [comment]
@thomcc I think this change is okay.

@manavsiddharthgupta 
Thank you for sending the PR ❤️

Before we can merge, please accept the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

Looking forward to merging your first contribution!!

**Review by mrinalwadhwa — APPROVED** [review]
Accepting the CLA will make the commits check pass.
https://github.com/build-trust/ockam/runs/6140843258?check_suite_focus=true

**Comment by mrinalwadhwa** [comment]
@manavsiddharthgupta thank you, we have a [convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages) around our commit messages.
I edited the commit message, rebased and queued the PR for merge in https://github.com/build-trust/ockam/pull/2757

Congratulations on an awesome first contribution 🎉

**Pull request closed without merging**
