### PR TITLE
Replaced the rust doc command 

### LINKED ISSUE #6644: Improve `ockam tcp-inlet list --help` text (`clap` command)
# Current behavior

When a user runs `ockam tcp-inlet list --help` they are shown the following help text.

Image

# Desired behavior

Instead, they should be presented with the following help text for the command `List TCP Inlets on the default node`. 

# Implementation details

1) Replace the Rust doc comment for the `ListCommand` struct with the following: `List TCP Inlets on the default node` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/list.rs#L21)

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

### PR DESCRIPTION
**Pull request by priyanshu9899**
## Current behavior

Rust doc comment for the ListCommand struct with the following: List TCP Inlets 

## Proposed changes
 
Fixes #6644

## Checks

- [ x ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ x ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ x ] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [ x ] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ x ] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by adrianbenavides** [comment]
Hi @priyanshu9899, thanks for submitting this PR! The changes look good, but we need you first to create a separate PR accepting our CLA as described here:

> I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

**Comment by mrinalwadhwa** [comment]
@priyanshu9899 to land this PR, our process requires an accepted Contributor License Agreement:

- [x] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by priyanshu9899** [comment]
done @mrinalwadhwa @adrianbenavides

**Comment by mrinalwadhwa** [comment]
@priyanshu9899  while we still have to review this change. I'm adding the HACKTOBERFEST-ACCEPTED label so the contribution is counted by hacktoberfest bots before the end of October. Thank you for taking time to contribute 🎉

**Review by adrianbenavides — APPROVED** [review]
Ready to merge, thanks again @priyanshu9899 🙏

**Review by etorreborre — APPROVED** [review]

**Pull request merged**
