### PR TITLE
add multi arch functionality to ockam-builder

### PR DESCRIPTION
**Pull request by metaclips**
- Adds Multi arch feature to Ockam-builder
- Add git tag signing support

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@metaclips we should add back the gosu entrypoint to ockam-builder otherwise file permissions in shared volumes become messy tools/docker/base/entrypoint.sh

This is also why builder should be invoked as follows:
```
docker run --rm -it -e HOST_USER_ID=$(id -u) --volume $(pwd):/work ockam-builder:latest bash
```

The other images don't need this.

**Comment by metaclips** [comment]
> @metaclips we should add back the gosu entrypoint to ockam-builder otherwise file permissions in shared volumes become messy tools/docker/base/entrypoint.sh
> 
> This is also why builder should be invoked as follows:
> 
> ```
> docker run --rm -it -e HOST_USER_ID=$(id -u) --volume $(pwd):/work ockam-builder:latest bash
> ```
> 
> The other images don't need this.

Added gosu

**Comment by mrinalwadhwa** [comment]
I built the ockam/builder image as follows:

```
docker buildx build --load --platform linux/arm64 --tag ghcr.io/build-trust/ockam/builder  .
```

for my M1 mac.

Running Erlang in it segfaults:

Screen Shot 2022-06-23 at 11 42 21 PM

We may have to build erlang from source instead of using the prebaked binaries from erlang-solutions.

`kerl` makes it easy to build and install from source
https://github.com/kerl/kerl

**Comment by metaclips** [comment]
> I built the ockam/builder image as follows:
> 
> ```
> docker buildx build --load --platform linux/arm64 --tag ghcr.io/build-trust/ockam/builder  .
> ```
> 
> for my M1 mac.
> 
> Running Erlang in it segfaults:
> 
> Screen Shot 2022-06-23 at 11 42 21 PM
> 
> We may have to build erlang from source instead of using the prebaked binaries from erlang-solutions.
> 
> `kerl` makes it easy to build and install from source https://github.com/kerl/kerl

I am able to successfully run ockam-builder on my macos 
Screenshot 2022-06-24 at 8 58 26 AM
Screenshot 2022-06-24 at 9 00 02 AM
What does `docker manifest inspect ghcr.io/build-trust/ockam-builder:latest` output

**Comment by mrinalwadhwa** [comment]
Something wasn't right about the image I was trying last night ... so I pulled the latest [here](https://github.com/build-trust/ockam-artifacts/pkgs/container/ockam-builder/26392604?tag=latest)

Screen Shot 2022-06-24 at 8 16 40 AM

Things look a lot better
Screen Shot 2022-06-24 at 8 18 07 AM

gradle builds still don't succeed .. I'll try that out and report back,

**Comment by metaclips** [comment]
> gradle builds still don't succeed .. I'll try that out and report back,

Seems we are not building NIFs for linux aarch64, I'll add that release to this PR

**Review by mrinalwadhwa — DISMISSED** [review]

**Review by mrinalwadhwa — APPROVED** [review]

**Pull request merged**
