### PR TITLE
feat(rust): add inlet/outlet delete/list

### PR DESCRIPTION
**Pull request by lameferret**
WIP #3167 

How do I debug, even with `RUST_LOG=debug/trace cargo run -- tcp-inlet ...` I don't get any output.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@anuvratsingh try `ockam node create n1 --foreground -vvv`.

**Comment by lameferret** [comment]
Sorry, I tried `ockam tcp-inlet create --at /node/n1 --from 127.0.0.1:6000 --to /node/n2/node/n3/service/outlet -vvv` it shows a lot of details but [`tcp/inlet/create.rs`: info!("Handling request to create inlet portal");](https://github.com/build-trust/ockam/blob/8f4d0391eae726a19d6e204189111474d447830b/implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs#L66) doesn't show up. Am I missing something?
 Thanks

**Comment by mrinalwadhwa** [comment]
since create inlet is delegated to node n1.

node n1 would have to be running as `ockam node create n1 --foreground -vvv` in a separate window .. this is where that info will print.

another way is to look at the node logs being written to your node state directory.

**Comment by lameferret** [comment]
@mrinalwadhwa sorry for being insanely late, was a bit busy.

Currently, I don't understand why `TRY 1` doesn't work. Just like when creating a `TCP Inlet`, I'm stopping it then removing it from the `BTreeMap`. `alias` I'm providing is correct as `btreemap.get(alias)` works, so why doesn't `remove` works?

<details><summary> TRY 1 </summary>

```2022-09-08T21:12:31.706432Z  INFO ockam_api::nodes::service::portals: Handling request to d
elete tcp inlet: 4d27644c9361d28413a29110a1d016ab
2022-09-08T21:12:31.706471Z  INFO ockam_api::nodes::service::portals: Stop TCP Inlet inlet.
bind_addr=127.0.0.1:6000
2022-09-08T21:12:31.706526Z DEBUG ockam_node::context: Shutting down processor 0#127.0.0.1:
6000
2022-09-08T21:12:31.706616Z TRACE ockam_node::router::stop_processor: Stopping processor '0
#127.0.0.1:6000'
2022-09-08T21:12:31.706778Z ERROR ockam_api::nodes::service: Failed to handle request err=O
ckam Error [[Origin::Node; Kind::NotFound]] at implementations/rust/ockam/ockam_node/src/er
ror.rs:32:9
--- Details ---
- Caused by: operation failed for address 0#127.0.0.1:6000
- possible root cause `ockam_node::error::NodeError`: operation failed for address 0#127.0.
0.1:6000
  debug output:
    Address(0#127.0.0.1:6000)
--- Captured Spantrace ---

--------------------------

2022-09-08T21:12:31.706854Z TRACE ockam_api::nodes::service: ** sending response
2022-09-08T21:12:31.706957Z TRACE ockam_node::router::utils: Resolving worker address '0#c6
d56aa7e081a1e1ccfe3285d763b08f'... OK
2022-09-08T21:12:31.707164Z TRACE ockam_node::context: 0#c6d56aa7e081a1e1ccfe3285d763b08f:
received new message!
2022-09-08T21:12:31.707226Z TRACE ockam_transport_tcp::router::tcp_router: TCP route reques
t: Ok(1#127.0.0.1:42194)
2022-09-08T21:12:31.707330Z TRACE ockam_node::router::utils: Resolving worker address '0#e2
a997c308b7ba0bbc4830604a10ee22'... OK
2022-09-08T21:12:31.707505Z TRACE ockam_node::context: 0#e2a997c308b7ba0bbc4830604a10ee22:
received new message!
2022-09-08T21:12:31.707771Z DEBUG ockam_node::router::start_worker: Starting new worker '0#
2e0cb65c79e4f568dbeba73aeea0eb86'
2022-09-08T21:12:31.707773Z TRACE ockam_node::context: De-allocated detached context 0#4b32
6213a285d6f5c6e7491f89b1daa6
2022-09-08T21:12:31.707866Z DEBUG ockam_node::async_drop: Received AsyncDrop request for ad
dress: 0#4b326213a285d6f5c6e7491f89b1daa6
2022-09-08T21:12:31.707956Z TRACE ockam_node::router::stop_worker: Stopping worker '0#4b326
213a285d6f5c6e7491f89b1daa6'
2022-09-08T21:12:31.708505Z  INFO ockam_transport_tcp::workers::receiver: Connection to pee
r '1#127.0.0.1:42194' was closed; dropping stream
2022-09-08T21:12:31.708641Z TRACE ockam_node::router::utils: Resolving worker address '0#30
ca07120eefd5877e49fd800f0364f5'... OK
2022-09-08T21:12:31.708867Z TRACE ockam_node::relay::processor_relay: Sending shutdown ACK
2022-09-08T21:12:31.708953Z TRACE ockam_node::router: Received shutdown ACK for address 0#9
1bc6efa6f857f7e8bbb437cacd1e4c6
2022-09-08T21:12:31.708966Z TRACE ockam_node::context: 0#e2a997c308b7ba0bbc4830604a10ee22:
received new message!
2022-09-08T21:12:31.709063Z  WARN ockam_transport_tcp::workers::sender: Stopping sender due
 to closed connection 127.0.0.1:42194
2022-09-08T21:12:31.709224Z TRACE ockam_node::context: De-allocated detached context 0#2e0c
b65c79e4f568dbeba73aeea0eb86
2022-09-08T21:12:31.709232Z DEBUG ockam_node::router::start_worker: Starting new worker '0#
a6cd74ba4293dbf54c71a206fcf05a11'
2022-09-08T21:12:31.709304Z DEBUG ockam_node::async_drop: Received AsyncDrop request for ad
dress: 0#2e0cb65c79e4f568dbeba73aeea0eb86
2022-09-08T21:12:31.709382Z TRACE ockam_node::router::stop_worker: Stopping worker '0#2e0cb
65c79e4f568dbeba73aeea0eb86'
2022-09-08T21:12:31.709492Z TRACE ockam_node::router::utils: Resolving worker address '0#03
b733cfc9fc35881f70d84ebbed46fd'... OK
2022-09-08T21:12:31.709667Z TRACE ockam_node::context: 0#c6d56aa7e081a1e1ccfe3285d763b08f:
received new message!
2022-09-08T21:12:31.709747Z TRACE ockam_transport_tcp::router::tcp_router: TCP unregistrati
on request: 0#e2a997c308b7ba0bbc4830604a10ee22
2022-09-08T21:12:31.709878Z TRACE ockam_node::router::utils: Resolving worker address '0#a6
cd74ba4293dbf54c71a206fcf05a11'... OK
2022-09-08T21:12:31.710050Z TRACE ockam_node::context: 0#a6cd74ba4293dbf54c71a206fcf05a11:
received new message!
2022-09-08T21:12:31.710138Z TRACE ockam_node::context: De-allocated detached context 0#a6cd
74ba4293dbf54c71a206fcf05a11
2022-09-08T21:12:31.710195Z DEBUG ockam_node::context: Shutting down worker 0#e2a997c308b7b
a0bbc4830604a10ee22
2022-09-08T21:12:31.710294Z DEBUG ockam_node::async_drop: Received AsyncDrop request for ad
dress: 0#a6cd74ba4293dbf54c71a206fcf05a11
2022-09-08T21:12:31.710336Z TRACE ockam_node::router::stop_worker: Stopping worker '0#e2a99
7c308b7ba0bbc4830604a10ee22'
2022-09-08T21:12:31.710534Z TRACE ockam_node::router::stop_worker: Stopping worker '0#a6cd7
4ba4293dbf54c71a206fcf05a11'
2022-09-08T21:12:31.710582Z TRACE ockam_node::relay::worker_relay: No more messages for wor
ker 0#e2a997c308b7ba0bbc4830604a10ee22
2022-09-08T21:12:31.710638Z TRACE ockam_node::relay::worker_relay: Sending shutdown ACK
2022-09-08T21:12:31.710724Z TRACE ockam_node::context: De-allocated detached context 0#3d1b
15375d07d960f90c502a47765522
2022-09-08T21:12:31.710748Z TRACE ockam_node::router: Received shutdown ACK for address 0#e
2a997c308b7ba0bbc4830604a10ee22
2022-09-08T21:12:31.710887Z TRACE ockam_node::context: De-allocated detached context 0#087c
0dc93e57ed63ad8a63251e038209
2022-09-08T21:12:31.710981Z DEBUG ockam_node::async_drop: Received AsyncDrop request for ad
dress: 0#087c0dc93e57ed63ad8a63251e038209
2022-09-08T21:12:31.711055Z DEBUG ockam_node::async_drop: Received AsyncDrop request for ad
dress: 0#3d1b15375d07d960f90c502a47765522
2022-09-08T21:12:31.711158Z TRACE ockam_node::router::stop_worker: Stopping worker '0#087c0
dc93e57ed63ad8a63251e038209'
2022-09-08T21:12:31.711304Z TRACE ockam_node::router::stop_worker: Stopping worker '0#3d1b1
5375d07d960f90c502a47765522'
2022-09-08T21:17:27.907482Z TRACE ockam_transport_tcp::workers::receiver: Received message
header for 4 bytes```

</details>

**Comment by adrianbenavides** [comment]
Closing since it looks pretty outdated. I'll leave the original issue open in case you want to give it a second try @anuvratsingh . Thanks!

**Pull request closed without merging**
