### PR TITLE
docs(completion): add Ockam completion documentation

### LINKED ISSUE #5565: Improve documentation of `ockam completion` command to specify how to use it properly
### Current behavior

The documentation of `ockam completion` is vague and doesn't work out of the box for the platforms we support (Linux, MacOS).

### Desired behavior

The documentation should include:
1. The steps to build the completion file
2. Where to store it
3. Explain what's the expected result

Proposed changes for the [`after_long_help.txt` file](https://github.com/build-trust/ockam/blob/c9d3b68b4d4d3dc7d4e51597d4e158d8b2a4ff1e/implementations/rust/ockam/ockam_command/src/completion/static/after_long_help.txt):

----

First off, you need a valid directory to store the completions file based on your OS and shell. One way to do that is to observe the `FPATH` environment variable. Usually, you will find one of the following:

- Bash: `/usr/share/bash-completion/completions`
- ZSH: `/usr/local/share/zsh/site-functions`
- Fish: `~/.config/fish/completions`

Now, make sure the directory exists running `mkdir -p {dir}` and execute the command to generate the completion file. Note that the file name must be exactly as shown below.

```sh
$ ockam completion --shell bash > /usr/share/bash-completion/completions/ockam.bash
$ ockam completion --shell zsh > /usr/local/share/zsh/site-functions/_ockam
$ ockam completion --shell fish > ~/.config/fish/completions/ockam.fish
```

Finally, run `compinit` to rebuild the completion of your shell.

---

This is the expected result

[asciicast](https://asciinema.org/a/C2uwlW1soMpDxW3tPK34Z6Xot)

### PR DESCRIPTION
**Pull request by iakev**
Added detailed documentation outlining the steps to build the Ockam completion file, specify the storage location, and explain the expected results.

## Build the Completion File

- Clarified the need for a valid directory based on the operating system and shell.
- Added details about creating the necessary directory using `mkdir`.
- Provided specific commands for generating the completion file for each supported shell: Bash, Zsh, and Fish.

## Update Completion Cache

- Added information about the potential need to update the shell's completion cache after generating the completion file.

## Expected Results

Outlined the expected outcomes after successfully completing the steps:

- The completion file will be generated according to the shell format.
- The file will contain relevant completion definitions for Ockam commands and options.
- The completion file will be saved in the designated directory for each shell.
- A link to an asciinema video demonstrates the expected behavior.

## Conclusion

Concluded the documentation with a congratulatory note, highlighting the successful integration of the Ockam completion file into the shell environment.

Fixes #5565

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@iakev Thank you for spending time on this, while we review please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

**Review by adrianbenavides — COMMENTED** [review]
Awesome, looks great! 

The content of this file is used to generate both the terminal docs and [markdown docs](https://command.ockam.io/manual/). Because of that, the content structure must be as simple as possible. For example, nested lists usually don't get well formatted.

Here is my proposal to simplify the structure a little bit. I've also replaced the asciinema file by a simple image.

````

The following steps outline how to build the Ockam completion file, where to store it, and what to expect from the process.

#### Build the Completion File

Start by ensuring you have a valid directory available to store the completion files, depending on your operating system and shell:
   
- For Bash: `/usr/share/bash-completion/completions`
- For Zsh: `/usr/local/share/zsh/site-functions`
- For Fish: `~/.config/fish/completions`

If the directory doesn't exist, create it using the following command, replacing `{dir}` with the appropriate path:

```sh
mkdir -p {dir}
```

Generate the completion file by executing the relevant command for your shell. The file name must match the specific name for each shell.

```sh
# Bash
$ ockam completion --shell bash > /usr/share/bash-completion/completions/ockam.bash

# Zsh
$ ockam completion --shell zsh > /usr/local/share/zsh/site-functions/_ockam

# Fish
$ ockam completion --shell fish > ~/.config/fish/completions/ockam.fish
```

#### Update Completion Cache

After generating the completion file, it may be necessary to update your shell's completion cache to activate the changes:

```sh
$ compinit
```

#### Expected Results

Upon successfully completing the steps outlined above:

- The completion file will be generated according to the specified shell format.
- The file will contain relevant completion definitions for Ockam commands and options.
- The completion file will be saved in the designated directory for your shell.

After successful installation, you can expect to see a result similar to the following video:

![image](https://github.com/build-trust/ockam/assets/12375782/5d8f89a4-9ea3-4d93-8932-23d918085e64)

Congratulations! You have successfully created and integrated the Ockam completion file into your shell environment. As you type Ockam commands, you'll enjoy the convenience of auto-suggestions and completion.

````

**Comment by iakev** [comment]
Thanks for the suggestions have pushed them, kindly review.

**Comment by adrianbenavides** [comment]
Nice, don't forget to open a PR to accept the Ockam Contributor License Agreement:

> Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

We'll merge it after that! 👍

**Comment by iakev** [comment]
Made some changes to try to pass the tests as 2 tests were failing.

**Comment by adrianbenavides** [comment]
> Made some changes to try to pass the tests as 2 tests were failing.

Great, the PR is ready to merge, but to land it our process requires that you accept the Ockam Contributor License Agreement as described below:

> Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.
>
> The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

If you have any question regarding this point, please let us know!

**Comment by nazmulidris** [comment]
Since images won't work in terminal output, perhaps the following contents for `after_long_help.txt` will work better 👍🏽 🙏🏽  

````
The following steps outline how to build the Ockam completion file, where to store it, and what to expect from the process.

#### Build the Completion File

Start by ensuring you have a valid directory available to store the completion files, depending on your operating system and shell:
   
- For Bash: `/usr/share/bash-completion/completions`
- For Zsh: `/usr/local/share/zsh/site-functions`
- For Fish: `~/.config/fish/completions`

If the directory doesn't exist, create it using the following command, replacing `{dir}` with the appropriate path:

```sh
mkdir -p {dir}
```

Generate the completion file by executing the relevant command for your shell. The file name must match the specific name for each shell.

```sh
# Bash
$ ockam completion --shell bash > /usr/share/bash-completion/completions/ockam.bash

# Zsh
$ ockam completion --shell zsh > /usr/local/share/zsh/site-functions/_ockam

# Fish
$ ockam completion --shell fish > ~/.config/fish/completions/ockam.fish
```

#### Update Completion Cache

After generating the completion file, it may be necessary to update your shell's completion cache to activate the changes:

```sh
$ compinit
```

#### Expected Results

Upon successfully completing the steps outlined above:

- The completion file will be generated according to the specified shell format.
- The file will contain relevant completion definitions for Ockam commands and options.
- The completion file will be saved in the designated directory for your shell.

Congratulations! You have successfully created and integrated the Ockam completion file into your shell environment. As you type Ockam commands, you'll enjoy the convenience of auto-suggestions and completion.
````

**Review by nazmulidris — CHANGES_REQUESTED** [review]
Images aren't supported in terminal output, so I've suggested some changes to remove the images from the help text.

**Review by nazmulidris — DISMISSED** [review]
Hi @iakev 👋🏽 . Thank you for taking the time to take a look at this.

There are 2 action items that are pending before we can merge this PR. If you have any questions about this, please let us know 👍🏽 .

## 1. Please accept the CLA

Thank you for spending time on this. In order to make contributions to Ockam (now or in the future), please add yourself to the Contributor License Agreement.

- Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

- The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR (and a single commit that will ensure that it is verified). The video below shows this in action.

https://github.com/build-trust/ockam-website/assets/2966499/363b5416-3b08-40fc-94b7-ce5ed3fb5af3

## 2. Please remove the link to the `asciicast` image

Markdown images don't work in terminal output. So we can't have any image tags. For terminal output, the Markdown we can use is limited to what we can show in `stdout`. The `asciicast` link renders in a web browser itself (but not `stdout`).

Please copy and paste the following to the `after_long_help.txt` file:

````
The following steps outline how to build the Ockam completion file, where to store it, and what to expect from the process.

#### Build the Completion File

Start by ensuring you have a valid directory available to store the completion files, depending on your operating system and shell:
   
- For Bash: `/usr/share/bash-completion/completions`
- For Zsh: `/usr/local/share/zsh/site-functions`
- For Fish: `~/.config/fish/completions`

If the directory doesn't exist, create it using the following command, replacing `{dir}` with the appropriate path:

```sh
mkdir -p {dir}
```

Generate the completion file by executing the relevant command for your shell. The file name must match the specific name for each shell.

```sh
# Bash
$ ockam completion --shell bash > /usr/share/bash-completion/completions/ockam.bash

# Zsh
$ ockam completion --shell zsh > /usr/local/share/zsh/site-functions/_ockam

# Fish
$ ockam completion --shell fish > ~/.config/fish/completions/ockam.fish
```

#### Update Completion Cache

After generating the completion file, it may be necessary to update your shell's completion cache to activate the changes:

```sh
$ compinit
```

#### Expected Results

Upon successfully completing the steps outlined above:

- The completion file will be generated according to the specified shell format.
- The file will contain relevant completion definitions for Ockam commands and options.
- The completion file will be saved in the designated directory for your shell.

Congratulations! You have successfully created and integrated the Ockam completion file into your shell environment. As you type Ockam commands, you'll enjoy the convenience of auto-suggestions and completion.
````

**Comment by iakev** [comment]
Hi @nazmulidris,

I thank you for your  invaluable guidance and unwavering patience as I embarked on my maiden voyage into the world of open source contributions. It has been an incredibly enlightening experience, and I genuinely appreciate your support every step of the way.

I am thrilled to inform you that I have wholeheartedly accepted the Ockam Contributor License Agreement, signifying my commitment to the project and its community. Furthermore, I have diligently addressed the necessary modifications in the documentation, ensuring that our codebase remains precise and user-friendly.

I am eager to see my pull request reviewed and merged, and I am confident that, with your continued assistance and the collective effort of this exceptional community, we will make significant strides toward our shared goals.

Thank you once again for your guidance and mentorship. It has been an absolute pleasure working with you, and I look forward to many more collaborative endeavors in the open source world.

If other changes are required let me know.

**Review by adrianbenavides — APPROVED** [review]
Looks good to merge 👍  

Thanks again @iakev and congrats on your first contribution to Ockam! 🚀

**Review by etorreborre — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
@iakev congratulations on an awesome first contribution 🥳

**Comment by iakev** [comment]
Thanks for the opportunity and guidance. Looking forward to more collaborations.

**Comment by nazmulidris** [comment]
> Hi @nazmulidris,
> 
> I thank you for your invaluable guidance and unwavering patience as I embarked on my maiden voyage into the world of open source contributions. It has been an incredibly enlightening experience, and I genuinely appreciate your support every step of the way.
> 
> I am thrilled to inform you that I have wholeheartedly accepted the Ockam Contributor License Agreement, signifying my commitment to the project and its community. Furthermore, I have diligently addressed the necessary modifications in the documentation, ensuring that our codebase remains precise and user-friendly.
> 
> I am eager to see my pull request reviewed and merged, and I am confident that, with your continued assistance and the collective effort of this exceptional community, we will make significant strides toward our shared goals.
> 
> Thank you once again for your guidance and mentorship. It has been an absolute pleasure working with you, and I look forward to many more collaborative endeavors in the open source world.
> 
> If other changes are required let me know.

@iakev Congratulations on your first contribution! 🎉 Thank you so much for your kind words and your patience, persistence, and resilience through this entire journey! Looking forward to lots more awesome collaborations with you and contributions from you 👍🏽 .

**Pull request merged**
