### PR TITLE
Update to CONTRIBUTORS.csv

### PR DESCRIPTION
**Pull request by Nathy-bajo**
## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by etorreborre** [comment]
Hi @Nathy-bajo can you please reword your commit message to be like [this one](https://github.com/build-trust/ockam/commit/5721b4777a86d009a48e4c39d1f0274f69366a80) for example.

**Comment by Nathy-bajo** [comment]
@etorreborre Done.

**Comment by etorreborre** [comment]
Hi @Nathy-bajo, the format for commit messages is very specific. 
It should be `cla: accepted by nathy-bajo` with a `cla:` prefix and no uppercase letters.

**Comment by Nathy-bajo** [comment]
> Hi @Nathy-bajo, the format for commit messages is very specific. It should be `cla: accepted by nathy-bajo` with a `cla:` prefix and no uppercase letters.

Hello @etorreborre, I have changed it as you said.

**Comment by etorreborre** [comment]
@Nathy-bajo I was trying to modify your branch to make it pass CI but something is not working I'm sorry. 
Is it possible for you to re-create that branch with just one commit with the message `cla: accepted by nathy-bajo` and with your signature? Thank you, I'm sorry for all that hassle.

**Review by etorreborre — APPROVED** [review]

**Comment by etorreborre** [comment]
@Nathy-bajo no need I was finally able to get us into a correct state.

**Pull request merged**
