### PR TITLE
Fix::> replace occurrence of ockam hub with ockam orchestrator

### LINKED ISSUE #4520: Replace Ockam Hub mentions in the codebase with appropriate terms
### Current behavior

We have mentioned Ockam Hub in the codebase a lot, while Ockam Hub as a term doesn't exist anymore. This includes doc comments as well as variable names (e.g. `hub_route`)

### Desired behavior

Rename with Ockam Orchestrator / Ockam Orchestrator Project 

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### PR DESCRIPTION
**Pull request by PsychoPunkSage**
Closes #4520

### CODE REVIEW

**Comment by PsychoPunkSage** [comment]
@SanjoDeundiak 
Please have a look at this PR.... I replaced all the occurrence of ockam hub with ockam Orchestrator.

**Review by SanjoDeundiak — DISMISSED** [review]

**Comment by SanjoDeundiak** [comment]
@PsychoPunkSage thanks for the contribution! I rebased and fixed the commit message

**Comment by SanjoDeundiak** [comment]
@PsychoPunkSage could you please make sure to read and accept the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

**Comment by PsychoPunkSage** [comment]
Hi @SanjoDeundiak 
Here it the [PR](https://github.com/build-trust/ockam/pull/8303) you asked me to make.
Is there anything else I have to do?

**Review by SanjoDeundiak — APPROVED** [review]

**Review by davide-baldo — APPROVED** [review]

**Comment by SanjoDeundiak** [comment]
@PsychoPunkSage thanks for the contribution!

**Pull request merged**
