### PR TITLE
ci: add ockam release installer script

### PR DESCRIPTION
**Pull request by danieled-it**
## Current Behavior

No installer is available to `curl | sh` precompiled ockam binaries

## Proposed Changes

This PR is meant to solve #3487 .

The new script in this PR performs the following when executed on Linux environments:

- Checks the architecture of the machine executing it, throws an error and exits if no related binary is released.
- Checks if `cosign` is available for signature verification, fetches the latest version if it's missing.
- Downloads the latest version of the precompiled `ockam` binary based on the architecture.
- Downloads `sha256sums.txt`, the related `ssha256sums.txt.sig` and the ockam public key for validation.
- Performs checksum validation on the downloaded binary
- Informs the user on how to start using ockam and suggests two ways of storing it in `$PATH` for future usages.

**Usage:**

```bash
curl https://raw.githubusercontent.com/danieled-it/ockam/ci/ockam_installer/tools/scripts/release-installer.sh | bash
```
**Missing features:**

- Handle Mac OS environments (I don't have a Mac to validate the results it would return with `uname -m` and `lscpu`, happy to keep working on this if someone can help)

**Execution results:** (excuse the screenshots, I just wanted to make sure the colors would show up 😄 ):

Case 1: `cosign` already available:
image

Case 2: `cosign` is missing:
image

Further testing needed;

- Unfortunately I can only test on a "Windows running Debian on WSL2" environment, so a validation with other architectures to ensure the initial `case` is correct would be nice.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@danieled-it thank you for an awesome first contribution!! 🥳 
I'll run some tests for it in various environments and report back soon.

**Comment by mrinalwadhwa** [comment]
@danieled-it The script looks great. A couple of suggestions:

1. I think we should use cosign, if it's available in the host machine's path, but if it's not available it doesn't make sense to download it via curl and then verify using it.

2. If possible, it would be nice to not limit the script to bash and try to be a bit more portable. For instance, I wasn't able to test the script in an alpine container where the default shell is ash.

On an M1 mac with the latest macos, `uname -m` returns `arm64` and `lscpu` is not found.

**Comment by danieled-it** [comment]
> I think we should use cosign, if it's available in the host machine's path, but if it's not available it doesn't make sense to download it via curl and then verify using it.

This one was easy to change, done in [35731a3](https://github.com/build-trust/ockam/pull/3488/commits/35731a3d5a4c461fea8e24e6a6a067741768131c).
The new execution in case `cosign` is missing looks like this:

image


> If possible, it would be nice to not limit the script to bash and try to be a bit more portable. For instance, I wasn't able to test the script in an alpine container where the default shell is ash.

I'll try to tweak it for some more shell-intercompatibility, I see the problem for now is the `$OSTYPE` variable on top, that's available only in bash, I'll find some replacement for it.

**Comment by danieled-it** [comment]
I think both shell inter-compatibility and MacOS management are ok now, at least from information I found online, of course some real-life testing will be needed for Mac (at least I was able to test the different shells on Linux on my local machine).

As I'm not familiar with ockam itself, I'd ask for an extra-careful check on the whole `case $OS_TYPE in` block 😄

**Review by mrinalwadhwa — DISMISSED** [review]

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
@danieled-it the script looks great! Thank you for an awesome first contribution!!
I can think of some small improvements but we can tackle those in follow on issues/prs.

**Pull request merged**
