### PR TITLE
Update builder image to bookworm and add net-tools package for netstat

### PR DESCRIPTION
**Pull request by alcolmenar**
## Current behavior

There is an error in CI while using the netstat utility to generate a port and test if it's already in use. The netstat utility doesn't exist in the builder image.

## Proposed changes

- Add the net-tools Debian package that contains netstat tool in the builder Dockerfile #5350 
- Move to Debian bookworm so that we do not have to deal with experimental dependency

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Comment by alcolmenar** [comment]
@metaclips I just realized that this was failing due to me not realizing that `ci` is a valid type and an invalid scope. I took your changes in and reworded the commit. It should pass now. sorry about that

**Comment by alcolmenar** [comment]
@metaclips how does this PR look? should I do anything else?

**Comment by metaclips** [comment]
Thanks @alcolmenar. PR looks good for a merge, I am currently on break so building of the image might take a bit of time, I'll merge this PR and create an issue when we need to update our workflows.

**Review by metaclips — APPROVED** [review]
Thanks for an amazing PR @alcolmenar

**Comment by alcolmenar** [comment]
> Thanks for an amazing PR @alcolmenar

@metaclips it's my pleasure! this is my first repo I've ever contributed to open source and my other PR is my first GitHub Rust commit so it's been fun :)

Unfortunately, it appears this is blocked because you were the last person to commit to the branch. Know anyone else who can rubber stamp it?

**Comment by alcolmenar** [comment]
> Thanks @alcolmenar. PR looks good for a merge, I am currently on break so building of the image might take a bit of time, I'll merge this PR and create an issue when we need to update our workflows.

oh sorry to bother you on break, hope that you're having a good rest!

**Review by davide-baldo — APPROVED** [review]

**Pull request merged**
