### PR TITLE
Added default shell for every job in the workflow

### PR DESCRIPTION
**Pull request by rghdrizzle**
This issue solves the problem in[ issue #4005 ](https://github.com/build-trust/ockam/issues/4005) , the problem was , in every job or run command there was a need for mentioning which shell do we need to run the command in . 

To solve this issue , I used a default to create a map of the settings that will apply to every job in the workflow and gave a default value for shell as bash since every run command in the workflow runs in bash

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@rghdrizzle Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

**Comment by rghdrizzle** [comment]
> 
@mrinalwadhwa 
Done

**Comment by metaclips** [comment]
Close to getting this merged. Seems the email used to sign this commit is rockgameplayhakeem@gmail.com ---- [from the lint CI log](https://github.com/build-trust/ockam/actions/runs/4414325553/jobs/7735889834#step:13:126) ---- and a different email was indicated in the [contributors list](https://github.com/build-trust/ockam-contributors/blob/42666b3b328f488a30ebb0c33dfd1d9362dd8551/CONTRIBUTORS.csv#L201), can we create a PR in the build-trust/ockam-contributors repository adding the other email address?

**Comment by rghdrizzle** [comment]
@metaclips So do I have to change my email in that file or add another entry with a different email ?

**Comment by rghdrizzle** [comment]
> @metaclips So do I have to change my email in that file or add another entry with a different email ?

ok nvm I can add another email beside the one already there

**Review by metaclips — DISMISSED** [review]
Thanks for an amazing PR @rghdrizzle 🚀

**Review by polvorin — DISMISSED** [review]

**Review by polvorin — APPROVED** [review]

**Pull request merged**
