### PR TITLE
docs: [WIP] Update `CLI` documentation for `vault` commands

### LINKED ISSUE #4776: Update CLI documentation for `vault` commands
Details of what the documentation should include can be found at https://github.com/build-trust/ockam/issues/4759

### PR DESCRIPTION
**Pull request by EliKalter**
## Current behavior
The documentation for vault commands in CLI doesn't exist.

## Proposed changes
Add documentation files and have the different commands display them when requested using `--help` option

Fixes #4776

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Comment by EliKalter** [comment]
Can someone please help me fix the commits messages?
I just now read the `CONTRIBUTING.md` file and don't know how to edit commit messages in a pull request,
Also, I just now made git sign all commits automatically (by running `git config --global commit.gpgsign true`),
How do I sign the commits that I created before?

**Comment by adrianbenavides** [comment]
Hey @EliKalter , sorry I couldn't reach out before, but I had a draft PR covering the documentation for the vault commands at https://github.com/build-trust/ockam/pull/4924

Since you didn't start writing the content yet, I'd like to close this PR in favor of mine to keep moving things forward. 

If you are interested in improving our docs, I'd recommend you to check out the https://github.com/build-trust/ockam/issues/4765 issue, which covers the `relay` commands. I'll be adding more details to these issues in the coming days.

**Comment by EliKalter** [comment]
> Hey @EliKalter , sorry I couldn't reach out before, but I had a draft PR covering the documentation for the vault commands at https://github.com/build-trust/ockam/pull/4924
> 
> Since you didn't start writing the content yet, I'd like to close this PR in favor of mine to keep moving things forward. 
> 
> If you are interested in improving our docs, I'd recommend you to check out the https://github.com/build-trust/ockam/issues/4765 issue, which covers the `relay` commands. I'll be adding more details to these issues in the coming days.
> 

I didn't know how to finish this PR anyway and didn't seem to get needed help, good that you took it away.

**Comment by adrianbenavides** [comment]
> and didn't seem to get needed help

Yeah, sorry about that. I was out the past week and couldn't reach out earlier. I'm back again so make sure to pick any other issue if you are interested or ask any question, I'll be happy to help!

**Comment by adrianbenavides** [comment]
Hi again @EliKalter ! Since we both worked on similar stuff in these two PR's, I've added you as a co-author of the the commit here: https://github.com/build-trust/ockam/pull/4924/commits. And thanks again for the time you spent on this PR 🙏 

I saw you've been active on our Discord channel. I'll ping you there to help you out with the next one! 💪

**Comment by EliKalter** [comment]
Thank you so much for giving credit!

**Pull request closed without merging**
