### PR TITLE
solve issue-3054 'tests hang on panic'

### PR DESCRIPTION
**Pull request by Retamogordo**
## Current Behavior
Currently async tests just hang whenever panic occurs.

## Proposed Changes
Wrap exisiting async test blocks with AssertUnwindSafe wrapper and call catch_unwind() on it. This introduces coarse-grained panic catches, assuring ctx.stop() invocation as a teardown code after the test is over.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@Retamogordo thank you for sending this. I think a `cargo fmt` would help satisfy the linters.
Also, please see my note here https://github.com/build-trust/ockam-contributors/pull/90#discussion_r934030505

**Comment by mrinalwadhwa** [comment]
@Retamogordo since your fork allowed pushing. I've fixed the linter errors and pushed to your fork/branch. Let's wait for reviews from @SanjoDeundiak & @adrianbenavides. Then we can merge this.

**Review by adrianbenavides — APPROVED** [review]
Thanks @Retamogordo for looking into this! As far as I understand, this fixes the async tests that manually create a `ctx` and an `executor`, although they could hang if the `ctx.stop()` panics (which is being solved at https://github.com/build-trust/ockam/issues/2996#issuecomment-1200266355). It seems we don't have more tests like this, so that's great!

In any case, we'd still have to fix the `ockam:test` and `ockam:node` macros to close the https://github.com/build-trust/ockam/issues/3054 issue.

We can merge this PR and see if the affected tests don't hang anymore.

**Comment by SanjoDeundiak** [comment]
Hey @Retamogordo, sorry, I didn't include enough information in the description of my issue. We have test macro that wraps (almost) all our async tests. The tests you're fixing here are old tests that we should rewrite to use this macro, so no sense fixing them. The fix should instead go to the macro itself. @adrianbenavides will add some info to the original issue, in case you want to pick it.
Closing this PR

**Pull request closed without merging**
