### PR TITLE
fix(rust): update 'tcp-connection create' output

### LINKED ISSUE #4245: Update TCP Connection output of `ockam tcp-connection create`
## Expected Behavior

The commands output should include the connection ID, while also updating the output format to remove the bulletpoints.

```
$ ockam tcp-connection create --from n1 --to 127.0.0.1:5000

  TCP Connection:
    ID: 2812c77bcc11fb1270333343aee57b93
    From: /node/n1
    To: 127.0.0.1:5000 (/ip4/127.0.0.1/tcp/5000)
```

`ockam tcp-connection create` command is found [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs).

## Current Behavior
The output currently:

```
$ ockam tcp-connection create --from n1 --to 127.0.0.1:5000

  Created TCP Connection:
  • From: /node/n1
  •   To: 127.0.0.1:5000 (/ip4/127.0.0.1/tcp/5000)
  
  Transport ID : 2812c77bcc11fb1270333343aee57b93
```

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by p-gentili**
## Current Behavior
```
$ ockam tcp-connection create --from n1 --to 127.0.0.1:5000

  Created TCP Connection:
  • From: /node/n1
  •   To: 127.0.0.1:5000 (/ip4/127.0.0.1/tcp/5000)
  
  Transport ID : 2812c77bcc11fb1270333343aee57b93
```
## Proposed Changes
```
$ ockam tcp-connection create --from n1 --to 127.0.0.1:5000

  TCP Connection:
    ID: 2812c77bcc11fb1270333343aee57b93
    From: /node/n1
    To: 127.0.0.1:5000 (/ip4/127.0.0.1/tcp/5000)
```
Resolves #4245 

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by etorreborre** [comment]
Hi @p-gentili, I tried to update your PR from the Github UI but that doesn't work because then the commit is not signed :-(. Can you please drop that commit and do the rebase on your branch? Thanks!

**Review by etorreborre — DISMISSED** [review]
Thanks @p-gentili!

**Comment by p-gentili** [comment]
@etorreborre rebased and force-pushed.

**Comment by etorreborre** [comment]
Thanks, I started the CI 🤞

**Review by etorreborre — APPROVED** [review]

**Pull request merged**
