### PR TITLE
Feat/remove pub extern

### LINKED ISSUE #2161: Remove/clean up `pub extern crate` in top level of `ockam_core`
In `ockam_core` we re-export several libraries that we don't need to. We should clean this up. Specifically:

---

```rs
pub extern crate hex;
```
Anything that needs `hex` should be changed to depend on `hex` directly. (We might be able to remove `hex` from ockam-core after this? Not sure, worth trying)

---

```rs
pub extern crate hashbrown;
```
Hashbrown's types are exported from `ockam_core::compat`, so we shouldn't need to export the top level use directly.

---

```rs
pub extern crate async_trait;
```
We already export the macro separately, so `async_trait`'s crate shouldn't need to be public.

### PR DESCRIPTION
**Pull request by Genysys**
## Proposed Changes

This PR closes #2161.
This PR: 

* [Changes the visibility of hex in ockam/core](https://github.com/Genysys/ockam/commit/24cebef95648a476fc31e87ec2639cbd8e340aed).
* [Removes hashbrown from ockam/core](https://github.com/Genysys/ockam/commit/7329e73203c3f742f0a8d1ab85a0f73de3884eb1)
* [Removes unused imports](https://github.com/Genysys/ockam/commit/4348acf2362f96cd64ee63857c4c8feeb828f9a0)

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@Genysys thank you for working on this!

@antoinevg has been working on a re-factor of ockam_core in https://github.com/ockam-network/ockam/pull/2546
It would be good to get thoughts from @antoinevg & @thomcc as you work on the changes in this PR.

**Comment by Genysys** [comment]
Thanks @mrinalwadhwa . @thomcc I would appreciate some pointers on how to remove `pub extern crate async_trait;`. Where is the marcos exported?

**Comment by Genysys** [comment]
hey @adrianbenavides why was this closed? i had already put some time into it

**Comment by adrianbenavides** [comment]
Hello @Genysys , sorry I didn't add a comment before closing it. The reason is that the changes you introduced here are already on `develop`. I guess someone did it as part of other PR. I'll add some context to the original issue giving some details on the current state and what's left to be done.

Thanks again!

**Pull request closed without merging**
