### PR TITLE
chore: removed git-cliff config file from root directory

### LINKED ISSUE #3567: Remove git-cliff config file from root directory
We currently have git-cliff configuration in this [toml file](https://github.com/build-trust/ockam/blob/develop/cliff.toml) in the `root path`, we should move the config file to `./tools/cliff` and set the [changelog generation script](https://github.com/build-trust/ockam/blob/127df6de454784813cb69c785faf2e627afa41c5/tools/scripts/release/changelog.sh#L14) to use the `updated` config path ( passing `--config` git-cliff option )

### PR DESCRIPTION
**Pull request by goverdhan07**
## Proposed Changes

removed git-cliff config file from root directory

fixes #3567 

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Review by metaclips — CHANGES_REQUESTED** [review]
Can we also add config arg here
https://github.com/build-trust/ockam/blob/127df6de454784813cb69c785faf2e627afa41c5/tools/scripts/release/changelog.sh#L14
This should be updated to
```bash
git-cliff $last_git_tag.. --config tools/cliff/cliff.toml --with-commit "$with_commit_msg" --include-path implementations/rust/ockam/$crate/**/*.rs --prepend implementations/rust/ockam/$crate/CHANGELOG.md
```

**Comment by metaclips** [comment]
Thanks for another PR @goverdhan07 🚀

**Review by metaclips — DISMISSED** [review]
Amazing PR! Thanks 🚀

**Review by mrinalwadhwa — DISMISSED** [review]
Thank you for another awesome contribution! 🥳

**Pull request merged**
