### PR TITLE
feat(rust): Improve output of secure-channel list command

### LINKED ISSUE #3391: Improve output of `ockam secure-channel list` command for formatting, color, and json
# Current:

To see the current outputs run:

```
$ ockam node create n1
$ ockam node create n2

$ ockam secure-channel create --from /node/n1 --to /node/n2/service/api
...

$ ockam secure-channel list --node n1

$ ockam secure-channel list --node default
Secure channels for node `n1`:
  0#a0d17e26a17a5917bfd90036c8b5bead
  0#a0d17e26a17a5917bfd90036c8b5bead
```

# Desired:

We want the output of `secure-channel list` it to be similar to the output from [secure-channel create](https://github.com/build-trust/ockam/blob/e74fe2d40a0aa6af548606850058da7c83949251/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L85-L141)

on stdout, if tty

```
$ ockam secure-channel list --node default
/service/a0d17e26a17a5917bfd90036c8b5bead
```

on stderr

```
$ ockam secure-channel list --node default

Secure Channels

  Secure Channel:
    • From: /node/n1
    •   To: /node/n2/service/api (/ip4/127.0.0.1/tcp/50303/service/api)
    •   At: /service/a0d17e26a17a5917bfd90036c8b5bead
```

And also handle json and color, similar to the setup [secure-channel create](https://github.com/build-trust/ockam/blob/e74fe2d40a0aa6af548606850058da7c83949251/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L85-L141)

The code for the `secure-channel list` command is here:
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/list.rs

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by sanjayts**
WIP -- fixes https://github.com/build-trust/ockam/issues/3391

Sample output:
```
ockam secure-channel list --at n3`

Secure Channels

    Secure Channel:
      • From: /node/n3
      •   To: /ip4/127.0.0.1/tcp/49501/service/api
      •   At: /service/55169a0c6d559137bb62165c65058304

    Secure Channel:
      • From: /node/n3
      •   To: /ip4/127.0.0.1/tcp/49509/service/api
      •   At: /service/b35f21a3935ddd5e4e92f0e29dee3547
```

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Review by mrinalwadhwa — DISMISSED** [review]

**Comment by mrinalwadhwa** [comment]
@sanjayts the changes in this PR look great and ready to merge. Thank you for spending time on this!

We can merge after this one last step:

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

**Comment by sanjayts** [comment]
@mrinalwadhwa Awesome, thanks for taking your time to review this. I've created a new PR to accept the CLA. https://github.com/build-trust/ockam-contributors/pull/110

**Review by mrinalwadhwa — DISMISSED** [review]

**Comment by mrinalwadhwa** [comment]
@sanjayts ah looks like there are some small clippy warning, could you fix those please before we merge https://github.com/build-trust/ockam/actions/runs/3099168825/jobs/5017984208

**Comment by sanjayts** [comment]
@mrinalwadhwa Done!

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
@sanjayts Thank you for an awesome first contribution 🥳 🎈

**Comment by sanjayts** [comment]
@mrinalwadhwa Thank you -- it has been a pleasant experience contributing so I would say you have done a great job with fostering a great open source culture for Ockam! :)

**Pull request merged**
