### PR TITLE
fix(rust): use runtime handles

### LINKED ISSUE #2996: Diagnose `Cannot drop a runtime ...` error in rust nodes
This error shows up often

```
thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/shutdown.rs:51:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by twittner**
Hopefully fixes #2996.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
I was able to reproduce the error in #2996, on  this branch, with my very crude test:

```
for i in {1..9}; do RUST_BACKTRACE=1 cargo run --bin ockam node create "n$i"; done
for i in {1..100}; do RUST_BACKTRACE=1 cargo run --quiet --bin ockam node list; done
```

**Comment by pro465** [comment]
hey, @mrinalwadhwa! so you somehow still got the panics?

can i get the backtrace?

**Comment by mrinalwadhwa** [comment]
Trying a few runs again, with a `cargo clean`... just to be sure. Let's see.

**Comment by pro465** [comment]
can i get the backtrace if you the error again?

**Comment by pro465** [comment]
@twittner quite elegant (potential) solution btw! runtimes being dropped in async contexts => use static runtimes and leak them. such simplicity! :chefs_kiss:

**Comment by mrinalwadhwa** [comment]
Had to interrupt this run but things are looking quite promising.
Will try another run later in the day.

```
» for j in {1..50}; do for i in {1..50}; do RUST_BACKTRACE=1 cargo run --quiet --bin ockam node list 1>/dev/null; echo -n "."; done; echo ""; done
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..............................

**Comment by pro465** [comment]
@mrinalwadhwa so no panics?

**Comment by mrinalwadhwa** [comment]
yes so far none.

**Comment by pro465** [comment]
that's good, hooray!

question: should not the `Handle::spawn` method call's returned JoinHandle block forever causing problems?

edit: and `Runtime::spawn` too?

**Comment by pro465** [comment]
@mrinalwadhwa you seem to be using `--quiet` flag which caused us problems before, perhaps you want to remove it?

**Comment by mrinalwadhwa** [comment]
Just finished running 2500 runs of `cargo run --bin ockam node list` with no failures 🎉

**Review by antoinevg — DISMISSED** [review]
"It is said there is no problem in computer science which cannot be solved by [one more level of indirection](https://wiki.c2.com/?OneMoreLevelOfIndirection)."

This is really good work. 👍

**Comment by twittner** [comment]
> @pro465: [...] static runtimes and leak them

I do not think the runtime is leaked. It is owned by `ockam_node::Executor` and dropped when the executor goes out of scope (which should usually happen in sync code, hence the panic no longer occurs).

> @pro465: question: should not the Handle::spawn method call's returned JoinHandle block forever causing problems? [...] and Runtime::spawn too?

I think so. This part is for no_std environments and I only added the Handle-part to be API compatible. Changes to the `JoinHandle` are out of scope for this PR I would say.

**Comment by pro465** [comment]
> @twittner: I do not think the runtime is leaked.

i meant the runtime in no_std environments.

**Comment by pro465** [comment]
sorry to bother you but i have another question: how is `Handle` different from `Arc<Runtime>`?

the docs say:
> The handle is internally reference-counted and can be freely cloned. A handle can be obtained using the [Runtime::handle](https://docs.rs/tokio/1.20.1/tokio/runtime/struct.Runtime.html#method.handle) method.

so how does just using Handle fix the problem?

**Comment by twittner** [comment]
> @pro465: how is `Handle` different from `Arc<Runtime>`?

The `Runtime` contains a `BlockingPool` which it shuts down when dropped which is itself a blocking operation that panics if used in an async context. Dropping the `Handle` OTOH does not cause this shutdown.

**Review by antoinevg — DISMISSED** [review]

**Comment by pro465** [comment]
@twittner oh so that's why, i wondered why would they behave differently, so thank you for clearing it up!

**Comment by mrinalwadhwa** [comment]
@pro465 Thank you so much for all the research you put into this over the last couple of weeks!!
@twittner Thank you for the fix!! and also thank you for adding attribution to @pro465 in the commit https://github.com/build-trust/ockam/pull/3084/commits/8bd0f21ad4248e8ccab3208b35b1b500bebef63d

**Review by mrinalwadhwa — DISMISSED** [review]

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by pro465** [comment]
@mrinalwadhwa thank you so much for the encouraging and kind messages!

also @twittner congrats for fixing another issue 🎉 ! Thank you for the effort and also for the attribution! 
(which, well i don't know if i deserve that, because idk if it helped you in fixing this...)

**Pull request merged**
