### PR TITLE
fix typos and grammatical mistake in README.md file

### PR DESCRIPTION
**Pull request by THEFZNKHAN**
## Current behavior

Grammatical Mistakes and Typos

## Proposed changes

Fix the grammatical mistake and the typos.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by THEFZNKHAN** [comment]
@mrinalwadhwa
Please review my PR
and anything needs to change then tell me 😊.

**Comment by nazmulidris** [comment]
@THEFZNKHAN We cherish and value all contributions - code, feedback, documentation etc. Thank you for spending time on this. In order to make contributions to Ockam (now or in the future), if you haven't already, please add yourself to the Contributor License Agreement in a separate PR.

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file *in a separate pull request* to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR (and a single commit that will ensure that it is verified).

The video below walks you through the process of accepting the Contributor License Agreement (CLA). This is one of the steps you have to follow in order to make a code or no-code contribution.

https://github.com/build-trust/ockam/assets/2966499/d835f521-50b9-4716-86db-4aa4f1b48309

**Comment by THEFZNKHAN** [comment]
@nazmulidris
I sent PR #6816
please review it
In that PR i am adding myself in the contributor list

**Comment by mrinalwadhwa** [comment]
@THEFZNKHAN while we still have to review this change. I'm adding the HACKTOBERFEST-ACCEPTED label so the contribution is counted by hacktoberfest bots before the end of October. Thank you for taking time to contribute 🎉

**Comment by nazmulidris** [comment]
> I sent PR #6816

Thanks for adding yourself to the CLA 👍🏽 . Once that is merged, I will take a look at the PR and merge it.

**Review by nazmulidris — APPROVED** [review]
Looks good to me 🎉

**Review by etorreborre — APPROVED** [review]

**Pull request merged**
