### PR TITLE
Update Identity argument name & doc string for authority (issue #6245)

### LINKED ISSUE #6245: `identity` argument value name on `ockam authority create` should be `IDENTITY_NAME`. The doc string should also be updated
## Current behavior

The `identity` argument value name on `ockam authority create` is `IDENTITY`.
## Desired behavior

The `identity` argument value name on `ockam authority create` should be `IDENTITY_NAME` and the doc string should be updated to `Name of the Identity that the authority will use`.
## Implementation details

This is the path to the argument that must be changed:

https://github.com/build-trust/ockam/blob/d5d3cafbec9fad4f5354c8549fee6da2b00b440d/implementations/rust/ockam/ockam_command/src/authority/create.rs#L99-L101

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

### PR DESCRIPTION
**Pull request by 0scvr**
## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

This PR addresses #6245 .

### CODE REVIEW

**Comment by adrianbenavides** [comment]
Hey @0scvr , thanks for submitting this PR 🙏 

Looks like the email you used to sign your commit (5xp395ab@duck.com) is different from the one you used in the CLA PR (71343264+0scvr@users.noreply.github.com). You would need to either change your commit's email or open a new CLA PR updating your associated email (you can add both if you want).

**Comment by 0scvr** [comment]
> Hey @0scvr , thanks for submitting this PR 🙏 
> 
> Looks like the email you used to sign your commit (5xp395ab@duck.com) is different from the one you used in the CLA PR (71343264+0scvr@users.noreply.github.com). You would need to either change your commit's email or open a new CLA PR updating your associated email (you can add both if you want).

Ah yes, my bad. Let me fix that.

EDIT: Done, #6311 .

**Review by adrianbenavides — APPROVED** [review]
Thanks @0scvr for this PR, ready to merge! 🚂

One quick note: we require commits to be signed. I force-pushed your commit to sign it myself, but in case you want to do it, it's a one-time operation and it's pretty straightforward. Here is how to do it.

> All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

**Comment by 0scvr** [comment]
> Thanks @0scvr for this PR, ready to merge! 🚂
> 
> One quick note: we require commits to be signed. I force-pushed your commit to sign it myself, but in case you want to do it, it's a one-time operation and it's pretty straightforward. Here is how to do it.
> 
> > All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

Glad I could help 😊. Thanks for signing it.

**Pull request merged**
