### PR TITLE
Added documentation for Windows Users (for setting up new cargo project)

### PR DESCRIPTION
**Pull request by rishabh99-rc**
## Current Behaviour
Currently, there is no documentation for the Windows users, who might face an issue while setting up the Rust framework for the first time on their system. 

## Proposed Changes
I have added the documentation for the setup of a new cargo project for the windows users. Hope it might help the beginners to head-start their journey with the Rust framework & the Ockam community.  

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@rishabh99-rc thank you for sending this pull request!

There are a couple of small things to fix before this is ready to merge.

There currently two checks that are [failing](https://github.com/ockam-network/ockam/pull/2396/checks) on this PR, 

1] Make the commit message follow our commit message convention ([failing check](https://github.com/ockam-network/ockam/runs/4587696263?check_suite_focus=true))
- Amend the commit message to `docs: add windows instruction to hello ockam example` with `git commit --amend`
- Force push to your branch with the `--force` flag.

2] Accept the Ockam CLA ([failing check](https://github.com/ockam-network/ockam/runs/4587696080?check_suite_focus=true))

Before we can merge, please accept our Contributor License Agreement (CLA).
a. Read the CLA at: https://www.ockam.io/learn/how-to-guides/contributing/cla

b. To accept the CLA, please send a different pull request to our [contributors repository](https://github.com/ockam-network/contributors) indicating that you accept the CLA by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/main/CONTRIBUTORS.csv) file.

Looking forward to merging your first contribution!

**Comment by rishabh99-rc** [comment]
@mrinalwadhwa, I have changed the commit message, as per the name convention & have also accepted the CLA. 

Here is my pull request for the same: [docs: added my details #60](https://github.com/ockam-network/contributors/pull/60)

Hope it will work now, in case of any further changes, please do let me know.

**Comment by rishabh99-rc** [comment]
Refer: [#60](https://github.com/ockam-network/contributors/pull/60)

@mrinalwadhwa, I have made the changes which you requested, please do merge my PR. 
Since, I was having an issue while pulling the repo, therefore I had to force push my work. But, I haven't changed anything, it's still the same. 

Thanks for the help & sorry for the delay !!

**Comment by mrinalwadhwa** [comment]
Closing this PR since we don't have an accepted CLA PR and this has been open for a long time which would make it hard to merge.

@rishabh99-rc if you want to try again, please send another new PR.

**Pull request closed without merging**
