### PR TITLE
chore(rust): downgrade tauri from 2.0-alpha to 1.4.1 stable

### LINKED ISSUE #5268: Integrate ockam desktop app prototype (ockam_app)
Merge the https://github.com/build-trust/ockam/pull/5222 as soon as possible to enable developers to start working on it.
Make sure is passing by checking license and security issues and code compilation and cherry-pick CI commits from https://github.com/build-trust/ockam/pull/4895.

Optimize CI by avoiding extra typescript compilation: https://github.com/build-trust/ockam/pull/5238
Check if we can downgrade to tauri stable: https://github.com/build-trust/ockam/pull/5242
Add muda dependency and update to latest alpha: https://github.com/build-trust/ockam/pull/5254
Add package/installer: https://github.com/build-trust/ockam/pull/5266

Tauri PR to upgrade unmaintained package : #7359 https://github.com/tauri-apps/tauri/pull/ (to avoid adding a cross-reference)

Parent: #5228

### PR DESCRIPTION
**Pull request by davide-baldo**
Since we don't know when Tauri 2 is going to be stabilized, it's best to downgrade to latest stable version

### CODE REVIEW

**Comment by davide-baldo** [comment]
on linux the app behavior doesn't change, can someone confirm the same on mac?

**Comment by etorreborre** [comment]
@davide-baldo I don't know why the tests are failing but the app works fine for me.

**Comment by metaclips** [comment]
@davide-baldo @etorreborre for CI we use [dependencies for Tauri version 2](https://github.com/build-trust/ockam/blob/56381d7f3173a71bf7ad4a9c9105c03cb6f82157/tools/docker/builder/Dockerfile#L157), if we plan on porting back to stable, we will have to build a new image.

**Comment by davide-baldo** [comment]
The idea is that we should be able to use [muda](https://github.com/tauri-apps/muda/releases) library to have enough flexibility in platform integration. This library should be independent of tauri but in practice tauri 1.4.x has conflicting libraries with muda > 0.3 (~6-month-old, current version 0.6).
Considering how new muda is, it would be naive to think such an early version (0.3) would be stable and ready.
I think staying aligned with tauri alpha is the safer bet for now.

**Pull request closed without merging**
