### PR TITLE
feat: adjust `enroll` logic and output for the new subscription plans

### PR DESCRIPTION
**Pull request by adrianbenavides**
- Ignore the errors at the end, that's happening when retrieving the project and is not related to this PR.
- The output in the code is the final version. I did a final adjustment after the recordings (the blank line after the `Please go to ... and subscribe to an Ockam plan...` line) 

#### New space is created using the subscription flow
- https://asciinema.org/a/nPpd4x8a6Y4Nd8YEdfpRRJe9o
```
    Getting available Spaces accessible to your account.                                                                                                                                                                                         
    No Spaces are accessible to your account.                                                                                                                                                                                                    
                                                                                                                                                                                                                                                 
    Please go to https://orchestrator.ockam.io and subscribe to an Ockam plan to create a new Space.         
                                                                                                                                    
    Press  ENTER ↵  to open https://orchestrator.ockam.io in your browser.                                                                                                                                                                       
    Opening your browser...                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                 
  ⠴ Waiting for you to subscribe to an Ockam plan using your browser...                                                                                                                                                                                                                                              
  ✔ Marked aspiring-goosefish as your default Space, on this machine.                                                                                                                                                                            
                                                                                                                                                                                                                                                 
    This Space has a developer-free Subscription attached to it.       
```

#### Enroll with an existing space with valid trial
- https://asciinema.org/a/qnrmaIPERl0KAzUcFrZ3J8qcD
```
    Getting available Spaces accessible to your account.                                                                                                                                                                                         
    Found existing Space touching-swift.                                                                                                                                                                                                         
                                                                                                                                                                                                                                                 
  ✔ Marked touching-swift as your default Space, on this machine.                                                                                                                                                                                
                                                                                                                                                                                                                                                 
    This Space has a developer-free (trial) Subscription attached to it.
    Started on 2024-09-12 12:00:00.0 +00:00:00 and will end on 2024-11-25 15:07:14.0 +00:00:00.

    Please subscribe to an Ockam plan before the trial ends to avoid any service interruptions https://orchestrator.ockam.io
    If you don't subscribe in that time, your Space and all associated Projects will be permanently deleted.
```

#### Enroll with an existing space with expired trial
- https://asciinema.org/a/ZAxhV784dxHSDbr5WyopT2BPh
```
    Getting available Spaces accessible to your account.                                                                                                                                                                                         
    Found existing Space touching-swift.                                                                                                                                                                                                         
                                                                                                                                                                                                                                                 
    Your Space touching-swift has an expired subscription plan attached to it.                                                                                                                                                                   
    Please go to https://orchestrator.ockam.io and update your Ockam subscription plan to use your Space.                                                                                                                                        
    
    Press  ENTER ↵  to open https://orchestrator.ockam.io in your browser.                                                                                                                                                                       
    Opening your browser...      
                                                                                                                                                                                                                
  ⠴ Waiting for you to subscribe to an Ockam plan using your browser...                                                                                                                                                                                                                                                  
  ✔ Marked touching-swift as your default Space, on this machine.                                                                                                                                                                                
                                                                                                                                                                                                                                                 
    This Space has a developer-free Subscription attached to it. 
```

#### Enroll with an existing space without a subscription
- https://asciinema.org/a/yixP86S2TQVzysyOK1HnAjVnn 
```
    Getting available Spaces accessible to your account.                                                                                                                                                                                         
    Found existing Space touching-swift.                                                                                                                                                                                                         
                                                                                                                                                                                                                                                 
    Your Space touching-swift doesn't have a subscription plan attached to it.                                                                                                                                                                   
    Please go to https://orchestrator.ockam.io and subscribe to an Ockam plan to use your Space. 
                                                                                                                                                
    Press  ENTER ↵  to open https://orchestrator.ockam.io in your browser.                                                                                                                                                                       
    Opening your browser...                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                 
  ⠧ Waiting for you to subscribe to an Ockam plan using your browser... 
  ✔ Marked touching-swift as your default Space, on this machine.                                                                                                                                                                                
                                                                                                                                                                                                                                                 
    This Space has a developer-free Subscription attached to it. 
```

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@adrianbenavides some notes:

New space is created using the subscription flow

```
    Getting available Spaces accessible to your account.                                                                                                                                                                                         
    No Spaces are accessible to your account.                                                                                                                                                                                                    
                                                                                                                                                                                                                                                 
    Please go to https://orchestrator.ockam.io and subscribe to create a new Space.         
                                                                                                                                    
    Press  ENTER ↵  to open https://orchestrator.ockam.io in your browser.                                                                                                                                                                       
    Opening your browser...                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                 
  ⠴ Waiting for you to subscribe using your browser...                                                                                                                                                                                                                                              
  ✔ Marked aspiring-goosefish as your default Space, on this machine.                                                                                                                                                                            
                                                                                                                                                                                                                                                 
    This Space has a Basic Subscription attached to it.    
```

**Comment by mrinalwadhwa** [comment]
Enroll with an existing space with valid trial

```
    Getting available Spaces accessible to your account.                                                                                                                                                                                         
    Found existing Space touching-swift.                                                                                                                                                                                                         
                                                                                                                                                                                                                                                 
  ✔ Marked touching-swift as your default Space, on this machine.                                                                                                                                                                                
                                                                                                                                                                                                                                                 
    This Space has a Trial of the Basic Subscription attached to it.
    Your trial started on 12, Nov 2024 and will end in 7 days.

    Please go to https://orchestrator.ockam.io and subscribe before the trial ends to avoid any service interruptions.
    If you don't subscribe in that time, your Space and all associated Projects will be permanently deleted.
```

**Comment by mrinalwadhwa** [comment]
Enroll with an existing space with expired trial

```
    Getting available Spaces accessible to your account.                                                                                                                                                                                         
    Found existing Space touching-swift.                                                                                                                                                                                                         
                                                                                                                                                                                                                                                 
    Your Trial of the Basic Subscription on the Space touching-swift has ended.
    Please go to https://orchestrator.ockam.io and subscribe to one of our paid plans to use your Space.
    All Projects in this Space will be deleted on 10, Dec 2024.

    Press  ENTER ↵  to open https://orchestrator.ockam.io in your browser.                                                                                                                                                                       
    Opening your browser...      
                                                                                                                                                                                                                
  ⠴ Waiting for you to subscribe using your browser...                                                                                                                                                                                                                                                 
  ✔ Marked touching-swift as your default Space, on this machine.                                                                                                                                                                                
                                                                                                                                                                                                                                                 
    This Space has a Gold Subscription attached to it. 
```

We will have a few days of grace period after trial expires and before projects are deleted. Assume 3 days for now. If that date has passed:

replace
> All Projects in this Space will be deleted on 10, Dec 2024.

with
> All Projects in this Space were deleted on 10, Dec 2024.

**Comment by mrinalwadhwa** [comment]
Enroll with an existing space without a subscription

```
    Getting available Spaces accessible to your account.                                                                                                                                                                                         
    Found existing Space touching-swift.                                                                                                                                                                                                         
                                                                                                                                                                                                                                                 
    Your Space touching-swift doesn't have Subscription attached to it.                                                                                                                                                                   
    Please go to https://orchestrator.ockam.io and subscribe to use the Space.
                                                                                                                                                
    Press  ENTER ↵  to open https://orchestrator.ockam.io in your browser.                                                                                                                                                                       
    Opening your browser...                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                 
  ⠧ Waiting for you to subscribe using your browser... 
  ✔ Marked touching-swift as your default Space, on this machine.                                                                                                                                                                                
                                                                                                                                                                                                                                                 
    This Space has a Gold Subscription attached to it. 
```

**Comment by adrianbenavides** [comment]
Done. I've attached some screenshots with the dates formatting changes.

## Enroll with an existing space with valid trial

image

## Enroll with an existing space with expired trial; within period grace

image

## Enroll with an existing space with expired trial; expired period grace

image

**Review by polvorin — APPROVED** [review]

**Pull request merged**
