### PR TITLE
Corrected action variable in PolicyAccessControl Debug impl

### PR DESCRIPTION
**Pull request by younes-io**
## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [X] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by SanjoDeundiak** [comment]
@younes-io Could you please accept the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

**Comment by younes-io** [comment]
@SanjoDeundiak why would I add you to the list of Contributors ? Also, I don't have your email, if that's required o;O
Sorry I'm confused... Should I add YOUR details or mine ?

**Comment by SanjoDeundiak** [comment]
> @SanjoDeundiak why would I add you to the list of Contributors ? Also, I don't have your email, if that's required o;O
> 
> Sorry I'm confused... Should I add YOUR details or mine ?

Sorry, you need to add your details)

**Comment by younes-io** [comment]
> > @SanjoDeundiak why would I add you to the list of Contributors ? Also, I don't have your email, if that's required o;O
> > Sorry I'm confused... Should I add YOUR details or mine ?
> 
> Sorry, you need to add your details)

@SanjoDeundiak  Done. cf. https://github.com/build-trust/ockam/pull/7244

**Review by SanjoDeundiak — APPROVED** [review]

**Comment by SanjoDeundiak** [comment]
@younes-io thank you! I fixed the commit message to align with our convention, now we can land the PR

**Comment by younes-io** [comment]
> @younes-io thank you! I fixed the commit message to align with our convention, now we can land the PR

Sorry for that.. I didn't pay attention until I pushed xD but I tried to stick to that in the other PRs lol
thank you

**Pull request merged**
