### PR TITLE
refactor(rust): remove LONG_TESTS env var usage/mention

### PR DESCRIPTION
**Pull request by saputkin**
Working on assigned issue - #4830

## Current behavior
As described in issue #4830, in the past there was a usage of the LONG_TESTS env variable, currently its no longer needed as there are no long bats tests.

## Proposed changes
BATS.md:
- Removed mention of LONG_TESTS env variable
- Removed sentance "that don't take too long" that points that there are longer tests.
orchestrator.bash:
- Removed helper function "skip_if_long_tests_not_enabled()"

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Review by polvorin — APPROVED** [review]
:+1:

**Comment by saputkin** [comment]
Hi, I rebased and it needs to run the workflows again 😬 @polvorin

**Comment by etorreborre** [comment]
Hi @saputkin it appears that your latest commit is signed but its signature cannot be verified by Github. Did you upload your public signing key?

**Comment by etorreborre** [comment]
@saputkin can you please rebase the PR instead of doing a merge? Because we don't accept merge commits in PRs. Thank you

**Comment by saputkin** [comment]
@etorreborre yup, sorry made a mess in my repo :) will create a clean PR.
you were correct about the key, thanks

**Comment by etorreborre** [comment]
No worries, that happens :-)

**Pull request closed without merging**
