### PR TITLE
feat(rust): move `multiaddr_to_socket_addr` method into `MultiAddr`

### LINKED ISSUE #4390: Move `multiaddr_to_socket_addr` method into `MultiAddr`
ref: https://github.com/build-trust/ockam/pull/4172#discussion_r1119912671

### Current

The `multiaddr_to_socket_addr` is a static function that operates on a `MultiAddr`.

### Desired

Move that function as part of the `MultiAddr` struct so we can call it as `ma.to_socket_addr()`

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by hugoamalric**
## Current behavior

The multiaddr_to_socket_addr is a static function that operates on a MultiAddr.

## Proposed changes

Move that function as part of the `MultiAddr` struct.

Closes #4390

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Review by adrianbenavides — CHANGES_REQUESTED** [review]
Hey @hugoamalric , the PR looks great! Could you please rebase on top of develop and fix the conflicts? We'll merge it as soon that gets done, thanks 🙏

**Review by adrianbenavides — DISMISSED** [review]

**Comment by adrianbenavides** [comment]
Looks ready to merge now @hugoamalric , thanks again for working on this one! 💪

**Review by SanjoDeundiak — DISMISSED** [review]

**Comment by etorreborre** [comment]
Hi @hugoamalric, I didn't spot this but the build is failing because you need to sign your commits (that's actually the first item in the PR checklist :-)). Please follow the instructions [on the Github page](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) on how to do it. It shouldn't take long and then it's done forever!

**Comment by hugoamalric** [comment]
You're welcome ! :) @adrianbenavides 
You're right @etorreborre, my commit wasn't properly signed for some reason.

**Review by adrianbenavides — DISMISSED** [review]

**Review by SanjoDeundiak — APPROVED** [review]

**Pull request merged**
