### PR TITLE
feat(elixir): identity secure channel implementation in elixir

### PR DESCRIPTION
**Pull request by hairyhum**
Depends on #2789 

In order to support identity secure channels with Rust,
implement a channel on top of encryption secure channel
using Rust sidecar identity service.

Identity service implementation is currently pluggable and implements
rust sidecar or stub implementation (for testing purposes)

Add authorization to only process inner messages from encryption secure channel
Add authorization rules to require identity secure channel in workers.

Allow per-address authorization config
Make secure channel create always wait for channel to be established
Allow changing authorization config from handshake callbacks

Add identity secure channel service provider

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor License Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/contributors](https://github.com/build-trust/contributors) repository.

### CODE REVIEW

**Comment by hairyhum** [comment]
@SanjoDeundiak  I'm looking at the `Contact` data structure that we pass in the identity handshake and I can't find an encoding schema for it. Trying to figure out the implicit encoding I've found those 23 types: https://gist.github.com/hairyhum/441bce5f550d3f604a1c3c3593fbcb50 

If we're going to exchange contacts between implementations, we can't rely on implicit encoding of such depth. Can you please make a BARE schema for the contact?

**Comment by mrinalwadhwa** [comment]
I think we should consider delegating identity authentication to the rust sidecar. The Identity related data structures in Rust can use some refactoring/simplification.
Until they are simpler ... it maybe better to get identity authentication from the sidecar.

**Comment by hairyhum** [comment]
Currently waiting for the Identity API to be finalized.

**Comment by hairyhum** [comment]
Example usage with services:

```
iex(1)> Ockam.Services.start_service(:identity_secure_channel)
[{:ok, #PID<0.627.0>, "identity_secure_channel"}]

iex(2)> Ockam.Services.start_service(:echo, [authorization: Ockam.Services.AuthorizationConfig.identity_secure_channel()])
[{:ok, #PID<0.629.0>, "echo"}]

iex(3)> alias Ockam.Identity                                       
Ockam.Identity

iex(4)> {:ok, vault} = Ockam.Vault.Software.init()
{:ok, %Ockam.Vault.Software{id: [1, 1]}}

iex(5)> {:ok, bob, bob_id} = Identity.create(Ockam.Identity.Stub) 
{:ok, {Ockam.Identity.Stub, "DATA_GM2DMMZX"}, "ID_GM2DMMZX"}

iex(6)> Ockam.Identity.SecureChannel.create_channel(identity: bob, encryption_options: [vault: vault], address: "bob_channel", route: ["identity_secure_channel"], trust_policies: [{:cached_identity, [Ockam.Identity.TrustPolicy.KnownIdentitiesEts]}])
{:ok, "bob_channel"}

 ## Echo works with channel

iex(7)> Ockam.Workers.Call.call_on_current_process("VIA CHANNEL", ["bob_channel", "echo"])
18:15:18.273 [info]  
ECHO
MESSAGE: %Ockam.Message{local_metadata: %{channel: :identity_secure_channel, identity: "ID_GM2DMMZX", source: :channel}, onward_route: ["echo"], payload: "VIA CHANNEL", return_route: ["ISC_R_df894a9372a06ef0", "c5afe7d3ee689fc1"], version: 1}
REPLY: %Ockam.Message{local_metadata: %{channel: :identity_secure_channel, identity: "ID_GM2DMMZX", source: :channel}, onward_route: ["ISC_R_df894a9372a06ef0", "c5afe7d3ee689fc1"], payload: "VIA CHANNEL", return_route: ["echo"], version: 1}
{:ok,
 %Ockam.Message{
   local_metadata: %{
     channel: :identity_secure_channel,
     identity: "ID_G42DOMI=",
     source: :channel
   },
   onward_route: ["c5afe7d3ee689fc1"],
   payload: "VIA CHANNEL",
   return_route: ["bob_channel", "echo"],
   version: 1
 }}
 
 ## Echo does not work without channel
 
iex(8)> Ockam.Workers.Call.call_on_current_process("WITHOUT CHANNEL", ["echo"])           

18:15:28.817 [debug] check from identity channel %Ockam.Message{local_metadata: %{source: :local}, onward_route: ["echo"], payload: "WITHOUT CHANNEL", return_route: ["6730aed5adec8f91"], version: 1}
 
18:15:28.817 [warning] Worker Elixir.Ockam.Services.Echo handle_message failed. Reason: {:from_identiy_secure_channel, :invalid_metadata, %{source: :local}}
{:error, :timeout}

```

**Review by polvorin — DISMISSED** [review]

**Review by mrinalwadhwa — DISMISSED** [review]

**Comment by mrinalwadhwa** [comment]
This looks great! A couple of side-notes:
1. Over time Identity Secure Channel should become the only secure channel available to users. There is no need to create a secure channel / secure channel without an identity.
2. We should add CI test for the examples in https://github.com/build-trust/ockam/tree/develop/examples/elixir

**Review by mrinalwadhwa — APPROVED** [review]

**Pull request merged**
