### PR TITLE
refactor(rust): improve ockam enroll project config step by warning u…

### LINKED ISSUE #6060: Improve `ockam enroll` project configuration step by warning user not to exit process
## Current behavior
When a user runs `ockam enroll` and they don't have a project already created in their account on Ockam Orchestrator, then it might take ~ 2 minutes for this process to complete. During this time `ockam enroll` displays a [progress spinner](https://docs.rs/indicatif/latest/indicatif/struct.ProgressBar.html#method.new_spinner) and "Configuring project..." text in the terminal. Here's a [video at timestamp 1:04](https://asciinema.org/a/608023?t=1:04) that display this.

During this time, if the user presses <kbd>Ctrl+C</kbd> then it terminates the `ockam` process. This is not desirable since it leaves the local state in an inconsistent state. And they have to recover from this by running `ockam reset -y` and then run `ockam enroll` again.

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

## Desired behavior
Display a prompt beside “Configuring project...” to let the user know that they should not close the terminal window or press <kbd>Ctrl+C</kbd> to exit out of this. And that it might take about 2 minutes for this operation to complete. An example of this is shown in the following screenshot.

Image

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### PR DESCRIPTION
**Pull request by jltorresm**
Improve ockam enroll project configuration step by warning user not to exit process.

Adds a warning message to inform users that the enrollment process could take about 2 minutes. And that they shouldn't close or terminate the process before it finishes to avoid inconsistent states.

Closes: #6060

## Current behavior

When the user enrolls and doesn't have an existing project the process of configuring the project can take about 2 minutes. The current implementation shows a spinner with the message "Configuring project..." but no warning for the user on how long it will take.

## Proposed changes

The improved message has information of how long it could take and a warning to not exit or terminate the process.

| Before | After |
|--------|--------|
| before | after | 

How it looks now

output2

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@jltorresm Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by adrianbenavides** [comment]
Looks great! We'll merge it as soon as the CLA PR is merged 👍

**Comment by jltorresm** [comment]
@adrianbenavides this is great! Would you mind approving the run of the checks?

**Review by adrianbenavides — APPROVED** [review]
Everything looks good to merge now, thanks a lot @jltorresm for this contribution! 🙏

**Pull request merged**
