### PR TITLE
ci: Relax permission scope in release-tag.yml workflow #3991

### PR DESCRIPTION
**Pull request by sriharshamajeti**
## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@sriharshamajeti Thank you for spending time on this, before we can merge please

- [x] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

**Review by metaclips — DISMISSED** [review]
Approved! 🚀. Thanks for an amazing PR and welcome to the Ockam community.

**Comment by mrinalwadhwa** [comment]
@metaclips could you also amend out the issue reference part of the commit message.

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by metaclips** [comment]
> @metaclips could you also amend out the issue reference part of the commit message.

Done

**Comment by sriharshamajeti** [comment]
> Approved! 🚀. Thanks for an amazing PR and welcome to the Ockam community.

Thank you @metaclips it means a lot.

**Pull request merged**
