### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NathanTarbert**
Fix grammer

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by adrianbenavides** [comment]
Hey @NathanTarbert, thanks for opening this PR. It looks good to merge but in order for us to merge it we need you to accept the Ockam Contributor License Agreement (see below for more details). As soon as you do that we can merge your PR :+1: 

> - [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

**Comment by NathanTarbert** [comment]
Hi Adrian, thanks for reaching out to me. I updated the CONTRIBUTORS.csv

Best,
Nathan
________________________________

**Comment by adrianbenavides** [comment]
Hey @NathanTarbert I'm having some trouble merging your PR. It looks like the email address associated to your commits is `66887028+nathantarbert@users.noreply.github.com` which is different from the one you added to the [`CONTRIBUTORS.csv`](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file.

I think the easiest solution would be to close https://github.com/build-trust/ockam/pull/3862 and https://github.com/build-trust/ockam/pull/3885 and create a new PR with those changes signed with the email address you provided.

Let me know what you think :+1:

**Comment by mrinalwadhwa** [comment]
@NathanTarbert sorry that we had trouble landing your changes. I've worked around the problem and landed your changes from the two PRs and landed them in https://github.com/build-trust/ockam/pull/3975 .. while making sure your credit is maintained in the commit log.

Thank you so much for spending time on improving the README .. looking forward to many more contributions. Now that the committers file has both your email, it should be easy to land any future contributions.

**Pull request closed without merging**
