### PR TITLE
fixes#6143 changed the error message

### LINKED ISSUE #6143: Improve `ockam project list` when there are no projects
# Current behavior

When there is no local state (e.g. after you run `ockam reset -y`) and you run `ockam project list` the following error is shown.

Image

# Desired behavior

It should display a message saying that local state is empty and there are no projects. Also the user might be instructed to run `ockam enroll` to create a default project.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### PR DESCRIPTION
**Pull request by Salonikansal2**
Fixes #6143
changed the error message displayed when local state is empty  
@nazmulidris

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@Salonikansal2 while we still have to review this change. I'm adding the `HACKTOBERFEST-ACCEPTED` label so the contribution is counted by hacktoberfest bots before the end of October. Thank you for taking time to contribute 🎉

**Comment by Salonikansal2** [comment]
Thanks for your efforts @mrinalwadhwa

**Comment by Salonikansal2** [comment]
gentle reminder to review changes 
@adrianbenavides 
@nazmulidris

**Comment by Salonikansal2** [comment]
Gentle reminder  , @nazmulidris , @adrianbenavides  . Sorry for such hurry in behavior but actually I participated in hacksquad competition due to which I need them merged as soon as possible

**Comment by Salonikansal2** [comment]
@metaclips

**Review by adrianbenavides — COMMENTED** [review]
The change should be done at the `project list` level, in [this function](https://github.com/build-trust/ockam/blob/140a8bd71183754d70ec1e4bc1a5c962062fa0a9/implementations/rust/ockam/ockam_command/src/project/list.rs#L42).

You can use something like:

```rust
if !opts.state.is_enrolled()? {
    return Err(miette!("You must enroll before you can list your projects"));
}
```

**Comment by Salonikansal2** [comment]
Sorry , for the late reply ,was busy in college.
Just summited my new pr #6808 by making the changes you suggested
@adrianbenavides 
Thanks for your time

**Comment by adrianbenavides** [comment]
Closed in favor of: https://github.com/build-trust/ockam/pull/6808

**Pull request closed without merging**
