### PR TITLE
feat(rust): delete relays interactive

### LINKED ISSUE #6464: Make `ockam relay delete` (no args) interactive by asking the user to choose from a list of relay names to delete (tuify)
# Current behavior

When a user runs `ockam relay delete` without any arguments, currently they are presented with an error & help text. Here's a screenshot of this.

Image

# Desired behavior

Instead of displaying help text, change the behavior of this command so that it becomes interactive with the user. Note that this can only be allowed to happen if:
- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.

1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of relay names, at the default node. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), display a confirmation prompt letting the user know that that a destructive operation is about to take place with the relay names they have selected. Use `select_from_list()` to display this prompt. They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

3) If they choose "YES", then delete each selected relay, and display a success / failure message for each relay that got deleted. 
   - If an operation succeeds then use the ✅ emoji as a prefix for the message. 
   - And if it fails, then use the ⚠️ emoji as a prefix for the message.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> Image
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/delete.rs#L42) you can look at to see where the `ockam relay delete` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

### PR DESCRIPTION
**Pull request by PanGan21**
## Current behavior

Errors out when the user doesn't specify a relay name.

## Proposed changes

Closes #6464
- `relay_name` argument becomes optional
- If the user provides a `relay_name` then uses the provided `relay_name`
- If the user doesn't provide a `relay_name` and the terminal is interactive, and the user didn't pass any of --no-output or --quiet flags then the terminal shows all available relays and allows the user select one or more from a list
- Then for all the selected relays - one for old case - multiple or one for new case - check, confirm and delete

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@PanGan21 Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by PanGan21** [comment]
> @PanGan21 Thank you for spending time on this, before we can merge please
> 
> * [ ]  Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.
> 
> The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

Hi @mrinalwadhwa ! Thanks for the reminder. Is it required to be done in a separate pr or I can just push the new `CONTRIBUTORS.csv` in this pr?

**Comment by mrinalwadhwa** [comment]
@PanGan21 in a separate PR please

**Comment by PanGan21** [comment]
> @PanGan21 in a separate PR please

Done in this pr #6744

**Comment by PanGan21** [comment]
Hi @mrinalwadhwa  would it be possible to review this pr in October?

**Review by adrianbenavides — COMMENTED** [review]
Hey @PanGan21 thanks for the PR! We are refactoring several commands to add the `tui` experience. You should use the `node delete` logic as a reference and keep the code as similar to that as possible.

Here is the code:

https://github.com/build-trust/ockam/blob/2a2843eb3c57c5e91819c837df0804664f30e2c6/implementations/rust/ockam/ockam_command/src/node/delete.rs#L44

**Comment by mrinalwadhwa** [comment]
@PanGan21 while we still have to review this change. I'm adding the `HACKTOBERFEST-ACCEPTED` label so the contribution is counted by hacktoberfest bots before the end of October. Thank you for taking time to contribute 🎉 

Please not @adrianbenavides's comment above.

**Comment by PanGan21** [comment]
> Hey @PanGan21 thanks for the PR! We are refactoring several commands to add the `tui` experience. You should use the `node delete` logic as a reference and keep the code as similar to that as possible.
> 
> Here is the code:
> 
> https://github.com/build-trust/ockam/blob/2a2843eb3c57c5e91819c837df0804664f30e2c6/implementations/rust/ockam/ockam_command/src/node/delete.rs#L44

Hi! I did some refactoring, let me know what you think

**Comment by adrianbenavides** [comment]
@PanGan21 Your PR is going to be merged as part of https://github.com/build-trust/ockam/pull/6889. You'll appear as co-author of the PR's commit 👍 Thank you so much for your help with this one 🙏

**Pull request closed without merging**
