### PR TITLE
add more executables in cloud node image

### PR DESCRIPTION
**Pull request by metaclips**

### CODE REVIEW

**Review by mrinalwadhwa — DISMISSED** [review]

**Review by hairyhum — CHANGES_REQUESTED** [review]
Can we also have the `ls` command?
I think it was missing the last time I checked.

**Comment by sobi3ch** [comment]
Maybe we should write down some list of our basic commands/tools we want in each container regardless of the purpose?

**Comment by metaclips** [comment]
> Can we also have the `ls` command? I think it was missing the last time I checked.

Done. Please review.

**Review by hairyhum — DISMISSED** [review]

**Comment by metaclips** [comment]
@Mergifyio refresh

**Review by mrinalwadhwa — DISMISSED** [review]

**Review by mrinalwadhwa — APPROVED** [review]

**Pull request merged**
