### PR TITLE
fix(rust): fix hyphen behaviour in #3068

### PR DESCRIPTION
**Pull request by pro465**
## Current Behavior

described in #3068
## Proposed Changes

replace `-/` and `/-` in args with stdin before parsing
## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by pro465** [comment]
we have to first see if this passes all checks except Commits, then i will force push this to make Commits pass as well

**Comment by pro465** [comment]
@mrinalwadhwa so, I can't seem to be able to install `gpg` to sign the commits, could you help me?

**Comment by mrinalwadhwa** [comment]
@pro465 yes, don't worry about it, I'll sign the commits as part of the merge.

**Comment by pro465** [comment]
@mrinalwadhwa ok, thank you!

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
The changes look great 🎉 
Preparing to merge in https://github.com/build-trust/ockam/pull/3129

**Comment by mrinalwadhwa** [comment]
Landed in https://github.com/build-trust/ockam/pull/3129
@pro465 Thank you for another awesome contribution 🥳

**Comment by pro465** [comment]
@mrinalwadhwa thank you too for the help & encouragement ❤️

**Pull request closed without merging**
