### PR TITLE
Upgrade aws-sdk-kms to 0.22.0

### LINKED ISSUE #3951: Fix upgrade of aws-sdk-kms from 0.21.0 to 0.22.0
this dependabot pr is failing https://github.com/build-trust/ockam/actions/runs/3749498519/jobs/6368046924

### PR DESCRIPTION
**Pull request by dzvon**
Closes #3951 #3924

### CODE REVIEW

**Review by mrinalwadhwa — DISMISSED** [review]

**Review by mrinalwadhwa — DISMISSED** [review]

**Comment by mrinalwadhwa** [comment]
@dzvon That changes look great. Thank you for an awesome first contribution.
The PR will merge shortly after the checks pass.

**Comment by mrinalwadhwa** [comment]
Cargo deny check is failing https://github.com/build-trust/ockam/actions/runs/3763424459/jobs/6396940139

One of the upgraded versions brought an MPL Licensed dependency. We don't allow MPL Licensed dependencies because they are incompatible with our Apache 2.0 License.

Would be good to find a way to avoid it.

**Comment by dzvon** [comment]
```
ockam_vault v0.67.0 
├── aws-config v0.52.0
│   ├── aws-http v0.52.0
│   │   ├── aws-types v0.52.0
│   │   │   ├── aws-smithy-client v0.52.0
│   │   │   │   ├── hyper-rustls v0.23.2
│   │   │   │   │   └── webpki-roots v0.22.6
```

It's webpki-roots, which introduced by aws-config. I will attempt to find a way to avoid using hyper-rustls.

**Comment by etorreborre** [comment]
@dzvon I collected your changes with the update of aws-config in https://github.com/build-trust/ockam/pull/4293

**Pull request closed without merging**
