### PR TITLE
refactor(rust): use `Duration` for status `timeout` argument

### LINKED ISSUE #6374: Replace `timeout` argument type on `ockam status` command to `Duration`
## Current behavior

The `timeout` argument on `ockam status` is of type `u64`.

## Desired behavior

The `timeout` argument on `ockam status` should be of type `Duration` and its doc string should have removed the `(in seconds)` part. Also, the default value should be changed to `30s` and the `value_parser` argument should be added calling the `duration_parser` function.

Take this as an example:

https://github.com/build-trust/ockam/blob/59f52a66cc84ad682d9f4ea5715057f97f8eb7a3/implementations/rust/ockam/ockam_command/src/message/send.rs#L47-L49

## Implementation details

This is the argument that must be changed:

https://github.com/build-trust/ockam/blob/5019283dfcb3ed95853e3729c2313f0e475a788e/implementations/rust/ockam/ockam_command/src/status.rs#L31-L33

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

### PR DESCRIPTION
**Pull request by parkercouch**
## Current behavior

The `timeout` argument on `ockam status` is of type `u64`. 

## Proposed changes

Fixes #6374 
`timeout` is now expressed as a `Duration`.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Review by adrianbenavides — COMMENTED** [review]
Looks perfect @parkercouch, I will approve it once your CLA PR gets merged 👍 

Thanks a lot for taking your time with this issue!

**Comment by adrianbenavides** [comment]
Hey @parkercouch ! I recently had to [make some changes](https://github.com/build-trust/ockam/pull/6988/files) in this command while fixing a bug, and I ended up fixing the issue https://github.com/build-trust/ockam/issues/6374, so I'll be closing this PR.

Thanks anyway for your help, and let me know if I can help you with any other issue you would like to work on 👍

**Comment by parkercouch** [comment]
> Thanks anyway for your help, and let me know if I can help you with any other issue you would like to work on 👍 

This at least allowed me to get everything running locally so I'm set up to work on other things. I'll dive into another easy issue next week

**Comment by adrianbenavides** [comment]
Nice! And again, ping me if you need any help, here or in Discord!

**Pull request closed without merging**
