### PR TITLE
feat(rust): remote_tracer client of tracing service

### PR DESCRIPTION
**Pull request by hairyhum**
Similar API to RemoteForwarder.

Using #1578

### CODE REVIEW

**Comment by SanjoDeundiak** [comment]
@hairyhum so what is the purpose of this service?

**Comment by hairyhum** [comment]
@SanjoDeundiak To create wiretap workers on the Hub to see what a certain step in the Hub routing sees.

**Comment by SanjoDeundiak** [comment]
> @SanjoDeundiak To create wiretap workers on the Hub to see what a certain step in the Hub routing sees.

I think the trick with end-to-end encryption is that you don't depend on what's going on on server-side and you can effectively demonstrate security features on client side. Using other words: the server may be malicious, this is why we need end-to-encryption, therefore, demonstrating that server doesn't see the data by asking it, doesn't prove anything. Showing what we send to the server is the right way.

**Comment by hairyhum** [comment]
I think you're coming from the point of view of proof, but my intention was to make a demo. And malicious servers are completely outside of the scope of the demo.
Showing "what the middle sees" is more snappy as a demo.

Also the Rust application is not always the termination point for the secure channel. If we establish a channel with the Hub to get something from another service. And secure channel is not the only use for wiretap.

The main motivation here was that getting logs from server is hard, especially in demo scenarios.

**Comment by SanjoDeundiak** [comment]
> I think you're coming from the point of view of proof, but my intention was to make a demo. And malicious servers are completely outside of the scope here.
> Showing "what the middle sees" is more snappy in a demo context.
> 
> Also the Rust application is not always the termination point for the secure channel. If we establish a channel with the Hub to get something from another service. And secure channel is not the only use for wiretap.
> 
> The main motivation here was that getting logs from server is hard, especially in demo scenarios.
> 
> It's fine with me if you make existing demos work without it, but in the future demos I'll need that.

I know we want demo, but the idea of demo is to show end-to-end encrypted channels, and showing that we don't trust server and use it solely for transportation needs is a good way of demonstrating our "Zero Trust Architecture".
I think yesterday @mrinalwadhwa mentioned good approach of showing what server sees - adding local tcp hop which prints payloads.

**Comment by antoinevg** [comment]
I don't understand Ockam well enough yet to comment on the value of this as a demo/example but would like to comment on the utility as a debugging aid.

Specifically in my case it would have been very useful to see the routing from the perspective of the server while I was trying to understand why messages in the Kafka streams examples weren't being forwarded to the echoer.

That said @SanjoDeundiak, is your main point that this functionality is useless for demonstrating end-to-end encrypted channels?

If so, I agree this is a valid concern. 

Do you have any ideas on how we could avoid this while still being able to have this (or something else?) functionality to get debug visibility on server-side communication?

Otherwise, what other negative outcomes do we need to guard against if we go down this road?

**Comment by etorreborre** [comment]
@hairyhum should we close this PR now?

**Pull request closed without merging**
