### PR TITLE
refactor(rust): use explicit column lists

### LINKED ISSUE #6947: Use explicit column list in `SELECT` SQL statements
In [this PR](https://github.com/build-trust/ockam/pull/6913) SQL support is introduced. We would like to use an explicit set of columns in every `SELECT` statements, since this helps to prevent mistakes

### PR DESCRIPTION
**Pull request by MatthewLeboffe**
## Current behavior

In [this pr](https://github.com/build-trust/ockam/pull/6913), SQL was introduced. Prior to our pull request, SELECT statements in our SQL queries were utilizing the * notation, which fetched all columns indiscriminately. This approach is considered bad practice and an issue was requested to use explicit columns in SELECT statements. 

Fixes #6947

## Proposed changes

To help prevent mistakes when using SQL queries, we can explicitly specify columns in every SELECT statement, significantly reducing the risk of errors.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@MatthewLeboffe @Sweetsuro thank you for sending the PR.
Thank you for spending time on this, before we can merge could both of you, in 2 separate PRs, please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by Sweetsuro** [comment]
Hi @mrinalwadhwa ! I believe we have already done so as a part of this PR, would you rather we have this done in separate in PRs?

**Comment by mrinalwadhwa** [comment]
Yes, they have to be 2 separate PRs - one for each of you, for our CI workflows to pick things up correctly. Sorry about the extra steps there.

**Comment by Sweetsuro** [comment]
Hi @mrinalwadhwa ! Now that both Matthew and I have accepted the clas, and that they are merged, is there anything else we need to do for this PR to be merged?

**Review by etorreborre — APPROVED** [review]
Everything looks good. Thanks for your contribution @MatthewLeboffe and @Sweetsuro!

**Pull request merged**
