### PR TITLE
feat(rust): add interactive tui to vault show

### LINKED ISSUE #6474: Make `ockam vault show` (no args) interactive by asking the user to choose from a list of vaults to show (tuify)
# Current behavior

When a user runs `ockam vault show` without any arguments, currently they are shown an error if there are no vaults:

Image

Or the default vault if there is a default one:

Image

# Desired behavior

Change the behavior of this command so that it becomes interactive with the user when no arguments are passed. Note that this can only be allowed to happen if:

- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.

1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of vault names. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), then run `show` for each selected vault, and display the results of the `show` command for each vault that they've selected.
   - They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> Image
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/vault/show.rs#L33) you can look at to see where the `ockam vault show` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

### PR DESCRIPTION
**Pull request by abhiramtilakiiit**
## Current behavior

When a user runs `ockam vault show` without any arguments, currently they are shown an error if there are no vaults:

image

Or the default vault if there is a default one:

image

## Proposed changes

When running `ockam vault show` under the circumstances below:

- the NAME argument is NOT provided
- the ENCODING argument is NOT provided
- the --quiet flag is NOT provided
- the --no-input flag is NOT provided
- The terminal is interactive.

then, a tui like interface pops up, asking the user to select the vaults to be displayed, from a list.

If no such vault exists, it gives a message, and suggests the user to create a vault using the 
`ockam vault create` command. 

Also, if the user doesn't select anything from the tui, it again gives a message, and additionally tells the user
how to select in the interface.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@abhiramtilakiiit while we still have to review this change. I'm adding the `HACKTOBERFEST-ACCEPTED` label so the contribution is counted by hacktoberfest bots before the end of October. Thank you for taking time to contribute 🎉

**Comment by abhiramtilakiiit** [comment]
alright thanks vm.

**Review by adrianbenavides — COMMENTED** [review]
Hey @abhiramtilakiiit thanks for the PR! We have similar issues related to other show commands where we are using a different structure to handle the multiple use cases. My only request for now would be to adapt your PR to that structure (check the [`node show` command](https://github.com/build-trust/ockam/blob/692494fc61257b8690c0f897de9b47a8a0d69c4b/implementations/rust/ockam/ockam_command/src/node/show.rs#L52)).

In the specific case of this PR, there are some unhandled cases. Here's the script that I used to test it manually, which goes through all the possible cases:

```
ockam reset -y
ockam vault show        # should show the "no vaults" message
ockam vault create v1
ockam vault show        # should show the "v1" vault with no interaction, as there is only one vault
ockam vault show v1     # same as before
ockam vault create v2
ockam vault show        # should show the interactive list
                        #   - if no vault was selected, show the "no vaults selected" message
                        #   - if one vault was selected, show the detailed version (like `vault show v1`)
                        #   - if multiple were selected, show the list version (like `vault list`)
```


Let me know if you have any questions!

**Comment by abhiramtilakiiit** [comment]
Oh I didn't handle the case where there is only one available vault to show.
Also @adrianbenavides  when you say
> adapt your PR to the structure

are you referring to the return messages, or just the implementation.

**Comment by abhiramtilakiiit** [comment]
Is this alright, or should I add a separate function for naive show without list output like `print_query_status` in `node show`.

**Comment by adrianbenavides** [comment]
Hi @abhiramtilakiiit  ! Your PR will be landed through https://github.com/build-trust/ockam/pull/6890

Thank you so much for your help!

**Pull request closed without merging**
