### PR TITLE
prepare #3124

### PR DESCRIPTION
**Pull request by mrinalwadhwa**
prepare #3124

### CODE REVIEW

**Comment by pro465** [comment]
elixir? i don't even know elixir and somehow it failed 😕

**Comment by pro465** [comment]
```
{'HTTP/1.1', 503, 'Egress is over the account limit.'}
```

ok i don't know what this means, just wanted to share the error for quick finding

**Comment by mrinalwadhwa** [comment]
Elixir downloads a dependency from github and sometimes github isn't feeling up to it 🤷 
https://github.com/build-trust/ockam/runs/7694785154?check_suite_focus=true#step:6:88

**Comment by mrinalwadhwa** [comment]
@pro465 we can ignore that failure, it only happens once in a while.

**Pull request merged**
