### PR TITLE
feat(rust): added option to create identity using a vault

### LINKED ISSUE #3684: Add ockam sub command to create an identity without creating a node
Related to #3683 

# Currently

We create a file based vault when a node is created.

```
ockam node create n1
ockam identity show --node n1

cat ~/.config/ockam/vault.json
cat ~/.config/ockam/identity.json
```

The json file contains serialized vault and idenity data.

This is how a simple file based vault can be created and then used to manage identities etc.

https://github.com/build-trust/ockam/blob/4659eed3b84d339d9590f9dca71d64dd62c15b90/implementations/rust/ockam/ockam_api/src/nodes/service/vault.rs#L38-L39

https://github.com/build-trust/ockam/blob/01e90778abb6a1c53afc6dcb47feafecfc972c90/implementations/rust/ockam/ockam_api/src/nodes/service/identity.rs#L32-L33

# Desired

After #3683 is addressed.

We want decouple management for identities from nodes (when using ockam command)

```
ockam vault create v1
ockam identity create i1 --vault v1
```

should create a new file based vault and place the file for it in

```
CONFIG_DIR/vaults/v1/vault.json
```

and then create an identity and place the file for it in:

```
CONFIG_DIR/vaults/v1/i1.json
```

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by michealkeines**
# Added

Option to create an Identity using an existing vault

fixes [issue](https://github.com/build-trust/ockam/issues/3684) 

# Output

image

image

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa Please review, Thank you

**Comment by mrinalwadhwa** [comment]
@michealkeines This is a great start, thank you for spending time on this.

From what I can tell it doesn't currently create the identity in the vault. So that's something to add.

These sections of code might be helpful as a reference:

https://github.com/build-trust/ockam/blob/4659eed3b84d339d9590f9dca71d64dd62c15b90/implementations/rust/ockam/ockam_api/src/nodes/service/identity.rs#L32-L34

It needs a vault
https://github.com/build-trust/ockam/blob/8c4ebf495353e2b42058573801738d3f4bd96fe0/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L297-L307

**Comment by mrinalwadhwa** [comment]
Since today is the last day of `hacktoberfest`, I've add the `hacktoberfest-accepted` label in case you're participating. We can land the PR in once the above changes are addresses.

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa, I am not able to understand how vaults and identities are mapped, 

I am able to create an Identity using a vault and export the identity and store it in a file

but to store (persist) that identity key in the vault, i guess we have to call this store method `vault_fs.store(&identifier.key_id());`
could you please help me out here,

this is what i have written so far

```rust
            let vault_file = dir.join("vault.json");

            // FileStorage::create loads the vault from the path, if the path already exists
            let vault_fs = FileStorage::create(vault_file.clone()).await?;

            let vault = Vault::new(Some(Arc::new(vault_fs)));

            let identity_path = format!("{}.json", slugify(&format!("identity-{}", identity_name)));

            if dir.join(&identity_path).as_path().exists() {
                return Err(crate::error::Error::new(
                    CANTCREAT,
                    anyhow!("Identity with name {} already exists!", identity_name),
                ));
            }

            let file = dir.join(&identity_path);
            let mut identity_file = File::create(file.clone()).await?;
            
            let identity = Identity::create(&ctx, &vault).await?;

            let identifier = identity.identifier().clone();
            // vault_fs.store(&identifier.key_id().to_string());
           
            let exported_identity = identity.export().await?;
            let json_string = serde_json::to_string_pretty(&exported_identity)?;   
            
            // write the exported identity to the file
            identity_file.write_all(&json_string.as_bytes()).await?;
        
            println!("Identity {} created in vault {}", identity_name, vault_name);
```

**Comment by adrianbenavides** [comment]
Hi @michealkeines! I'm closing this PR as we did some big changes around this code. We implemented this feature on https://github.com/build-trust/ockam/pull/3854 

Thanks for your work on this PR!

**Pull request closed without merging**
