### PR TITLE
refactor(rust): restrict info shown on output of enroll command

### LINKED ISSUE #3393: Reduce the amount of information that we show at Project Creation
# Currently we see

```
» ockam enroll

Enroll Ockam Command's default identity with Ockam Orchestrator:
! First copy your one-time code:  CCZT-GFSF
> Then press enter to open https://account.ockam.io/activate in your browser...
> Opening: https://account.ockam.io/activate
> Tokens received, processing...

Space
  Id: a0f5c1d9-dad4-4f22-aa06-d5d2e9a5e8a4
  Name: 2024000c
  Users: ...

Establishing secure channel...
Project
  Id: 6ee618f3-77b8-4328-9517-28943bae8987
  Name: default
  Users:
  Services:
  Access route: /dnsaddr/a4e562a7c92894a86a7c6be95dacc107-57cfc2b5c9137176.elb.us-west-1.amazonaws.com/tcp/6252/service/api
  Identity identifier: P8d2b4d4fe9990e4ebe4c6270ce34801846cbd4406fb99a046cc6384521081024
  Authority access route: Some(CowStr("/dnsaddr/a4e562a7c92894a86a7c6be95dacc107-57cfc2b5c9137176.elb.us-west-1.amazonaws.com/tcp//service/api"))
  Authority identity: 011d66869dfcf7f0cbe05818495cc34a2bb2e315cc9bebf73641f4118769a141d4010000084f434b414d5f524b00030120000000000000002000e703224639e380b9d370a6a747dc929cb096f86da7c4916ae8bdc092475897034037f7679b8a4cfc7074b107378870721442019673333ee2305d3c34df7add7d74436e5f808f32e43daaddd1f2c71ee791232815f9da278aae8be6fff6fcf19f05b9154549a381303a93dd12a27e173d7f366f1597ca282dace84737fcfb3fa282010140068ba8d818bdd0689c777e339ee36ee569eaf8dc4f6d763fb97fb265f2e5345ceb95ad0b2ba8f02c79d4f6b1685630190d31230a58e5a59001ed8de62551e10c
```

# Desired

Under the Project information, we can remove Identity Identifier, Authority access route and Authority Identity.

```
» ockam enroll && bats implementations/rust/ockam/ockam_command/tests/commands.bats

Enroll Ockam Command's default identity with Ockam Orchestrator:
! First copy your one-time code:  CCZT-GFSF
> Then press enter to open https://account.ockam.io/activate in your browser...
> Opening: https://account.ockam.io/activate
> Tokens received, processing...

Space
  Id: a0f5c1d9-dad4-4f22-aa06-d5d2e9a5e8a4
  Name: 2024000c
  Users: ...

Establishing secure channel...

Project
  Id: 6ee618f3-77b8-4328-9517-28943bae8987
  Name: default
  Access route: /dnsaddr/a4e562a7c92894a86a7c6be95dacc107-57cfc2b5c9137176.elb.us-west-1.amazonaws.com/tcp/6252/service/api
  Identity identifier: P8d2b4d4fe9990e4ebe4c6270ce34801846cbd4406fb99a046cc6384521081024
```

The code for the project create is here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/create.rs

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by Abhicodes-crypto**
## Current Behavior
Closes #3393

## Proposed Changes
Removed `write!` macros 

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Review by adrianbenavides — CHANGES_REQUESTED** [review]
Hey @Abhicodes-crypto, thanks for submitting this PR!

Although your approach is correct, reading through the [issue description](https://github.com/build-trust/ockam/issues/3393) it looks to me that the fields that must be removed are: `Users`, `Services`,  `Authority access route` and `Authority identity`.

The `Identity identifier` should be kept.

**Comment by Abhicodes-crypto** [comment]
@adrianbenavides  Sorry about that. I've made the correct changes.

**Comment by adrianbenavides** [comment]
> @adrianbenavides Sorry about that. I've made the correct changes.

Nothing to be sorry about, we are here to help!

**Review by adrianbenavides — APPROVED** [review]
Looks great now, thanks @Abhicodes-crypto for your contribution :mechanical_arm:

**Pull request merged**
