### PR TITLE
fix(rust):replaced termimad with formatdoc & opts.terminal.stdout() in lease show

### LINKED ISSUE #6677: Build output of `lease show` implementing the `Output` trait instead of using `termimad`
## Current behavior

The [`lease show` command](https://github.com/build-trust/ockam/blob/da8e3a5e109ed2ed265cdbac05a9f9e890e21451/implementations/rust/ockam/ockam_command/src/lease/show.rs) uses `termimad` to format and print its output.

## Desired behavior

The command output should be formatted with `formatdoc` and printed with `opts.terminal.stdout()`.

## Implementation details

Since `Token` already implements the `Output` trait, you could write something like:

```rust
opts.terminal
    .stdout()
    .plain(&token)
    .json(serde_json::json!(&token))
    .write_line()?;
```

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

### PR DESCRIPTION
**Pull request by zacharyftw**
## Current behavior
The [lease show command](https://github.com/build-trust/ockam/blob/da8e3a5e109ed2ed265cdbac05a9f9e890e21451/implementations/rust/ockam/ockam_command/src/lease/show.rs) uses termimad to format and print its output.

## Proposed changes
 Termimad is replaced and the command output is formatted with formatdoc and printed with opts.terminal.stdout().

Fixes https://github.com/build-trust/ockam/issues/6677

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by zacharyftw** [comment]
@mrinalwadhwa is this PR ok? do i have to make any changes?

**Comment by adrianbenavides** [comment]
Hi @KekmaTime, thanks for submitting a PR! Looks good to merge, but we first need you to create a different PR accepting our CLA, as described below:

> I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

Once that's done, I'll merge your PR! 💪

**Comment by zacharyftw** [comment]
@adrianbenavides can this PR be merged?

**Review by adrianbenavides — APPROVED** [review]
LGTM! Thanks again @KekmaTime for your contribution 🙏

**Review by metaclips — APPROVED** [review]

**Pull request merged**
