### PR TITLE
Identity v2

### PR DESCRIPTION
**Pull request by SanjoDeundiak**
## Changes

1. Rewrite `Identity`:
    - New on-the-wire models
    - Renamings
    - New protocol design
    - Introduce `PurposeKey`s
    - All keys have creation and expiration timestamps
2. Rewrite `Vault`
    - Introduce `SigningVault`, `VerifyingVault` and `SecureChannelVault`
3. Rewrote `AWS` `Vault`:
    - Remove persistent state (fetches all keys on start)
    - Check for maximum number of keys (100)
    - Change formats from der to what we use
4. Change `Attributes` key type to binary
5. Change display formats for `Identity` models
6. FFI improvements
7. Please go over Commit messages

### NOTE
It also breaks backward compatibility:
1. Identity migration support is removed
2. `LEGACY_ID` is removed from the credential

### CODE REVIEW

**Comment by SanjoDeundiak** [comment]
Updated documentation is here https://github.com/build-trust/ockam-documentation/pull/57

**Comment by mrinalwadhwa** [comment]
@SanjoDeundiak Before we merge this branch let's squash the commit, otherwise we end up with really noisy changelogs. This PR is ~one logical change.

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa ok, next time, I won't waste time on isolated commits with proper descriptions :D

**Comment by mrinalwadhwa** [comment]
😁 we can keep everything you wrote in the description of the squashed commit

**Review by polvorin — APPROVED** [review]

**Pull request merged**
