### PR TITLE
feat(rust): derive `Default` for `Id` and `Error`

### PR DESCRIPTION
**Pull request by twittner**
To allow construction of responses and errors without having access to the request (e.g. because decoding it failed), this commit derives `Default` for `Id` and ensures that random Ids are never 0. It also makes the `path` in `Error` optional, so that an error response can be constructed without knowing the request path. This functionality should be used judiciously, e.g. only when request decoding failed, otherwise when the data is available it should be used.

### CODE REVIEW

**Comment by SanjoDeundiak** [comment]
@twittner If a client sent us something that is not a valid `Request`, unlikely that he expects `Response` in response. Thoughts?

**Comment by SanjoDeundiak** [comment]
PR itself is fine though

**Comment by twittner** [comment]
> If a client sent us something that is not a valid `Request`, unlikely that he expects `Response` in response. Thoughts?

Maybe. We do not know and I think it is still better to return a well-formed `Response` and keep our end of the API contract.

**Comment by SanjoDeundiak** [comment]
@mergifyio rebase

**Review by SanjoDeundiak — APPROVED** [review]

**Pull request merged**
