### PR TITLE
Resolves #3722: Format all bash scripts using shfmt

### LINKED ISSUE #3722: Format all bash scripts using `shfmt`
Bash scripts in our repositories currently fail [`shfmt`](https://github.com/mvdan/sh), we should properly format all script files. A working command is
```bash
shfmt -d ./**/*.sh | git apply
```
This should format all files automatically

### PR DESCRIPTION
**Pull request by Sparrow1029**
Signed-off-by: Sparrow1029 <19390913+Sparrow1029@users.noreply.github.com>
## Current Behavior

Bash scripts in our repositories currently fail [shfmt](https://github.com/mvdan/sh), we should properly format all script files.

## Proposed Changes
run
```bash
shfmt -d ./**/*.sh | git apply
```
to properly format shell scripts across the repository.
## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Review by metaclips — DISMISSED** [review]
Thanks @Sparrow1029 for an amazing PR.

**Comment by metaclips** [comment]
@Sparrow1029 can you update your commit message to `ci: run shfmt across all .sh scripts in repo` so that commit CI can pass.

**Comment by Sparrow1029** [comment]
@metaclips changed!

**Comment by metaclips** [comment]
Thanks @Sparrow1029 ! We need to change the commit message to 
ci: `run` shfmt across all .sh scripts in repo
CI doesn't allow Caps in commit message. We should merge right after the commit update.

**Comment by Sparrow1029** [comment]
Heh, sorry, should have recognized that! Should be set now @metaclips

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
@Sparrow1029 Thank you for an awesome first contribution 🥳

**Comment by Sparrow1029** [comment]
@mrinalwadhwa thanks! I look forward to contributing more on the Rust side of things

**Comment by mrinalwadhwa** [comment]
Awesome let us know if you have questions as you explore

**Pull request merged**
