### PR TITLE
ci: add global default shell to release-binaries workflow

### LINKED ISSUE #4004: Use global default shell in `release-binaries.yml` workflow
To remove the need to repeat default shell declaration in our workflow, we should set a global default so that it is available across all jobs in https://github.com/build-trust/ockam/blob/cdf925aa2adb4439061449e5ea5f9ad774833e20/.github/workflows/release-binaries.yml#L1 
More here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults

### PR DESCRIPTION
**Pull request by murex971**
Signed-off-by: murex971 <nupur202000@gmail.com>

Fixes : #4004 

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@murex971 have a look at how commit messages can be signed with GPG or SSH keys. In the previous PRs I signed them on your behalf but it would be better if you can sign them.
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

This is why this check is failing https://github.com/build-trust/ockam/actions/runs/4098791629/jobs/7068289870

**Comment by murex971** [comment]
@mrinalwadhwa  done

**Comment by murex971** [comment]
```
ci: add global default shell to release-binaries workflow
Signed-off-by: murex971 <nupur202000@gmail.com>
```

**Review by mrinalwadhwa — APPROVED** [review]
That looks great. Thank you

**Pull request merged**
