### PR TITLE
fix(rust): check tcp-outlet alias before delete

### LINKED ISSUE #6347: Improve `ockam tcp-outlet delete <ALIAS>` when `<ALIAS>` does not exist
# Current behavior

When a user runs `ockam tcp-outlet delete <ALIAS>` and `<ALIAS>` does not exist, then they get a prompt, asking them to confirm whether this command should proceed or not. Then they are shown an error stating that `404 NotFound`.

Image

# Desired behavior

Instead of asking the user for a confirmation prompt, it would be better to first check to see whether `<ALIAS>` even exists. 

1) If it does *not*, then the user should be notified that this alias name doesn't exist and can't be deleted. This can be an error.

2) If it does exist, then the user should be prompted, to confirm whether this destructive operation should proceed. If that operation fails for some reason then an error should be displayed with information on what went wrong (which is the current behavior).

# Implementation details

Take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs#L39) to get started.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

### PR DESCRIPTION
**Pull request by racnan**
fixes #6347 

## Current behavior

> When a user runs ockam tcp-outlet delete <ALIAS> and <ALIAS> does not exist, then they get a prompt, asking them to confirm whether this command should proceed or not. Then they are shown an error stating that 404 NotFound.

## Proposed changes

Checking if the alias exists before deleting.

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [X] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by adrianbenavides** [comment]
Sorry @racnan , but this issue was picked up already and solved at https://github.com/build-trust/ockam/pull/6305 a few days ago. I'll close this PR and add the `HACKTOBERFEST-ACCEPTED` label to give you credit 👍 

Make sure to check our other open issues, we have plenty of unassigned issues, and more coming in the next few days!

**Comment by racnan** [comment]
hey @adrianbenavides, PR you mentioned above fixes different issue. 😕

**Comment by adrianbenavides** [comment]
@racnan you are right, sorry about that! I'm reopening it 🙏 

Check out how the `it_exists` check is done at https://github.com/build-trust/ockam/pull/6370/files for reference and let me know if you have any questions 👍

**Comment by adrianbenavides** [comment]
Before we can merge your PR, we'll also need you to accept our CLA as described here:

> I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

**Comment by racnan** [comment]
@adrianbenavides thanks for reopening the PR.
About the [file ref](https://github.com/build-trust/ockam/pull/6370/files) you gave:
From what I've understood, `ask_and_get_reply` gives you a "decodable response or an API error" which I guess is not required here since we are not using any data from the API, we just want to propagate error (if any) or else just proceed.
Hence, I've used `tell`.

**Comment by adrianbenavides** [comment]
> @adrianbenavides thanks for reopening the PR. About the [file ref](https://github.com/build-trust/ockam/pull/6370/files) you gave: From what I've understood, `ask_and_get_reply` gives you a "decodable response or an API error" which I guess is not required here since we are not using any data from the API, we just want to propagate error (if any) or else just proceed. Hence, I've used `tell`.

The problem is that `tell` is just sending a request and doesn't care about its result, so you can't tell whether the requested outlet exists or not, only that the node received the request.

If you look closely at the example I referenced, we call the `found()` method on the request's reply to make sure the requested resource was found.

Does that make sense?

**Comment by adrianbenavides** [comment]
Looks like we fixed #6347 through https://github.com/build-trust/ockam/pull/6453.

Thanks for the time you spent on this one! 🙏

**Pull request closed without merging**
