### PR TITLE
fixes#4522 Added pre-installed version of commit lint in ockam-builder docker image

### LINKED ISSUE #4522: Use pre-installed version of commit lint in `ockam-builder` docker image
### Current behavior

To lint commit, we currently install commit-lint for every lint_commit job run which increases time for CI test to complete https://github.com/build-trust/ockam/blob/1b7d42a3e870e4bdef20fff7e3ead302edfb1d6b/.github/workflows/all.yml#L90-L91 

### Desired behavior

We now have commit-lint pre-installed into our [builder image](https://github.com/build-trust/ockam-artifacts/pkgs/container/ockam-builder) https://github.com/build-trust/ockam/blob/1b7d42a3e870e4bdef20fff7e3ead302edfb1d6b/tools/docker/builder/Dockerfile#L80-L81
we should use our builder image as our default image in the `lint_commits job`.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### PR DESCRIPTION
**Pull request by Salonikansal2**
added pre-installed version of commit lint in ockam-builder docker image #452
@nazmulidris 
@metaclips

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@Salonikansal2 while we still have to review this change. I'm adding the `HACKTOBERFEST-ACCEPTED` label so the contribution is counted by hacktoberfest bots before the end of October. Thank you for taking time to contribute 🎉

**Comment by Salonikansal2** [comment]
Thanks for your efforts @mrinalwadhwa

**Comment by Salonikansal2** [comment]
gentle reminder to review changes 
@metaclips 
@adrianbenavides

**Review by metaclips — APPROVED** [review]
Thanks @Salonikansal2 for working on this issue and apologies for the late reply. I amended the Dockerfile to indicate to where commitlint was installed

**Review by mrinalwadhwa — APPROVED** [review]

**Pull request merged**
