### PR TITLE
Refactored get_node_port so it returns a Result

### LINKED ISSUE #3555: Refactor `get_node_port` so it returns a Result
Function: https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/util/config.rs#L118

## Current

The `get_node_port` is calling the `std::process::exit` function when there is an error.

## Desired

We want to refactor this method so it returns an `anyhow::Result` instead of using `std::process::exit`.

For now, it doesn't matter if the callers of `get_node_port` must `unwrap` that result. This is something we will address in future issues.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by gybrish**
Fixes #3555 

## Current Behavior

The `get_node_port` is calling the `std::process::exit` function when there is an error.

## Proposed Changes

We want to refactor this method so it returns an `anyhow::Result` instead of using `std::process::exit`.

For now, it doesn't matter if the callers of `get_node_port` must unwrap that result. This is something we will address in future issues.

## Checks

- [*] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [*] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [*] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [*] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@gybrish Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

**Comment by gybrish** [comment]
Ah apologies, missed that step, done.

**Comment by mrinalwadhwa** [comment]
No worries at all.

It doesn't look like a PR was created on the contributors repo https://github.com/build-trust/ockam-contributors/pulls

Could you double check please.

**Review by adrianbenavides — COMMENTED** [review]
It looks great @gybrish! We can merge it as soon as you get the `build-trust/ockam-contributors` PR ready :rocket:

**Comment by gybrish** [comment]
The PR should be in now, please let me know if there's any issues.

Thanks!

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
@gybrish thank you for an awesome first contribution 🥳 🎈 

Preparing for a merge in #3585

**Comment by mrinalwadhwa** [comment]
Merged https://github.com/build-trust/ockam/pull/3585

**Pull request closed without merging**
