### PR TITLE
refactor(rust): Refactor tcp inlet create command 

### PR DESCRIPTION
**Pull request by Abhicodes-crypto**
## Current Behavior
Currently the tcp inlet create command is mapping errors manually using std::process::exit. 
#3596

## Proposed Changes
As discussed here, made the required changes and the  `create an inlet/outlet pair and move tcp traffic through it`, `create an inlet/outlet pair with relay through a forwarder and move tcp traffic through it` bats test pass. #3596

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Review by adrianbenavides — DISMISSED** [review]
Looks awesome, thanks @Abhicodes-crypto! :partying_face: 

I've created a follow-up issue, in case you are interested: https://github.com/build-trust/ockam/issues/3742

**Comment by adrianbenavides** [comment]
@Abhicodes-crypto can you add a new PR to https://github.com/build-trust/ockam-contributors adding yourself to the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file?

**Comment by Abhicodes-crypto** [comment]
@adrianbenavides I've already raised a PR here. https://github.com/build-trust/ockam-contributors/pull/145

**Comment by mrinalwadhwa** [comment]
@Abhicodes-crypto Thank you for an awesome first contribution!
Preparing to land this is #3751

**Pull request closed without merging**
