### PR TITLE
Parse ChangeHistory command-line arguments

### PR DESCRIPTION
**Pull request by Nathy-bajo**
## Current behavior

Currently, the ockam_command has multiple places where Identity change history is accepted as a hex-encoded string. This approach lacks type safety and does not validate or decode the input into a structured format.

## Proposed changes

Introduced a new crate, ockam_common, which includes the ValueParser struct.

ValueParser is designed to validate and decode hex-encoded strings into structured data representing Identity change history.

Implemented a ChangeHistoryParser which utilizes the ValueParser for argument parsing in CLI commands. This ensures that the inputs are validated and decoded properly before being used.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by etorreborre** [comment]
Hi @Nathy-bajo I am going to review the PR today. In the meantime can you please have a look at the list of checks in the PR description? In particular you need to format your commits and open a separate PR to be added to the contributors file. Thanks.

**Comment by Nathy-bajo** [comment]
> Hi @Nathy-bajo I am going to review the PR today. In the meantime can you please have a look at the list of checks in the PR description? In particular you need to format your commits and open a separate PR to be added to the contributors file. Thanks.

Alright, I will do just that.

**Comment by Nathy-bajo** [comment]
@etorreborre Sorry for the delay I'm still adjusting to the features that come with using GitHub so it was a bit confusing setting it up and I was having network issues.

**Comment by Nathy-bajo** [comment]
@etorreborre Please can you review this PR

**Comment by etorreborre** [comment]
Hi @Nathy-bajo, I think we can do something simple by leveraging some existing code without a new crate. 
For example, for the `authority_identity` field we can declare:
```rust
#[arg(long, value_name = "ACCOUNT_AUTHORITY_CHANGE_HISTORY", default_value = None, value_parser = ChangeHistory::import_from_string)]
    account_authority: Option<ChangeHistory>,
``` 

A bit of massaging for error types could be necessary but otherwise this should work.

**Comment by Nathy-bajo** [comment]
> Hi @Nathy-bajo, I think we can do something simple by leveraging some existing code without a new crate. For example, for the `authority_identity` field we can declare:
> 
> ```rust
> #[arg(long, value_name = "ACCOUNT_AUTHORITY_CHANGE_HISTORY", default_value = None, value_parser = ChangeHistory::import_from_string)]
>     account_authority: Option<ChangeHistory>,
> ```
> 
> A bit of massaging for error types could be necessary but otherwise this should work.

Hello @etorreborre 😄 
I have updated the code as you requested.

**Comment by etorreborre** [comment]
Hi @Nathy-bajo, that looks good, can you please rebase to fix the conflict?

**Comment by Nathy-bajo** [comment]
> Hi @Nathy-bajo, that looks good, can you please rebase to fix the conflict?

I have rebased it.
Please can you confirm?

**Comment by etorreborre** [comment]
Hi @Nathy-bajo. We don't accept merge commits on our branches, only rebasing.
Can you please have a look at the CI job results, I see several issues which shouldn't be too hard too fix:

 - With your commit message. It should be something like `feat(rust): ...`
 - With some unused imports.
 - With code formatting.

**Comment by Nathy-bajo** [comment]
Hello @etorreborre. Hope you're having a good day😄
I have fixed the issues. Is there anything else I need to do?

**Comment by etorreborre** [comment]
@Nathy-bajo can you please have a look at the failed jobs? For example you will have to get rid of the merge commit [0c026b8](https://github.com/build-trust/ockam/pull/8365/commits/0c026b86050c854042479839c13fd57f92028a93) (one way to do this is to recreate your branch entirely and force-push it).

**Comment by Nathy-bajo** [comment]
> @Nathy-bajo can you please have a look at the failed jobs? For example you will have to get rid of the merge commit [0c026b8](https://github.com/build-trust/ockam/pull/8365/commits/0c026b86050c854042479839c13fd57f92028a93) (one way to do this is to recreate your branch entirely and force-push it).

Hello @etorreborre 
I have removed unused imports as requested in the failed jobs and formatted the code. I have also created a new branch and force-pushed it.

**Comment by Nathy-bajo** [comment]
Hello @etorreborre 
I have tried using `git reset --soft HEAD~4` to move HEAD back to the point just before the merge commit, then rebased it and force-pushed it because the job failing is still coming from the merge commit.

**Comment by etorreborre** [comment]
Let me try to fix this PR.

**Review by etorreborre — APPROVED** [review]

**Comment by etorreborre** [comment]
@Nathy-bajo we're getting there!

**Comment by Nathy-bajo** [comment]
> @Nathy-bajo we're getting there!

Hello @etorreborre 😄
Nice work! I was even thinking of creating a new PR if this did not work.
Thank you.

**Review by davide-baldo — APPROVED** [review]

**Pull request merged**
