### PR TITLE
Refactor identity secure channel

### PR DESCRIPTION
**Pull request by davidag**
## Current Behavior

NA

## Proposed Changes

Refactors modules into correct directory and file structure, as suggested in https://github.com/build-trust/ockam/issues/3650

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Review by hairyhum — CHANGES_REQUESTED** [review]
Can you also add a rename of `Ockam.Identity.SecureChannel.IdentityChannelMessage` to `Ockam.Identity.SecureChannel.HandshakeMessage`

**Comment by davidag** [comment]
> Can you also add a rename of `Ockam.Identity.SecureChannel.IdentityChannelMessage` to `Ockam.Identity.SecureChannel.HandshakeMessage`

Thanks for noticing, I missed it.

**Comment by hairyhum** [comment]
Looks good.
@davidag can you please rebase and resolve conflicts if something was changed in the `identity_channel.ex`?
Also make sure that all commits are signed.

**Comment by davidag** [comment]
> Looks good. @davidag can you please rebase and resolve conflicts if something was changed in the `identity_channel.ex`? Also make sure that all commits are signed.

Rebased, there were no conflicts thanks to the renaming commit. The new `idle_timeout` option for workers is there 👌🏼

**Review by hairyhum — DISMISSED** [review]

**Comment by hairyhum** [comment]
@davidag can you also squash your commits, make sure the resulting commit follows the [format](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages) and make sure that it's signed by a signature verified by github?

**Comment by davidag** [comment]
@hairyhum commits squashed and signed. I'd say the commit format follows the guidelines, but let me know otherwise. Thanks.

**Comment by hairyhum** [comment]
https://github.com/Mergifyio rebase

**Comment by hairyhum** [comment]
Merged in https://github.com/build-trust/ockam/pull/3813

**Pull request closed without merging**
