### PR TITLE
chore: update cla markdown file

### PR DESCRIPTION
**Pull request by metaclips**
Update the markdown file

### CODE REVIEW

**Review by nazmulidris — APPROVED** [review]
LGTM

**Comment by mrinalwadhwa** [comment]
Let's make this commit message better, it doesn't describe the change in this commit.
[chore: update cla markdown file](https://github.com/build-trust/ockam/pull/6127/commits/99dd55fe292770c9e5d9467bff0f1d3c72dc455d)

**Comment by metaclips** [comment]
> Let's make this commit message better, it doesn't describe the change in this commit. [chore: update cla markdown file](https://github.com/build-trust/ockam/pull/6127/commits/99dd55fe292770c9e5d9467bff0f1d3c72dc455d)

@mrinalwadhwa updated

**Review by nazmulidris — APPROVED** [review]
LGTM

**Pull request merged**
