### PR TITLE
docs(rust): update value_name on issuer arg in credential store

### LINKED ISSUE #6250: `issuer` argument value name on `ockam credential store` should be `HEX_ENCODED_FULL_IDENTITY`
## Current behavior

The `issuer` argument value name on `ockam credential store` is not set.

## Desired behavior

The `issuer` argument value name on `ockam credential store` should be `HEX_ENCODED_FULL_IDENTITY` and a doc string should be added 
with the contents `The full hex-encoded Identity that was used to issue the credential`.

## Implementation details

This is the argument that must be changed:

https://github.com/build-trust/ockam/blob/c0db0ce89a69991a46b3872a5464c1ff9da15432/implementations/rust/ockam/ockam_command/src/credential/store.rs#L20-L21

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

### PR DESCRIPTION
**Pull request by brehen**
## Current behavior

This fixes #6250, which asked for adding a value_name to the arguement "issuer" on the credential store in the rust implementation.

## Proposed changes

Fix #6250 by adding value_name and a docstring.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by adrianbenavides** [comment]
Thanks @brehen for submitting the PR 🙏  It looks good, but we need you to accept our CLA before we can merge your PR. These are the instructions:

> I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

**Comment by brehen** [comment]
Think I've been added to the CLA now, how do I get this PR approved and merged? 😄

**Comment by brehen** [comment]
@adrianbenavides I've been added to the CLA now :-)

**Review by adrianbenavides — APPROVED** [review]
Nice, thanks @brehen 🙏

**Pull request merged**
