### PR TITLE
Renamed Ockam Hub to Ockam Orchestrator

### PR DESCRIPTION
**Pull request by postmeback**
## Current behavior

Renamed Ockam Hub to Ockam Orchestrator

## Proposed changes

Renamed Ockam Hub to Ockam Orchestrator

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by SanjoDeundiak** [comment]
Hey @postmeback , thanks for contributing! Could you please edit your commit message to follow our [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages)
Also, I think there are few more mentions of Hub in the codebase, would you like to fix them as well? (Search for "hub" case-insensitive)

**Comment by postmeback** [comment]
Hi @SanjoDeundiak 

I tried to search with `Ockam Hub` & `Ockam hub`, but no search result came up.

image

image



Am I missing anything ?

**Comment by SanjoDeundiak** [comment]
Hey @postmeback , I think we had a race condition here. I think [this issue](https://github.com/build-trust/ockam/issues/4520) is taken by @PsychoPunkSage and there is already a [PR in progress](https://github.com/build-trust/ockam/pull/8265)

**Comment by postmeback** [comment]
Shall i delete my PR ?

What do you suggest ? @SanjoDeundiak

**Comment by SanjoDeundiak** [comment]
Sorry, we should close it. There are more issues if you would like to contribute again 🙂

**Pull request closed without merging**
