### PR TITLE
fix(rust): tcp-connection/listener show only connections/listeners

### LINKED ISSUE #3145: Show only connections in output of `ockam tcp-connection list`
Currently:

```
> ockam node create n1 --api-address "127.0.0.1:6001"
> ockam node create n2 --api-address "127.0.0.1:6002"
> ockam tcp-listener create "127.0.0.1:7001" --node n2
> ockam tcp-connection create "127.0.0.1:7001" --node n1

> ockam tcp-connection list --node n1
+----------------------------------+----------------+-------------------+----------------+
| Transport ID                     | Transport Type | Mode              | Address bind   |
+----------------------------------+----------------+-------------------+----------------+
| 4e45dcc06f776a851ef2b589b230aa30 | TCP            | Listening         | 127.0.0.1:6001 |
+----------------------------------+----------------+-------------------+----------------+
| 65c51c27d5bde0f2274d642f3e1e06a6 | TCP            | Remote connection | 127.0.0.1:7001 |
+----------------------------------+----------------+-------------------+----------------+
```

We want to change it to:

```
> ockam tcp-connection list --node n1
+----------------------------------+----------------+
| Transport ID                     | Connected To   |
+----------------------------------+----------------+
| 65c51c27d5bde0f2274d642f3e1e06a6 | 127.0.0.1:7001 |
+----------------------------------+----------------+
```

Listeners should not be shown.

The code for this is here: https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/connection/list.rs

### LINKED ISSUE #3146: Show only listeners in output of `ockam tcp-listener list ...`
Currently:

```
> ockam node create n1 --api-address "127.0.0.1:6001"
> ockam node create n2 --api-address "127.0.0.1:6002"
> ockam tcp-listener create "127.0.0.1:7001" --node n2
> ockam tcp-connection create "127.0.0.1:7001" --node n1

» ockam tcp-listener list --node n1
+----------------------------------+----------------+-------------------+----------------+
| Transport ID                     | Transport Type | Mode              | Address bind   |
+----------------------------------+----------------+-------------------+----------------+
| 4e45dcc06f776a851ef2b589b230aa30 | TCP            | Listening         | 127.0.0.1:6001 |
+----------------------------------+----------------+-------------------+----------------+
| 65c51c27d5bde0f2274d642f3e1e06a6 | TCP            | Remote connection | 127.0.0.1:7001 |
+----------------------------------+----------------+-------------------+----------------+
```

We want to change it to:

```
> ockam tcp-listener list --node n1
+----------------------------------+----------------+
| Transport ID                     | Listening On   |
+----------------------------------+----------------+
| 4e45dcc06f776a851ef2b589b230aa30 | 127.0.0.1:6001 |
+----------------------------------+----------------+
```

Connections should not be shown.

The code for this is here: https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/listener/list.rs

Related #3145

### PR DESCRIPTION
**Pull request by lameferret**
Fix #3145 
Fix #3146 

IMO, this should work but it doesn't. 

Here is how I think `ockam tcp-connection list --node n1` works
1. Calls `list_connections`
2. `api::list_tcp_connections()` create a RequestBuilder and pass it to context which call the executioner
    ```
    RequestBuilder { header: Request { id: Id(2379971879), 
    path: "/node/tcp/connection", method: Some(Get), 
    has_body: false }, body: None }
    ```
3. `ockam_api::service::handle_request` matches req type(GET) and path ("node/tcp/connection").
4. `self.get_tcp_con_or_list(req)` matches on `TransportMode`
    ```rust
    pub(super) fn get_tcp_con_or_list(
        &self,
        req: &Request<'_>,
    ) -> ResponseBuilder<TransportList<'_>> {
        Response::ok(req.id()).body(TransportList::new(
            self.transports
                .iter()
                .map(|(tid, (tt, tm, addr))| match tm {
                    TransportMode::Listen => TransportStatus::new(*tt, *tm, addr, tid),
                    TransportMode::Connect => TransportStatus::new(*tt, *tm, addr, tid),
                })
                .collect(),
        ))
    }
    ```
6. Some other stuff happens, and the result is passed back to the original `send_and_receive` call, which returns a vec in binary.
7. Which is further parsed and prints the output
Which is wrong
tcptransportoutput

Issue can probably with 4's match. 
Some help would be great thanks

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@anuvratsingh thanks for starting this. I'll try it our in a bit.
@adrianbenavides / @SanjoDeundiak / @spacekookie may be able to help / advise.

**Comment by mrinalwadhwa** [comment]
@anuvratsingh you had it almost working ... the missing piece was this filter
https://github.com/build-trust/ockam/blob/3f4cadddc89fc44dcd58715b0b3695e9f97ffa47/implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs#L19

I'll merge this PR soon, in a follow on PR we can tackle the empty tables that are displayed if there is no result to show.

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
Thank you @anuvratsingh for another amazing contribution 🥳

**Comment by lameferret** [comment]
Thanks for your kind words @mrinalwadhwa, but I can't remember how in my head this made any sense:
```
Response::ok(req.id()).body(TransportList::new(
        self.transports
            .iter()
            .map(|(tid, (tt, tm, addr))| match tm {
                TransportMode::Listen => TransportStatus::new(*tt, *tm, addr, tid),
                TransportMode::Connect => TransportStatus::new(*tt, *tm, addr, tid),
            })
            .collect(),
    ))
```
I was trying `filter_map` probably forgot to compile and ended up with this gibberish.

**Pull request merged**
