### PR TITLE
Update CONTRIBUTORS.csv (accept Ockam Agreement)

### PR DESCRIPTION
**Pull request by pradovic**
Accept Ockam Agreement.

### CODE REVIEW

**Comment by adrianbenavides** [comment]
Hey @pradovic ! Can you resolve the conflict with the contributors file please?

Also, can you change the commit message to: `chore: accept cla`? That way it will pass the lint CI check.

Thanks!

**Comment by pradovic** [comment]
> Hey @pradovic ! Can you resolve the conflict with the contributors file please?
> 
> Also, can you change the commit message to: `chore: accept cla`? That way it will pass the lint CI check.
> 
> Thanks!

Thanks! I think it should be good now!

**Comment by etorreborre** [comment]
Hi @pradovic, there are still 2 issues:

 1. a newline is missing at the end of the file
```
.github/CONTRIBUTORS.csv:
356:53: the final newline is missing
yes,pradovic,Petar Radovic,<petar.radovic@gmail.com
```

 2. your commit needs to be signed (was it signed the first time and not now?)

**Comment by pradovic** [comment]
> Hi @pradovic, there are still 2 issues:
> 
> 1. a newline is missing at the end of the file
> 
> ```
> .github/CONTRIBUTORS.csv:
> 356:53: the final newline is missing
> yes,pradovic,Petar Radovic,<petar.radovic@gmail.com
> ```
> 
> 2. your commit needs to be signed (was it signed the first time and not now?)

Ah, sorry about that 🙈  I forgot about the signing, should be fixed now!

**Comment by etorreborre** [comment]
We're getting there but Github says that your key hasn't been uploaded yet 
image

**Comment by pradovic** [comment]
> We're getting there but Github says that your key hasn't been uploaded yet image

Hm, refresh? :) It is showing verified status to me? Maybe it is lagging a bit. It is showing me a verified checkmark:
image

**Review by etorreborre — APPROVED** [review]
Yay, a refresh did it! 

Thank you for accepting the CLA and taking time to contribute!!
Welcome to the Ockam Community 🥳 

If you have questions, as you explore, join us on the contributors discord channel https://discord.gg/bewvnm6zqS

**Comment by pradovic** [comment]
> Yay, a refresh did it!
> 
> Thank you for accepting the CLA and taking time to contribute!! Welcome to the Ockam Community 🥳
> 
> If you have questions, as you explore, join us on the contributors discord channel https://discord.gg/bewvnm6zqS

Thanks!

**Pull request merged**
