### PR TITLE
test: reorganize bats tests to run them in parallel

### PR DESCRIPTION
**Pull request by adrianbenavides**
This won't take effect until we change [the bats tests CI action](https://github.com/build-trust/.github/blob/custom-actions/actions/run_bats_test/action.yml).

## Execution times

With the old single-file bats:
- `ORCHESTRATOR_TESTS=1 bats ./commands.bats`: 1m 51s

With the new organization
- `ORCHESTRATOR_TESTS=1 bats ./bats`: 1m 40s
- `ORCHESTRATOR_TESTS=1 bats ./bats -j 6`: 25s

## Other changes

- The project's forwarders are parameterized so there are no tests trying to create two forwarders with the same name. The rest of the inputs are fixed (nodes/identities names, forwarders to temporary local nodes, ...)
- There are also other optimizations (e.g. we only fetch the project.json once, instead of on every orchestrator test).

### CODE REVIEW

**Comment by metaclips** [comment]
@adrianbenavides GNU parallel is not installed by default in GitHub CI default package https://github.com/build-trust/ockam/actions/runs/4176053292/jobs/7231825188#step:7:8. I'll only run bats tests in parallel for `Orchestrator` tests.

**Comment by adrianbenavides** [comment]
> @adrianbenavides GNU parallel is not installed by default in GitHub CI default package https://github.com/build-trust/ockam/actions/runs/4176053292/jobs/7231825188#step:7:8. I'll only run bats tests in parallel for Orchestrator tests.

The parallelization has the most impact on orchestrator tests anyway, so it makes sense to me. Unit tests are fast to run sequentially.

**Comment by metaclips** [comment]
@adrianbenavides bats test blocks on bash terminal  (doesn't on zsh, I wonder why). CI also blocks due to this hang https://github.com/build-trust/ockam/actions/runs/4183597388/jobs/7248152827.

It seems like the tests run `ok 32 portals - create an inlet/outlet pair with relay through a forwarder and move tcp traffic through it` but fails to exit (even when we ctrl-c).

```bash
$ docker run -e HOST_USER_ID=$(id -u) --volume $(pwd):/work -it --rm ghcr.io/build-trust/ockam-builder:latest bash
$ cargo build --bin ockam
$ export PATH=$(pwd)/target/debug:$PATH
$ bats implementations/rust/ockam/ockam_command/tests/bats
```

**Comment by adrianbenavides** [comment]
Fixed! It looks like the [python server wasn't shut down](https://github.com/build-trust/ockam/compare/27da5ea7175433f24b7f8dfac506b6ae9d63695f..4d2f3917f48a0cd5103f7618a7ddc0a80d4b84e3) in the teardown stage.

I've tried locally both directly and through docker and it didn't hang.

**Comment by metaclips** [comment]
I get the below error when I run on `commit f2f3e8d7a5dcd9675bbc9e2adddeb58d809049e3`
```bash
$ ockam reset -y
$ bats implementations/rust/ockam/ockam_command/tests/bats
```

```
$ bats implementations/rust/ockam/ockam_command/tests/bats
message.bats
 ✗ setup_file failed
   (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
    from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/message.bats, line 8)
     `setup_python_server' failed
   /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
portals.bats
 ✗ setup_file failed
   (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
    from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/portals.bats, line 8)
     `setup_python_server' failed
   /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
projects.bats
 ✗ setup_file failed
   (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
    from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/projects.bats, line 8)
     `setup_python_server' failed
   /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
spaces.bats
 ✗ setup_file failed
   (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
    from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/spaces.bats, line 8)
     `setup_python_server' failed
   /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
unit.bats
 ✗ setup_file failed
   (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
    from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/unit.bats, line 7)
     `setup_python_server' failed
   /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
use-cases.bats
 ✗ setup_file failed
   (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
    from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/use-cases.bats, line 10)
     `setup_python_server' failed
   /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
   bats warning: Executed 6 instead of expected 35 tests

35 tests, 6 failures, 29 not run
```

**Comment by metaclips** [comment]
> I get the below error when I run on `commit f2f3e8d7a5dcd9675bbc9e2adddeb58d809049e3`
> 
> ```shell
> $ ockam reset -y
> $ bats implementations/rust/ockam/ockam_command/tests/bats
> ```
> 
> ```
> $ bats implementations/rust/ockam/ockam_command/tests/bats
> message.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/message.bats, line 8)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> portals.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/portals.bats, line 8)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> projects.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/projects.bats, line 8)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> spaces.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/spaces.bats, line 8)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> unit.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/unit.bats, line 7)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> use-cases.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/use-cases.bats, line 10)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
>    bats warning: Executed 6 instead of expected 35 tests
> 
> 35 tests, 6 failures, 29 not run
> ```

Ignore. Was using an old commit, apologies.

**Comment by metaclips** [comment]
> I get the below error when I run on `commit f2f3e8d7a5dcd9675bbc9e2adddeb58d809049e3`
> 
> ```shell
> $ ockam reset -y
> $ bats implementations/rust/ockam/ockam_command/tests/bats
> ```
> 
> ```
> $ bats implementations/rust/ockam/ockam_command/tests/bats
> message.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/message.bats, line 8)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> portals.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/portals.bats, line 8)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> projects.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/projects.bats, line 8)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> spaces.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/spaces.bats, line 8)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> unit.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/unit.bats, line 7)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
> use-cases.bats
>  ✗ setup_file failed
>    (from function `setup_python_server' in file implementations/rust/ockam/ockam_command/tests/bats/load/base.bash, line 20,
>     from function `setup_file' in test file implementations/rust/ockam/ockam_command/tests/bats/use-cases.bats, line 10)
>      `setup_python_server' failed
>    /work/implementations/rust/ockam/ockam_command/tests/bats/load/base.bash: line 20: /root/.ockam/http_server.pid: No such file or directory
>    bats warning: Executed 6 instead of expected 35 tests
> 
> 35 tests, 6 failures, 29 not run
> ```

@adrianbenavides I just pushed a fix and updated CI. Lets see what CI says.......

**Comment by polvorin** [comment]
I'm not sure how I feel about all the helpers functions needed,  like `(create_random_node)`  etc.  
Previously it was basically possible to copy-paste an individual test and run it as a script (just removing the `RUN`  keyword and  `asserts`),    now it will need all the boilerplate code to be around.   It makes the test significantly harder to follow  (sometimes when asking  "how to do X",    I linked to the relevant bats test to use as guide).

Have doubts about how stable the tests will be too..  as when talking with orchestrator the user is the _same_   so if a test creates a project,   it will be visible on other'  test  `project list`,     if two tests try to create a project,   it likely will hit the limits,  etc.   
How much do we gain for doing it in parallel?   my experience is that the biggest chunk of the time is spend on just one tests, that need to create a project on orchestrator,   so even if we parallelized everything,  I think in terms of total _time_   it won't make a super big difference.

**Comment by adrianbenavides** [comment]
> I'm not sure how I feel about all the helpers functions needed, like (create_random_node) etc.

This is just an attempt to parameterize the tests so we make sure that one test data doesn't leak into another (as has been the case).

We could find an intermediate way of writing them, like removing the `create_X` helpers. But I don't think having the same hardcoded values for every test is good either.

> Have doubts about how stable the tests will be too.. as when talking with orchestrator the user is the same so if a test creates a project, it will be visible on other' test project list, if two tests try to create a project, it likely will hit the limits, etc.

We can write those kind of tests so they are dependent, or run them from the same $OCKAM_HOME, or run them serially.

> How much do we gain for doing it in parallel?

From `1m 50s` down to `~22s`.

**Comment by polvorin** [comment]
This is usually how I run the tests:
```
pablo@t14:~/src/ockam$  BATS_LIB=/home/pablo/src/ockam-cloud/integration-test/test_helper OCKAM=/home/pablo/src/ockam/ockam-local.sh LONG_TESTS=1 ORCHESTRATOR_TESTS=1 /home/pablo/src/ockam-cloud/integration-test/bats/bin/bats  /home/pablo/src/ockam/implementations/rust/ockam/ockam_command/tests/commands.bats
 ✓ create a node without a name
 ✓ node is restarted with default services
 ✓ create a vault and do show on it
 ✓ create a identity and do show on it
 ✓ create a identity and do show change history on it
 ✓ create a node with a name and do show on it
[...]
```

trying on the new directory gives me this error,  what I'm missing?
```
pablo@t14:~/src/ockam$ BATS_LIB=/home/pablo/src/ockam-cloud/integration-test/test_helper OCKAM=/home/pablo/src/ockam/ockam-local.sh LONG_TESTS=1 ORCHESTRATOR_TESTS=1 /home/pablo/src/ockam-cloud/integration-test/bats/bin/bats  /home/pablo/src/ockam/implementations/rust/ockam/ockam_command/tests/bats
 ✗ setup_suite
/home/pablo/src/ockam/implementations/rust/ockam/ockam_command/tests/bats/setup_suite.bash: line 9: load: command not found
/home/pablo/src/ockam/implementations/rust/ockam/ockam_command/tests/bats/setup_suite.bash: line 10: teardown_python_server: command not found
   (from function `setup_suite' in test file implementations/rust/ockam/ockam_command/tests/bats/setup_suite.bash, line 4)
     `load load/base.bash' failed with status 127
   bats warning: Executed 1 instead of expected 35 tests

35 tests, 1 failure, 34 not run
```

**Comment by adrianbenavides** [comment]
~@polvorin looks like a problem with relative paths to load the setup files. I'll try to find a solution to not force cd'ing into the tests directory.~

Update: this doesn't seem to be the problem. I was able to run it from any directory.

**Comment by adrianbenavides** [comment]
Actually, it fails to run the `load` command... could it be because the `bats` binary is not accessible from your `$PATH`?

**Comment by mrinalwadhwa** [comment]
I haven't dug into the code so not sure what the problem is but all the orchestrator tests seem to be failing for me on this branch. 

```
» ORCHESTRATOR_TESTS=1 LONG_TESTS=1 bats implementations/rust/ockam/ockam_command/tests/bats
authority.bats
 ✓ authority - standalone authority, enrollers, members
message.bats
 ✗ message - send a message to a project node command embedded node
   (from function `assert_success' in file /opt/homebrew/lib/bats-assert/src/assert.bash, line 114,
    in test file implementations/rust/ockam/ockam_command/tests/bats/message.bats, line 29)
     `assert_success' failed

   -- command failed --
   status : 70
   output :
   --

 ✗ message - send a message to a project node from a background node
   (from function `assert_success' in file /opt/homebrew/lib/bats-assert/src/assert.bash, line 114,
    in test file implementations/rust/ockam/ockam_command/tests/bats/message.bats, line 39)
     `assert_success' failed

   -- command failed --
   status : 70
   output :
   --

 ✗ send a message to a project node from an embedded node, passing identity
   (from function `assert_success' in file /opt/homebrew/lib/bats-assert/src/assert.bash, line 114,
    in test file implementations/rust/ockam/ockam_command/tests/bats/message.bats, line 45)
     `assert_success' failed

   -- command failed --
   status : 70
   output :
   --

portals.bats
 ✗ portals - create an inlet/outlet pair with relay through a forwarder in an orchestrator project and move tcp traffic through it
   (in test file implementations/rust/ockam/ockam_command/tests/bats/portals.bats, line 34)
     `$OCKAM forwarder create "$fwd" --at /project/default --to /node/blue' failed with status 70
   /service/outlet
   Version 0.80.0, hash: a1367541da9826f248a682baeed0b18936e63e87
   The request timed out, please make sure the command's arguments are correct or try again
 ✗ portals - create an inlet (with implicit secure channel creation) / outlet pair with relay through a forwarder in an orchestrator project and move tcp traffic through it
   (in test file implementations/rust/ockam/ockam_command/tests/bats/portals.bats, line 53)
     `$OCKAM forwarder create "$fwd" --at /project/default --to /node/blue' failed with status 70
   /service/outlet
   Version 0.80.0, hash: a1367541da9826f248a682baeed0b18936e63e87
   The request timed out, please make sure the command's arguments are correct or try again
 ✗ portals - inlet/outlet example with credentials, not provided
   (in test file implementations/rust/ockam/ockam_command/tests/bats/portals.bats, line 83)
     `run "$OCKAM" project enroll --member "$blue_identifier" --attribute role=member' failed with status 130

   Received SIGINT, aborting ...
```

This works fine:

```
bats implementations/rust/ockam/ockam_command/tests/bats
```

**Comment by adrianbenavides** [comment]
@mrinalwadhwa I can only think it's because the enrolled identity is not where expected (i.e. at `$HOME/.ockam`). 

Can you confirm this is not working for you?
```bash
OCKAM_HOME=$HOME/.ockam
ockam reset -y
ockam enroll
ORCHESTRATOR_TESTS=1 LONG_TESTS=1 bats ...
```

**Comment by mrinalwadhwa** [comment]
I suspect the failure I was seeing had to do with my OCKAM_HOME set to some other path other than `$HOME/.ockam`

It's working now, so let's merge this PR.
In a followup we should try to remove the assumption that OCKAM_HOME must be `$HOME/.ockam`

**Review by mrinalwadhwa — APPROVED** [review]

**Pull request merged**
