### PR TITLE
feat(rust): improve status command

### LINKED ISSUE #6063: `ockam status` should provide more user friendly information when a user is enrolled
# Current behavior

Running `ockam status` when a user is enrolled currently displays a lot of debug type information. This information might be useful for developers working on Command, but it isn't directly relevant for users who use the CLI app.

The following screenshot shows what this currently looks like for a user who has previously enrolled successfully using `ockam enroll`. 

Image

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

# Desired behavior

Instead of the low level information that's currently displayed, we can think about the following categories of higher level status information:

- liveness (in real time), eg: is a node currently running or stopped.
- data (persistent), eg: what is the user's enrollment email address.

Here's a list of useful status information for the user that should be displayed when `ockam status` is run for an enrolled user.
- Version of ockam command
- Enrollment status
- Email address used for enrollment
- Trust context
- Identities: Display a check mark like ✅ when a credential exists for an identity.
- List of nodes: Display a red 🔴 or green 🟢 circle beside each node to show liveness.

Note that this type of information would not be used in filing bug reports where log data is required. Log data would be useful in situations where bug reports need to be filed when ockam crashes.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### PR DESCRIPTION
**Pull request by MJoaaquin**
resolves #6063 

Now we are going to show the following information
image

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@MJoaaquin Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by nazmulidris** [comment]
@MJoaaquin Thank you for spending time on this 🎉 . We will take a look at this by tomorrow. 👍🏽

**Comment by adrianbenavides** [comment]
@MJoaaquin don't forget to setup the signing stuff on your github account to verify your commits. [Here is how to do it](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

**Comment by mrinalwadhwa** [comment]
@MJoaaquin to land this PR, our process requires an accepted Contributor License Agreement:

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by MJoaaquin** [comment]
@mrinalwadhwa already sent the PR to add me in contributors.csv and fixed the problem of unverified commits.

**Comment by mrinalwadhwa** [comment]
@MJoaaquin Thank you sending the CLA PR, for while we still have to review this change. I'm adding the HACKTOBERFEST-ACCEPTED label so the contribution is counted by hacktoberfest bots before the end of October. Thank you for taking time to contribute 🎉

**Pull request closed without merging**
