### PR TITLE
fix(rust): before sending the req to delete the TCP (outlet, inlet,listener) check that the target exists

### LINKED ISSUE #6347: Improve `ockam tcp-outlet delete <ALIAS>` when `<ALIAS>` does not exist
# Current behavior

When a user runs `ockam tcp-outlet delete <ALIAS>` and `<ALIAS>` does not exist, then they get a prompt, asking them to confirm whether this command should proceed or not. Then they are shown an error stating that `404 NotFound`.

Image

# Desired behavior

Instead of asking the user for a confirmation prompt, it would be better to first check to see whether `<ALIAS>` even exists. 

1) If it does *not*, then the user should be notified that this alias name doesn't exist and can't be deleted. This can be an error.

2) If it does exist, then the user should be prompted, to confirm whether this destructive operation should proceed. If that operation fails for some reason then an error should be displayed with information on what went wrong (which is the current behavior).

# Implementation details

Take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs#L39) to get started.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

### PR DESCRIPTION
**Pull request by 0x61nas**
Before sending the req to delete the TCP (outlet, inlet, listener) check that the target exist

I'm still unable to figure out how to send a bodyless request to `/node/tcp/listener/` to just check if there is a TCP listener with the target address or not.  I'll appreciate it if someone can help me with this.

- Closes: #6347

## Current behavior
When a user runs `ockam tcp-outlet delete <ALIAS>` or `ockam tcp-inlet delete <ALIAS>` or `ockam tcp-listners delete <ALIAS>`  and ``<ALIAS>`` does not exist, then they get a prompt, asking them to confirm whether this command should proceed or not. Then they are shown an error stating that 404 NotFound.
 
## Proposed changes
- When the user tries to delete one (instance) of mentioned (resources) then send an `get` request to checks if the target are exist in the first place
- If not, then mention this in an error message and exit.
- If the target was exist then process the delete operation as normal

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. done via: build-trust/ockam-contributors/pull/266

### CODE REVIEW

**Review by adrianbenavides — COMMENTED** [review]
Hi @0x61nas, I wanted to apply some format+renaming changes but I couldn't push to your branch. Could you allow maintainers to push on your branch? Here is a guide on how to do it: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by 0x61nas** [comment]
> Hi @0x61nas, I wanted to apply some format+renaming changes but I couldn't push to your branch. Could you allow maintainers to push on your branch? Here is a guide on how to do it: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I'm having trouble finding the mint option, perhaps you meant an invitation to contribute to my repo. If so, I've sent it.

**Comment by adrianbenavides** [comment]
Still nothing, could you try checking this post? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by 0x61nas** [comment]
>  could you try checking this post? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I still can't figure how to do this, even after following the steps. the **Allow edits from maintainers** option in the fourth step doesn't exist

> Still nothing,

could you check this link?
https://github.com/anas-contribs/ockam/invitations

**Comment by adrianbenavides** [comment]
> I still can't figure how to do this, even after following the steps. the Allow edits from maintainers option in the fourth step doesn't exist

I don't know exactly how to fix it, but perhaps it's related to some configuration you have or how you created the fork in the first place.

I've created a PR attaching your commit and keeping your signature at https://github.com/build-trust/ockam/pull/6494. We can close this issue in favor of the other one (the result is the same).

Thanks again for your effor you put in this PR, will get merged soon 🚀

**Pull request closed without merging**
