### PR TITLE
fix(rust): Check address before creating stuff

### LINKED ISSUE #3061: Router doesn't check if address is already taken while starting Worker/Processor

### PR DESCRIPTION
**Pull request by pro465**
## Current Behavior

described in #3061 

## Proposed Changes

fixes #3061.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by pro465** [comment]
github didn't even let me edit the commit message before pushing 😞

**Comment by pro465** [comment]
okay i accidentally did the opposite 😄

**Comment by pro465** [comment]
oh no, did the same thing because of laziness 😭

**Comment by pro465** [comment]
ok now it should be fixed

**Comment by pro465** [comment]
okay it should pass now

**Review by SanjoDeundiak — DISMISSED** [review]
Hey @pro465 , thank you for the contribution. I think the problem here is that router should reply with an error using `reply` mpsc sender, so that caller could handle the error correctly. Could you please also add a simple test for that scenario? Tnx!

**Comment by pro465** [comment]
@SanjoDeundiak thank you for reviewing this! I don't know what would constitute a good test for this, but i will try nevertheless

**Comment by pro465** [comment]
hey @SanjoDeundiak i have a question: do we need to check the secondary addresses too? or just the primary address?

**Comment by pro465** [comment]
@SanjoDeundiak i dunno a good test, but  i'm guessing this:
```rust
#[test]
#[ockam::node]
async fn no_dup_addresses(ctx: &mut Context) {
    // create router
    // send StartWorker message
    // recieve message
    // assert recieved message is an error
}
```

**Comment by mrinalwadhwa** [comment]
@pro465 before you add the test.
Do you mind if I modify [your branch](https://github.com/pro465/ockam/tree/check-addr) to remove the [merge commit](https://github.com/build-trust/ockam/runs/7702259611?check_suite_focus=true), so its easy to land when ready?

**Comment by pro465** [comment]
@mrinalwadhwa no, I would not mind that. In fact I want that, so thank you for the offer!

**Comment by mrinalwadhwa** [comment]
@pro465 all set. just add new commits from here, don't do any merges and we can squash when landing the pr.

**Comment by pro465** [comment]
ok thank you!

**Comment by pro465** [comment]
@SanjoDeundiak should i create a raw Router for the test,
or is there a high-level fn that i can call, that automatically does what i want, and i can simply just assert the result is an error when calling it twice?

**Comment by mrinalwadhwa** [comment]
@pro465 checkout the tests here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_node/src/tests.rs

**Comment by pro465** [comment]
@mrinalwadhwa how do i specify that the furst `start_{worker, processor}` call should pass and only the second call should fail?

**Comment by mrinalwadhwa** [comment]
Maybe:

1. start first worker
2. send it a message
3. receive an expected reply based on what the worker does - maybe an echo
4. start a second worker with the same name
5. receive a message
6. assert received message is an error

**Comment by pro465** [comment]
> @mrinalwadhwa: 

> 



> Maybe:
> 
> [..]
> 4. start a second worker with the same name
> 5. receive a message
> 6. assert received message is an error

I'm confused, should not the second `start_worker` call return an error? or should it instead return Ok but send an Err thru the mpsc?

**Comment by pro465** [comment]
(just to clarify, the it does send Err thru the mpsc, but the Context seem to catch it in the `start_worker` call and return if it is an Err, which is why i think the mpsc should not contain an error after returning from `start_worker`)

**Comment by mrinalwadhwa** [comment]
You're right, the tests you've added look great. I'll merge shortly.

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by pro465** [comment]
@mrinalwadhwa thank you!

**Comment by mrinalwadhwa** [comment]
@pro465 Thank you for another awesome contribution 👏 👏

**Pull request merged**
