### PR TITLE
refactor(rust): Rename ockam policy set/get to ockam policy create/show

### LINKED ISSUE #4488: Rename `ockam policy set/get ...` to `ockam policy create/show ...`
### Current behavior

Here's a full example of policies in action
https://docs.ockam.io/guides/use-cases/apply-fine-grained-permissions-with-attribute-based-access-control-abac#step-by-step-walkthrough

The current commands are 

```
ockam policy set ...
```

and 

```
ockam policy get ...
```

The source code is here:
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/policy

### Desired behavior

Rename the `set` command to

```
ockam policy create ...
```

Rename the `get` command to

```
ockam policy show ...
```

### PR DESCRIPTION
**Pull request by MehSalhi**
## Current behavior

The current command to change a policy are : 

```
ockam policy set ...
ockam policy get ...

```
## Proposed changes

This command will be renamed to be : 
 
```
ockam policy create ...
ockam policy show ...
```

Should close #4488 

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

**Comment by MehSalhi** [comment]
This is my very first contribution. Feel free to give any insight and guidance.

**Review by mrinalwadhwa — DISMISSED** [review]
@MehSalhi The changes look great. Congratulations on an awesome first contribution.

**Comment by mrinalwadhwa** [comment]
@metaclips @adrianbenavides I was about to merge this but realized this likely breaks bats test and various demos however CI didn't catch. Could you take a look and decide when to merge.

**Comment by adrianbenavides** [comment]
> @metaclips @adrianbenavides I was about to merge this but realized this likely breaks bats test and various demos however CI didn't catch. Could you take a look and decide when to merge.

The tests using the `policy get/set` commands are only run when merging into develop, so this PR will fail to get merged unless the tests are fixed. We should fix the tests in this PR and then merge it along with the docs changes.

**Comment by MehSalhi** [comment]
Noted. I will look into the tests.

**Comment by MehSalhi** [comment]
I renamed the commands used by the tests and it should work now.

I also noticed that the following files use the old policy set/get commands:

- ockam/demos/influxdb-telegraf/telegraf/start_ockam.sh
- ockam/demos/influxdb-telegraf/influxdb/start_ockam.sh

Should I also rename these ?

As for the documentation, it seems the 'policy' subcommand is missing in your manual here : https://command.ockam.io/manual/

**Comment by metaclips** [comment]
> @metaclips @adrianbenavides I was about to merge this but realized this likely breaks bats test and various demos however CI didn't catch. Could you take a look and decide when to merge.

~CI should catch that when it’s on the merge queue as the PR will be rebased with develop branch and the CI run on the rebase~ Misinterpreted the issue to be due to a branch conflict, apologies.

**Comment by etorreborre** [comment]
> As for the documentation, it seems the 'policy' subcommand is missing in your manual here : https://command.ockam.io/manual/

☝️ @CAOakleyII @adrianbenavides FYI

**Comment by etorreborre** [comment]
> Should I also rename these ?

@MehSalhi Thanks for your contribution! You're absolutely right, those 2 commands need to be updated. I did it in the last commit.

**Review by davide-baldo — DISMISSED** [review]

**Review by etorreborre — APPROVED** [review]

**Review by SanjoDeundiak — APPROVED** [review]

**Pull request merged**
