### PR TITLE
markdown generator

### LINKED ISSUE #4253: Generate a markdown manual from command help
We want to generate a website that that looks like this https://cli.github.com/manual/
As a first step, let's generate markdown with an index of links, we can then use a static site generator to generate html from the markdown.

Ockam Command has very similar struct to gh command - `ockam NOUN VERB`

We use clap as our command line framework, Ockam Command source code is here
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src

It's possible to get Clap's full help output at build time
https://github.com/clap-rs/clap/discussions/4475
https://docs.rs/clap/latest/clap/

There is currently `ockam manpages` command to generate man pages, we could generate man pages first and then generate html/markdown from it using pandoc. I tried that but it gives us very little control on the rendered HTML pages. I think just generating the markdown/html ourselves would be better.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by murex971**
Resolves #4253

## Proposed Changes

Generate markdown pages for ockam command
An example of generated page:

---
## `lease`

**Usage:** `ockam lease [OPTIONS] <COMMAND>`

#### **Subcommands:**

* create
* list
* show
* revoke

#### **Options:**

* `--identity <IDENTITY>`
* `--project-path <PROJECT_JSON_PATH>` — Project config file
---

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@murex971 this is already excellent 🥳 

A few things that would be great improvements:

1. make all generated files have a `.md` extension
2. link subcommands.
3. make a SUMMARY.md file with the assumption that we'll use mdbook to turn markdown pages into an html website. Don't worry about generating the other configuration files for mdbook, we can hardcode them as long as have the structure and SUMMARY.md that mdbook expects.
https://rust-lang.github.io/mdBook/guide/creating.html
https://rust-lang.github.io/mdBook/format/summary.html
4. Could we do the markdown generation at compile time (maybe with our [build.rs](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/build.rs) instead of adding a new command?

Thank you for working on this, please let me know if you have any questions.

**Comment by mrinalwadhwa** [comment]
I created a little place holder for where the generated HTML output will go.

The mdbook rendered html will be committed to this folder. One per released version
https://github.com/build-trust/ockam-documentation/tree/command/manual/v0.82.0

Initially we can do this commit manually but later turn that into a github action than runs on ever new release.

This will render as a website here
https://command.ockam.io/manual/v0.82.0/

**Comment by mrinalwadhwa** [comment]
To take the above comment further, I generated a live version using you code in this PR

https://command.ockam.io/manual/v0.81.0
It's looks really nice thanks to your great work!!

The script that generates it is here
https://github.com/build-trust/ockam-documentation/blob/command/manual/template/mdbook/build.sh

Note I manually wrote the SUMMARY.md file
https://github.com/build-trust/ockam-documentation/blob/command/manual/template/mdbook/SUMMARY.md

I also added .md extension.

**Comment by murex971** [comment]
@mrinalwadhwa  refactored and cleaned code up a bit
1) files have .md extension
2) subcommands are linked
3) title is modified to include parent command as well as highlighted properly
4) help part of arguments appear in next line

Now the markdown looks like this:

---
##  lease

---
`ockam lease [OPTIONS] <COMMAND>`

#### **Subcommands:**

* [create](ockam-lease-create.md)
* [list](ockam-lease-list.md)
* [show](ockam-lease-show.md)
* [revoke](ockam-lease-revoke.md)

#### **Options:**

* `--identity <IDENTITY>`
* `--project-path <PROJECT_JSON_PATH>`<br/>
Project config file
---

**Comment by mrinalwadhwa** [comment]
The links end up with an extra `-` somehow
See subcommands section here: https://command.ockam.io/manual/v0.81.0/ockam.html

**Comment by murex971** [comment]
fixed :+1:

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
I manually [populated the full SUMMARY.md](https://github.com/build-trust/ockam-documentation/blob/command/manual/template/mdbook/SUMMARY.md) and rendered output looks great
https://command.ockam.io/manual/

Let's merge this PR and tackle further improvements in follow on PR. The main next thing is generate SUMMARY.md. I'll also write some notes on other things that would be nice to improve.

Thank you for this awesome contribution 🥳

**Pull request merged**
