### PR TITLE
test(rust): add unit test for the medic session

### PR DESCRIPTION
**Pull request by Alef-gabriel**
## Description
introduces unit test for the functionality responsible for restarting the topology, including TCP connections, secure channels, etc., for Ockam Relays and Inlets.

## Changes Made

- Added integration tests for the restart mechanism.
- Simulated the monitoring of Sessions and periodic ping messages.
- Verified the detection of outages and the subsequent recreation of routes, Relays, and Inlets.

### CODE REVIEW

**Comment by davide-baldo** [comment]
The current design doesn't spawn sessions yet, but this is a great start! I'd love to see this test completed. Are there any questions or information that you need from us?

**Comment by Alef-gabriel** [comment]
@davide-baldo thanks, I'll go to restoration and complete this task.

**Comment by Alef-gabriel** [comment]
@davide-baldo can you help-me?  I've trying spawn sessions, but I don't understand the Context yet. Do you have a code example?

**Comment by davide-baldo** [comment]
@Alef-gabriel 

Sure! The context is your mean to interact with the system:
 - it's tied to at least one `Mailbox`  (a mailbox is a box where messages are received)
 - it can spawn new workers (since it has access to both runtime (tokio) and the Router)
 - control the whole `Node`
 
In particular, `Context::stop()` will stop every worker, in tests this is usually at the end.

Sessions, on the other hand, are a concept built on **top of** context (meaning you could reimplement it without modifying the context code).
The sessions are currently used in the `ockam_api` module, during the creation of inlets and forwarders (aka relays).
That said, you don't need to test existing sessions usages, you can create a dummy session specifically to test re-creation.

I've modified your code in this gist with some explanatory comments to show how you could test it:  https://gist.github.com/davide-baldo/4d5b5850eef5135098a74c9f4fdf6797

Fell free to use it however you like. Testing time-based asynchronous code is **very** tricky, and the resulting code is far from being simple, so don't hold back any questions or doubt you may have!

And thank you again for taking the time to contribute!

**Comment by Alef-gabriel** [comment]
@davide-baldo thank you so much. I'm learning a lot

**Pull request closed without merging**
